// Generated by gen_emitter_ts.ts
// Copyright (c) 2026 Roberto Raggi <roberto.raggi@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

export type BlockRef = number;
export type CleanupRegionRef = number;
export type FunctionRef = number;
export type GlobalRef = number;
export type InsertionPointRef = number;
export type ModuleRef = number;
export type TypeRef = number;
export type ValueRef = number;

export type TokenIndex = number;

export enum InsertionPointKind {
  BlockStart = 0,
  BlockEnd = 1,
  ModuleStart = 2,
  ModuleEnd = 3,
}

export enum InitializerKind {
  None = 0,
  Integer = 1,
  Floating = 2,
  Bytes = 3,
  Aggregate = 4,
  Null = 5,
  Zero = 6,
  ScalarZero = 7,
  Undef = 8,
  SignalingNaN = 9,
}

export enum TodoKind {
  Expression = 0,
  Statement = 1,
}

export enum UnaryOp {
  NegateFloat = 0,
}

export enum Linkage {
  External = 0,
  Internal = 1,
  LinkOnceODR = 2,
  WeakODR = 3,
  AvailableExternally = 4,
  Appending = 5,
}

export enum BinaryOp {
  AddInt = 0,
  SubInt = 1,
  MulInt = 2,
  SignedDiv = 3,
  UnsignedDiv = 4,
  SignedRem = 5,
  UnsignedRem = 6,
  AndInt = 7,
  OrInt = 8,
  XorInt = 9,
  ShiftLeft = 10,
  ArithmeticShiftRight = 11,
  LogicalShiftRight = 12,
  AddFloat = 13,
  SubFloat = 14,
  MulFloat = 15,
  DivFloat = 16,
}

export enum IntPredicate {
  Equal = 0,
  NotEqual = 1,
  SignedLess = 2,
  SignedLessEqual = 3,
  SignedGreater = 4,
  SignedGreaterEqual = 5,
  UnsignedLess = 6,
  UnsignedLessEqual = 7,
  UnsignedGreater = 8,
  UnsignedGreaterEqual = 9,
}

export enum FloatPredicate {
  OrderedEqual = 0,
  OrderedNotEqual = 1,
  OrderedLess = 2,
  OrderedLessEqual = 3,
  OrderedGreater = 4,
  OrderedGreaterEqual = 5,
  UnorderedNotEqual = 6,
  Unordered = 7,
}

export enum FloatKind {
  Half = 0,
  Single = 1,
  Double = 2,
  X87DoubleExtended = 3,
  Quad = 4,
}

export enum CastKind {
  Truncate = 0,
  SignExtend = 1,
  ZeroExtend = 2,
  FloatExtend = 3,
  FloatTruncate = 4,
  SignedIntToFloat = 5,
  UnsignedIntToFloat = 6,
  FloatToSignedInt = 7,
  FloatToUnsignedInt = 8,
  ReinterpretBits = 9,
  Bitcast = 10,
  Reshape = 11,
  ArrayToPointer = 12,
  PointerToInt = 13,
  IntToPointer = 14,
}

export enum TypeKind {
  Void = 0,
  Integer = 1,
  Floating = 2,
  Pointer = 3,
  Array = 4,
  Class = 5,
  Function = 6,
  Unresolved = 7,
  Other = 8,
}

export enum CallKind {
  Direct = 0,
  Builtin = 1,
}

export enum ParameterAbiKind {
  Default = 0,
  StructReturn = 1,
  ByValue = 2,
}

export enum Visibility {
  Default = 0,
  Hidden = 1,
  Protected = 2,
}

export enum InlineKind {
  NoInline = 0,
  InlineHint = 1,
}

export interface InsertionPoint {
  kind: InsertionPointKind;
  block: BlockRef;
}

export interface Initializer {
  kind: InitializerKind;
  type: TypeRef;
  integer: number;
  floating: number;
  bytes: Uint8Array;
  elements: readonly Initializer[];
}

export interface VTableInfo {
  name: string;
  typeInfo: string;
  tables: readonly VTableTableInfo[];
  linkage: Linkage;
}

export interface VTableTableInfo {
  virtualBaseOffsets: readonly number[];
  virtualCallOffsets: readonly number[];
  offsetToTop: number;
  slots: readonly FunctionRef[];
}

export interface ModuleInfo {
  name: string;
  sourceFile: string;
  targetTriple: string;
  debugCompilationDirectory: string;
}

export interface CleanupTarget {
  block: BlockRef;
  label: string;
}

export interface CleanupAction {
  address: ValueRef;
  destructor: FunctionRef;
  depth: number;
  activeFlag: ValueRef;
}

export interface Access {
  alignment: number;
  bitfield: BitfieldInfo | undefined;
  isSigned: boolean;
}

export interface BitfieldInfo {
  bitOffset: number;
  bitWidth: number;
  alignment: number;
}

export interface CallInfo {
  kind: CallKind;
  callee: string;
  indirectCallee: ValueRef;
  arguments: readonly ValueRef[];
  results: readonly TypeRef[];
  parameters: readonly ParameterAbi[];
  variadicCalleeType: TypeRef;
}

export interface ParameterAbi {
  kind: ParameterAbiKind;
  indirectType: TypeRef;
  alignment: number;
}

export interface FunctionInfo {
  name: string;
  type: TypeRef;
  linkage: Linkage;
  visibility: Visibility;
  inlineKind: InlineKind;
  aliasName: string;
  importModule: string;
  importName: string;
  exportName: string;
  isUsed: boolean;
  parameters: readonly ParameterAbi[];
}

export interface GlobalInfo {
  name: string;
  type: TypeRef;
  linkage: Linkage;
  isConstant: boolean;
  alignment: number;
  initializer: Initializer;
  unknownLocation: boolean;
  isUsed: boolean;
}

export interface EmitterDelegate {
  saveInsertionPoint(): InsertionPointRef;
  restoreInsertionPoint(point: InsertionPointRef): void;
  setInsertionPoint(point: InsertionPoint): void;
  beginGlobalInitializer(global: GlobalRef): void;
  globalConstructor(loc: TokenIndex, function_: FunctionRef): void;
  constant(loc: TokenIndex, type: TypeRef, value: Initializer): ValueRef;
  isZeroConstant(value: ValueRef): boolean;
  symbolExists(name: string): boolean;
  todo(loc: TokenIndex, kind: TodoKind, message: string): ValueRef;
  unaryOp(
    loc: TokenIndex,
    op: UnaryOp,
    type: TypeRef,
    value: ValueRef,
  ): ValueRef;
  defineVTable(loc: TokenIndex, info: VTableInfo): void;
  beginModule(info: ModuleInfo): ModuleRef;
  endModule(): void;
  beginFunctionBody(function_: FunctionRef): void;
  endFunctionBody(function_: FunctionRef): void;
  beginCleanupRegion(): CleanupRegionRef;
  endCleanupRegion(region: CleanupRegionRef): void;
  activateConditionalCleanup(
    address: ValueRef,
    entry: BlockRef,
    region: CleanupRegionRef,
  ): ValueRef;
  switchBranch(
    loc: TokenIndex,
    flag: ValueRef,
    defaultDest: BlockRef,
    caseValues: readonly number[],
    caseDestinations: readonly BlockRef[],
  ): void;
  defineLabel(loc: TokenIndex, name: string, cleanupDepth: number): void;
  branchWithCleanups(
    loc: TokenIndex,
    target: CleanupTarget,
    cleanups: readonly CleanupAction[],
  ): void;
  indirectGoto(loc: TokenIndex, target: ValueRef): void;
  labelAddress(
    loc: TokenIndex,
    type: TypeRef,
    name: string,
    function_: FunctionRef,
  ): ValueRef;
  resolveFunctionControlFlow(function_: FunctionRef): void;
  functionParameterTypes(function_: FunctionRef): TypeRef[];
  functionResultTypes(function_: FunctionRef): TypeRef[];
  addBlockParameter(block: BlockRef, type: TypeRef, loc: TokenIndex): ValueRef;
  blockParameter(block: BlockRef, index: number): ValueRef;
  blockParameterCount(block: BlockRef): number;
  createBlock(function_: FunctionRef): BlockRef;
  insertionBlock(): BlockRef;
  eraseBlock(block: BlockRef): void;
  hasTerminator(block: BlockRef): boolean;
  branch(
    loc: TokenIndex,
    target: BlockRef,
    operands: readonly ValueRef[],
  ): void;
  globalLinkage(global: GlobalRef): Linkage;
  condBranch(
    loc: TokenIndex,
    condition: ValueRef,
    trueDest: BlockRef,
    falseDest: BlockRef,
  ): void;
  binaryOp(
    loc: TokenIndex,
    op: BinaryOp,
    lhs: ValueRef,
    rhs: ValueRef,
  ): ValueRef;
  compareInt(
    loc: TokenIndex,
    predicate: IntPredicate,
    lhs: ValueRef,
    rhs: ValueRef,
  ): ValueRef;
  compareFloat(
    loc: TokenIndex,
    predicate: FloatPredicate,
    lhs: ValueRef,
    rhs: ValueRef,
  ): ValueRef;
  select(
    loc: TokenIndex,
    condition: ValueRef,
    ifTrue: ValueRef,
    ifFalse: ValueRef,
  ): ValueRef;
  voidType(): TypeRef;
  unresolvedType(): TypeRef;
  integerType(bits: number): TypeRef;
  floatingType(kind: FloatKind): TypeRef;
  pointerType(elementType: TypeRef): TypeRef;
  arrayType(elementType: TypeRef, size: number): TypeRef;
  vectorType(elementType: TypeRef, elementCount: number): TypeRef;
  vectorSplat(loc: TokenIndex, vectorType: TypeRef, scalar: ValueRef): ValueRef;
  functionType(
    parameters: readonly TypeRef[],
    results: readonly TypeRef[],
    isVariadic: boolean,
  ): TypeRef;
  declareClassType(name: string): TypeRef;
  defineClassType(
    classType: TypeRef,
    members: readonly TypeRef[],
    isPacked: boolean,
  ): void;
  convert(
    loc: TokenIndex,
    kind: CastKind,
    value: ValueRef,
    type: TypeRef,
  ): ValueRef;
  typeKind(type: TypeRef): TypeKind;
  scalarWidth(type: TypeRef): number;
  elementType(type: TypeRef): TypeRef;
  typeOf(value: ValueRef): TypeRef;
  allocate(
    loc: TokenIndex,
    pointerType: TypeRef,
    size: ValueRef,
    alignment: number,
  ): ValueRef;
  load(
    loc: TokenIndex,
    valueType: TypeRef,
    address: ValueRef,
    access: Access,
  ): ValueRef;
  pointerAdd(
    loc: TokenIndex,
    pointerType: TypeRef,
    base: ValueRef,
    offset: ValueRef,
  ): ValueRef;
  pointerDiff(
    loc: TokenIndex,
    resultType: TypeRef,
    lhs: ValueRef,
    rhs: ValueRef,
  ): ValueRef;
  subscript(
    loc: TokenIndex,
    pointerType: TypeRef,
    base: ValueRef,
    index: ValueRef,
  ): ValueRef;
  memberAddress(
    loc: TokenIndex,
    pointerType: TypeRef,
    base: ValueRef,
    index: number,
  ): ValueRef;
  extractValue(
    loc: TokenIndex,
    resultType: TypeRef,
    container: ValueRef,
    position: number,
  ): ValueRef;
  insertValue(
    loc: TokenIndex,
    resultType: TypeRef,
    container: ValueRef,
    value: ValueRef,
    position: number,
  ): ValueRef;
  addressOfSymbol(
    loc: TokenIndex,
    resultType: TypeRef,
    symbol: string,
  ): ValueRef;
  store(
    loc: TokenIndex,
    value: ValueRef,
    address: ValueRef,
    access: Access,
  ): void;
  memsetZero(loc: TokenIndex, address: ValueRef, size: number): void;
  memcpy(
    loc: TokenIndex,
    destination: ValueRef,
    source: ValueRef,
    size: number,
  ): void;
  unreachable(loc: TokenIndex): void;
  call(loc: TokenIndex, info: CallInfo): ValueRef[];
  ret(loc: TokenIndex, values: readonly ValueRef[]): void;
  findFunction(name: string): FunctionRef;
  declareFunction(loc: TokenIndex, info: FunctionInfo): FunctionRef;
  functionHasBody(function_: FunctionRef): boolean;
  findGlobal(name: string): GlobalRef;
  declareGlobal(loc: TokenIndex, info: GlobalInfo): GlobalRef;
}
