// Generated by gen_emitter_delegate_h.ts
// Copyright (c) 2026 Roberto Raggi <roberto.raggi@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

#include <cxx/codegen/emitter.h>

#include "emitter_marshal.h"

namespace cxx::js {

inline auto toVal(cxx::ir::InsertionPoint::Kind value) -> val {
  switch (value) {
    case cxx::ir::InsertionPoint::Kind::BlockStart:
      return val("BlockStart");
    case cxx::ir::InsertionPoint::Kind::BlockEnd:
      return val("BlockEnd");
    case cxx::ir::InsertionPoint::Kind::ModuleStart:
      return val("ModuleStart");
    case cxx::ir::InsertionPoint::Kind::ModuleEnd:
      return val("ModuleEnd");
  }
  return val::undefined();
}

template <>
inline auto toEnum<cxx::ir::InsertionPoint::Kind>(const val& value)
    -> cxx::ir::InsertionPoint::Kind {
  const auto name = toString(value);
  if (name == "BlockStart") return cxx::ir::InsertionPoint::Kind::BlockStart;
  if (name == "BlockEnd") return cxx::ir::InsertionPoint::Kind::BlockEnd;
  if (name == "ModuleStart") return cxx::ir::InsertionPoint::Kind::ModuleStart;
  if (name == "ModuleEnd") return cxx::ir::InsertionPoint::Kind::ModuleEnd;
  return cxx::ir::InsertionPoint::Kind{};
}

inline auto toVal(cxx::ir::Initializer::Kind value) -> val {
  switch (value) {
    case cxx::ir::Initializer::Kind::None:
      return val("None");
    case cxx::ir::Initializer::Kind::Integer:
      return val("Integer");
    case cxx::ir::Initializer::Kind::Floating:
      return val("Floating");
    case cxx::ir::Initializer::Kind::Bytes:
      return val("Bytes");
    case cxx::ir::Initializer::Kind::Aggregate:
      return val("Aggregate");
    case cxx::ir::Initializer::Kind::Null:
      return val("Null");
    case cxx::ir::Initializer::Kind::Zero:
      return val("Zero");
    case cxx::ir::Initializer::Kind::ScalarZero:
      return val("ScalarZero");
    case cxx::ir::Initializer::Kind::Undef:
      return val("Undef");
    case cxx::ir::Initializer::Kind::SignalingNaN:
      return val("SignalingNaN");
  }
  return val::undefined();
}

template <>
inline auto toEnum<cxx::ir::Initializer::Kind>(const val& value)
    -> cxx::ir::Initializer::Kind {
  const auto name = toString(value);
  if (name == "None") return cxx::ir::Initializer::Kind::None;
  if (name == "Integer") return cxx::ir::Initializer::Kind::Integer;
  if (name == "Floating") return cxx::ir::Initializer::Kind::Floating;
  if (name == "Bytes") return cxx::ir::Initializer::Kind::Bytes;
  if (name == "Aggregate") return cxx::ir::Initializer::Kind::Aggregate;
  if (name == "Null") return cxx::ir::Initializer::Kind::Null;
  if (name == "Zero") return cxx::ir::Initializer::Kind::Zero;
  if (name == "ScalarZero") return cxx::ir::Initializer::Kind::ScalarZero;
  if (name == "Undef") return cxx::ir::Initializer::Kind::Undef;
  if (name == "SignalingNaN") return cxx::ir::Initializer::Kind::SignalingNaN;
  return cxx::ir::Initializer::Kind{};
}

inline auto toVal(cxx::ir::TodoKind value) -> val {
  switch (value) {
    case cxx::ir::TodoKind::Expression:
      return val("Expression");
    case cxx::ir::TodoKind::Statement:
      return val("Statement");
  }
  return val::undefined();
}

template <>
inline auto toEnum<cxx::ir::TodoKind>(const val& value) -> cxx::ir::TodoKind {
  const auto name = toString(value);
  if (name == "Expression") return cxx::ir::TodoKind::Expression;
  if (name == "Statement") return cxx::ir::TodoKind::Statement;
  return cxx::ir::TodoKind{};
}

inline auto toVal(cxx::ir::UnaryOp value) -> val {
  switch (value) {
    case cxx::ir::UnaryOp::NegateFloat:
      return val("NegateFloat");
  }
  return val::undefined();
}

template <>
inline auto toEnum<cxx::ir::UnaryOp>(const val& value) -> cxx::ir::UnaryOp {
  const auto name = toString(value);
  if (name == "NegateFloat") return cxx::ir::UnaryOp::NegateFloat;
  return cxx::ir::UnaryOp{};
}

inline auto toVal(cxx::ir::Linkage value) -> val {
  switch (value) {
    case cxx::ir::Linkage::External:
      return val("External");
    case cxx::ir::Linkage::Internal:
      return val("Internal");
    case cxx::ir::Linkage::LinkOnceODR:
      return val("LinkOnceODR");
    case cxx::ir::Linkage::WeakODR:
      return val("WeakODR");
    case cxx::ir::Linkage::AvailableExternally:
      return val("AvailableExternally");
    case cxx::ir::Linkage::Appending:
      return val("Appending");
  }
  return val::undefined();
}

template <>
inline auto toEnum<cxx::ir::Linkage>(const val& value) -> cxx::ir::Linkage {
  const auto name = toString(value);
  if (name == "External") return cxx::ir::Linkage::External;
  if (name == "Internal") return cxx::ir::Linkage::Internal;
  if (name == "LinkOnceODR") return cxx::ir::Linkage::LinkOnceODR;
  if (name == "WeakODR") return cxx::ir::Linkage::WeakODR;
  if (name == "AvailableExternally")
    return cxx::ir::Linkage::AvailableExternally;
  if (name == "Appending") return cxx::ir::Linkage::Appending;
  return cxx::ir::Linkage{};
}

inline auto toVal(cxx::ir::BinaryOp value) -> val {
  switch (value) {
    case cxx::ir::BinaryOp::AddInt:
      return val("AddInt");
    case cxx::ir::BinaryOp::SubInt:
      return val("SubInt");
    case cxx::ir::BinaryOp::MulInt:
      return val("MulInt");
    case cxx::ir::BinaryOp::SignedDiv:
      return val("SignedDiv");
    case cxx::ir::BinaryOp::UnsignedDiv:
      return val("UnsignedDiv");
    case cxx::ir::BinaryOp::SignedRem:
      return val("SignedRem");
    case cxx::ir::BinaryOp::UnsignedRem:
      return val("UnsignedRem");
    case cxx::ir::BinaryOp::AndInt:
      return val("AndInt");
    case cxx::ir::BinaryOp::OrInt:
      return val("OrInt");
    case cxx::ir::BinaryOp::XorInt:
      return val("XorInt");
    case cxx::ir::BinaryOp::ShiftLeft:
      return val("ShiftLeft");
    case cxx::ir::BinaryOp::ArithmeticShiftRight:
      return val("ArithmeticShiftRight");
    case cxx::ir::BinaryOp::LogicalShiftRight:
      return val("LogicalShiftRight");
    case cxx::ir::BinaryOp::AddFloat:
      return val("AddFloat");
    case cxx::ir::BinaryOp::SubFloat:
      return val("SubFloat");
    case cxx::ir::BinaryOp::MulFloat:
      return val("MulFloat");
    case cxx::ir::BinaryOp::DivFloat:
      return val("DivFloat");
  }
  return val::undefined();
}

template <>
inline auto toEnum<cxx::ir::BinaryOp>(const val& value) -> cxx::ir::BinaryOp {
  const auto name = toString(value);
  if (name == "AddInt") return cxx::ir::BinaryOp::AddInt;
  if (name == "SubInt") return cxx::ir::BinaryOp::SubInt;
  if (name == "MulInt") return cxx::ir::BinaryOp::MulInt;
  if (name == "SignedDiv") return cxx::ir::BinaryOp::SignedDiv;
  if (name == "UnsignedDiv") return cxx::ir::BinaryOp::UnsignedDiv;
  if (name == "SignedRem") return cxx::ir::BinaryOp::SignedRem;
  if (name == "UnsignedRem") return cxx::ir::BinaryOp::UnsignedRem;
  if (name == "AndInt") return cxx::ir::BinaryOp::AndInt;
  if (name == "OrInt") return cxx::ir::BinaryOp::OrInt;
  if (name == "XorInt") return cxx::ir::BinaryOp::XorInt;
  if (name == "ShiftLeft") return cxx::ir::BinaryOp::ShiftLeft;
  if (name == "ArithmeticShiftRight")
    return cxx::ir::BinaryOp::ArithmeticShiftRight;
  if (name == "LogicalShiftRight") return cxx::ir::BinaryOp::LogicalShiftRight;
  if (name == "AddFloat") return cxx::ir::BinaryOp::AddFloat;
  if (name == "SubFloat") return cxx::ir::BinaryOp::SubFloat;
  if (name == "MulFloat") return cxx::ir::BinaryOp::MulFloat;
  if (name == "DivFloat") return cxx::ir::BinaryOp::DivFloat;
  return cxx::ir::BinaryOp{};
}

inline auto toVal(cxx::ir::IntPredicate value) -> val {
  switch (value) {
    case cxx::ir::IntPredicate::Equal:
      return val("Equal");
    case cxx::ir::IntPredicate::NotEqual:
      return val("NotEqual");
    case cxx::ir::IntPredicate::SignedLess:
      return val("SignedLess");
    case cxx::ir::IntPredicate::SignedLessEqual:
      return val("SignedLessEqual");
    case cxx::ir::IntPredicate::SignedGreater:
      return val("SignedGreater");
    case cxx::ir::IntPredicate::SignedGreaterEqual:
      return val("SignedGreaterEqual");
    case cxx::ir::IntPredicate::UnsignedLess:
      return val("UnsignedLess");
    case cxx::ir::IntPredicate::UnsignedLessEqual:
      return val("UnsignedLessEqual");
    case cxx::ir::IntPredicate::UnsignedGreater:
      return val("UnsignedGreater");
    case cxx::ir::IntPredicate::UnsignedGreaterEqual:
      return val("UnsignedGreaterEqual");
  }
  return val::undefined();
}

template <>
inline auto toEnum<cxx::ir::IntPredicate>(const val& value)
    -> cxx::ir::IntPredicate {
  const auto name = toString(value);
  if (name == "Equal") return cxx::ir::IntPredicate::Equal;
  if (name == "NotEqual") return cxx::ir::IntPredicate::NotEqual;
  if (name == "SignedLess") return cxx::ir::IntPredicate::SignedLess;
  if (name == "SignedLessEqual") return cxx::ir::IntPredicate::SignedLessEqual;
  if (name == "SignedGreater") return cxx::ir::IntPredicate::SignedGreater;
  if (name == "SignedGreaterEqual")
    return cxx::ir::IntPredicate::SignedGreaterEqual;
  if (name == "UnsignedLess") return cxx::ir::IntPredicate::UnsignedLess;
  if (name == "UnsignedLessEqual")
    return cxx::ir::IntPredicate::UnsignedLessEqual;
  if (name == "UnsignedGreater") return cxx::ir::IntPredicate::UnsignedGreater;
  if (name == "UnsignedGreaterEqual")
    return cxx::ir::IntPredicate::UnsignedGreaterEqual;
  return cxx::ir::IntPredicate{};
}

inline auto toVal(cxx::ir::FloatPredicate value) -> val {
  switch (value) {
    case cxx::ir::FloatPredicate::OrderedEqual:
      return val("OrderedEqual");
    case cxx::ir::FloatPredicate::OrderedNotEqual:
      return val("OrderedNotEqual");
    case cxx::ir::FloatPredicate::OrderedLess:
      return val("OrderedLess");
    case cxx::ir::FloatPredicate::OrderedLessEqual:
      return val("OrderedLessEqual");
    case cxx::ir::FloatPredicate::OrderedGreater:
      return val("OrderedGreater");
    case cxx::ir::FloatPredicate::OrderedGreaterEqual:
      return val("OrderedGreaterEqual");
    case cxx::ir::FloatPredicate::UnorderedNotEqual:
      return val("UnorderedNotEqual");
    case cxx::ir::FloatPredicate::Unordered:
      return val("Unordered");
  }
  return val::undefined();
}

template <>
inline auto toEnum<cxx::ir::FloatPredicate>(const val& value)
    -> cxx::ir::FloatPredicate {
  const auto name = toString(value);
  if (name == "OrderedEqual") return cxx::ir::FloatPredicate::OrderedEqual;
  if (name == "OrderedNotEqual")
    return cxx::ir::FloatPredicate::OrderedNotEqual;
  if (name == "OrderedLess") return cxx::ir::FloatPredicate::OrderedLess;
  if (name == "OrderedLessEqual")
    return cxx::ir::FloatPredicate::OrderedLessEqual;
  if (name == "OrderedGreater") return cxx::ir::FloatPredicate::OrderedGreater;
  if (name == "OrderedGreaterEqual")
    return cxx::ir::FloatPredicate::OrderedGreaterEqual;
  if (name == "UnorderedNotEqual")
    return cxx::ir::FloatPredicate::UnorderedNotEqual;
  if (name == "Unordered") return cxx::ir::FloatPredicate::Unordered;
  return cxx::ir::FloatPredicate{};
}

inline auto toVal(cxx::ir::FloatKind value) -> val {
  switch (value) {
    case cxx::ir::FloatKind::Half:
      return val("Half");
    case cxx::ir::FloatKind::Single:
      return val("Single");
    case cxx::ir::FloatKind::Double:
      return val("Double");
    case cxx::ir::FloatKind::X87DoubleExtended:
      return val("X87DoubleExtended");
    case cxx::ir::FloatKind::Quad:
      return val("Quad");
  }
  return val::undefined();
}

template <>
inline auto toEnum<cxx::ir::FloatKind>(const val& value) -> cxx::ir::FloatKind {
  const auto name = toString(value);
  if (name == "Half") return cxx::ir::FloatKind::Half;
  if (name == "Single") return cxx::ir::FloatKind::Single;
  if (name == "Double") return cxx::ir::FloatKind::Double;
  if (name == "X87DoubleExtended") return cxx::ir::FloatKind::X87DoubleExtended;
  if (name == "Quad") return cxx::ir::FloatKind::Quad;
  return cxx::ir::FloatKind{};
}

inline auto toVal(cxx::ir::CastKind value) -> val {
  switch (value) {
    case cxx::ir::CastKind::Truncate:
      return val("Truncate");
    case cxx::ir::CastKind::SignExtend:
      return val("SignExtend");
    case cxx::ir::CastKind::ZeroExtend:
      return val("ZeroExtend");
    case cxx::ir::CastKind::FloatExtend:
      return val("FloatExtend");
    case cxx::ir::CastKind::FloatTruncate:
      return val("FloatTruncate");
    case cxx::ir::CastKind::SignedIntToFloat:
      return val("SignedIntToFloat");
    case cxx::ir::CastKind::UnsignedIntToFloat:
      return val("UnsignedIntToFloat");
    case cxx::ir::CastKind::FloatToSignedInt:
      return val("FloatToSignedInt");
    case cxx::ir::CastKind::FloatToUnsignedInt:
      return val("FloatToUnsignedInt");
    case cxx::ir::CastKind::ReinterpretBits:
      return val("ReinterpretBits");
    case cxx::ir::CastKind::Bitcast:
      return val("Bitcast");
    case cxx::ir::CastKind::Reshape:
      return val("Reshape");
    case cxx::ir::CastKind::ArrayToPointer:
      return val("ArrayToPointer");
    case cxx::ir::CastKind::PointerToInt:
      return val("PointerToInt");
    case cxx::ir::CastKind::IntToPointer:
      return val("IntToPointer");
  }
  return val::undefined();
}

template <>
inline auto toEnum<cxx::ir::CastKind>(const val& value) -> cxx::ir::CastKind {
  const auto name = toString(value);
  if (name == "Truncate") return cxx::ir::CastKind::Truncate;
  if (name == "SignExtend") return cxx::ir::CastKind::SignExtend;
  if (name == "ZeroExtend") return cxx::ir::CastKind::ZeroExtend;
  if (name == "FloatExtend") return cxx::ir::CastKind::FloatExtend;
  if (name == "FloatTruncate") return cxx::ir::CastKind::FloatTruncate;
  if (name == "SignedIntToFloat") return cxx::ir::CastKind::SignedIntToFloat;
  if (name == "UnsignedIntToFloat")
    return cxx::ir::CastKind::UnsignedIntToFloat;
  if (name == "FloatToSignedInt") return cxx::ir::CastKind::FloatToSignedInt;
  if (name == "FloatToUnsignedInt")
    return cxx::ir::CastKind::FloatToUnsignedInt;
  if (name == "ReinterpretBits") return cxx::ir::CastKind::ReinterpretBits;
  if (name == "Bitcast") return cxx::ir::CastKind::Bitcast;
  if (name == "Reshape") return cxx::ir::CastKind::Reshape;
  if (name == "ArrayToPointer") return cxx::ir::CastKind::ArrayToPointer;
  if (name == "PointerToInt") return cxx::ir::CastKind::PointerToInt;
  if (name == "IntToPointer") return cxx::ir::CastKind::IntToPointer;
  return cxx::ir::CastKind{};
}

inline auto toVal(cxx::ir::TypeKind value) -> val {
  switch (value) {
    case cxx::ir::TypeKind::Void:
      return val("Void");
    case cxx::ir::TypeKind::Integer:
      return val("Integer");
    case cxx::ir::TypeKind::Floating:
      return val("Floating");
    case cxx::ir::TypeKind::Pointer:
      return val("Pointer");
    case cxx::ir::TypeKind::Array:
      return val("Array");
    case cxx::ir::TypeKind::Class:
      return val("Class");
    case cxx::ir::TypeKind::Function:
      return val("Function");
    case cxx::ir::TypeKind::Unresolved:
      return val("Unresolved");
    case cxx::ir::TypeKind::Other:
      return val("Other");
  }
  return val::undefined();
}

template <>
inline auto toEnum<cxx::ir::TypeKind>(const val& value) -> cxx::ir::TypeKind {
  const auto name = toString(value);
  if (name == "Void") return cxx::ir::TypeKind::Void;
  if (name == "Integer") return cxx::ir::TypeKind::Integer;
  if (name == "Floating") return cxx::ir::TypeKind::Floating;
  if (name == "Pointer") return cxx::ir::TypeKind::Pointer;
  if (name == "Array") return cxx::ir::TypeKind::Array;
  if (name == "Class") return cxx::ir::TypeKind::Class;
  if (name == "Function") return cxx::ir::TypeKind::Function;
  if (name == "Unresolved") return cxx::ir::TypeKind::Unresolved;
  if (name == "Other") return cxx::ir::TypeKind::Other;
  return cxx::ir::TypeKind{};
}

inline auto toVal(cxx::ir::CallKind value) -> val {
  switch (value) {
    case cxx::ir::CallKind::Direct:
      return val("Direct");
    case cxx::ir::CallKind::Builtin:
      return val("Builtin");
  }
  return val::undefined();
}

template <>
inline auto toEnum<cxx::ir::CallKind>(const val& value) -> cxx::ir::CallKind {
  const auto name = toString(value);
  if (name == "Direct") return cxx::ir::CallKind::Direct;
  if (name == "Builtin") return cxx::ir::CallKind::Builtin;
  return cxx::ir::CallKind{};
}

inline auto toVal(cxx::ir::ParameterAbiKind value) -> val {
  switch (value) {
    case cxx::ir::ParameterAbiKind::Default:
      return val("Default");
    case cxx::ir::ParameterAbiKind::StructReturn:
      return val("StructReturn");
    case cxx::ir::ParameterAbiKind::ByValue:
      return val("ByValue");
  }
  return val::undefined();
}

template <>
inline auto toEnum<cxx::ir::ParameterAbiKind>(const val& value)
    -> cxx::ir::ParameterAbiKind {
  const auto name = toString(value);
  if (name == "Default") return cxx::ir::ParameterAbiKind::Default;
  if (name == "StructReturn") return cxx::ir::ParameterAbiKind::StructReturn;
  if (name == "ByValue") return cxx::ir::ParameterAbiKind::ByValue;
  return cxx::ir::ParameterAbiKind{};
}

inline auto toVal(cxx::ir::Visibility value) -> val {
  switch (value) {
    case cxx::ir::Visibility::Default:
      return val("Default");
    case cxx::ir::Visibility::Hidden:
      return val("Hidden");
    case cxx::ir::Visibility::Protected:
      return val("Protected");
  }
  return val::undefined();
}

template <>
inline auto toEnum<cxx::ir::Visibility>(const val& value)
    -> cxx::ir::Visibility {
  const auto name = toString(value);
  if (name == "Default") return cxx::ir::Visibility::Default;
  if (name == "Hidden") return cxx::ir::Visibility::Hidden;
  if (name == "Protected") return cxx::ir::Visibility::Protected;
  return cxx::ir::Visibility{};
}

inline auto toVal(cxx::ir::InlineKind value) -> val {
  switch (value) {
    case cxx::ir::InlineKind::NoInline:
      return val("NoInline");
    case cxx::ir::InlineKind::InlineHint:
      return val("InlineHint");
  }
  return val::undefined();
}

template <>
inline auto toEnum<cxx::ir::InlineKind>(const val& value)
    -> cxx::ir::InlineKind {
  const auto name = toString(value);
  if (name == "NoInline") return cxx::ir::InlineKind::NoInline;
  if (name == "InlineHint") return cxx::ir::InlineKind::InlineHint;
  return cxx::ir::InlineKind{};
}

auto toVal(const cxx::ir::InsertionPoint& value) -> val;
auto toVal(const cxx::ir::Initializer& value) -> val;
auto toVal(const cxx::ir::VTableInfo& value) -> val;
auto toVal(const cxx::ir::VTableTableInfo& value) -> val;
auto toVal(const cxx::ir::ModuleInfo& value) -> val;
auto toVal(const cxx::ir::CleanupTarget& value) -> val;
auto toVal(const cxx::ir::CleanupAction& value) -> val;
auto toVal(const cxx::ir::Access& value) -> val;
auto toVal(const cxx::ir::BitfieldInfo& value) -> val;
auto toVal(const cxx::ir::CallInfo& value) -> val;
auto toVal(const cxx::ir::ParameterAbi& value) -> val;
auto toVal(const cxx::ir::FunctionInfo& value) -> val;
auto toVal(const cxx::ir::GlobalInfo& value) -> val;

inline auto toVal(const cxx::ir::InsertionPoint& value) -> val {
  auto result = val::object();
  result.set("kind", toVal(value.kind));
  result.set("block", toVal(value.block));
  return result;
}

inline auto toVal(const cxx::ir::Initializer& value) -> val {
  auto result = val::object();
  result.set("kind", toVal(value.kind));
  result.set("type", toVal(value.type));
  result.set("integer", toVal(value.integer));
  result.set("floating", toVal(value.floating));
  result.set("bytes", toVal(value.bytes));
  result.set("elements",
             arrayVal(value.elements, [](const cxx::ir::Initializer& item) {
               return toVal(item);
             }));
  return result;
}

inline auto toVal(const cxx::ir::VTableInfo& value) -> val {
  auto result = val::object();
  result.set("name", toVal(value.name));
  result.set("typeInfo", toVal(value.typeInfo));
  result.set("tables",
             arrayVal(value.tables, [](const cxx::ir::VTableTableInfo& item) {
               return toVal(item);
             }));
  result.set("linkage", toVal(value.linkage));
  return result;
}

inline auto toVal(const cxx::ir::VTableTableInfo& value) -> val {
  auto result = val::object();
  result.set("virtualBaseOffsets",
             arrayVal(value.virtualBaseOffsets,
                      [](const long long& item) { return toVal(item); }));
  result.set("virtualCallOffsets",
             arrayVal(value.virtualCallOffsets,
                      [](const long long& item) { return toVal(item); }));
  result.set("offsetToTop", toVal(value.offsetToTop));
  result.set("slots",
             arrayVal(value.slots, [](const cxx::ir::FunctionRef& item) {
               return toVal(item);
             }));
  return result;
}

inline auto toVal(const cxx::ir::ModuleInfo& value) -> val {
  auto result = val::object();
  result.set("name", toVal(value.name));
  result.set("sourceFile", toVal(value.sourceFile));
  result.set("targetTriple", toVal(value.targetTriple));
  result.set("debugCompilationDirectory",
             toVal(value.debugCompilationDirectory));
  result.set("framePointer", toVal(value.framePointer));
  return result;
}

inline auto toVal(const cxx::ir::CleanupTarget& value) -> val {
  auto result = val::object();
  result.set("block", toVal(value.block));
  result.set("label", toVal(value.label));
  return result;
}

inline auto toVal(const cxx::ir::CleanupAction& value) -> val {
  auto result = val::object();
  result.set("address", toVal(value.address));
  result.set("destructor", toVal(value.destructor));
  result.set("depth", toVal(value.depth));
  result.set("activeFlag", toVal(value.activeFlag));
  return result;
}

inline auto toVal(const cxx::ir::Access& value) -> val {
  auto result = val::object();
  result.set("alignment", toVal(value.alignment));
  result.set("bitfield",
             optionalVal(value.bitfield, [](const cxx::ir::BitfieldInfo& item) {
               return toVal(item);
             }));
  result.set("isSigned", toVal(value.isSigned));
  return result;
}

inline auto toVal(const cxx::ir::BitfieldInfo& value) -> val {
  auto result = val::object();
  result.set("bitOffset", toVal(value.bitOffset));
  result.set("bitWidth", toVal(value.bitWidth));
  result.set("alignment", toVal(value.alignment));
  return result;
}

inline auto toVal(const cxx::ir::CallInfo& value) -> val {
  auto result = val::object();
  result.set("kind", toVal(value.kind));
  result.set("callee", toVal(value.callee));
  result.set("indirectCallee", toVal(value.indirectCallee));
  result.set("arguments",
             arrayVal(value.arguments, [](const cxx::ir::ValueRef& item) {
               return toVal(item);
             }));
  result.set("results",
             arrayVal(value.results, [](const cxx::ir::TypeRef& item) {
               return toVal(item);
             }));
  result.set("parameters",
             arrayVal(value.parameters, [](const cxx::ir::ParameterAbi& item) {
               return toVal(item);
             }));
  result.set("variadicCalleeType", toVal(value.variadicCalleeType));
  return result;
}

inline auto toVal(const cxx::ir::ParameterAbi& value) -> val {
  auto result = val::object();
  result.set("kind", toVal(value.kind));
  result.set("indirectType", toVal(value.indirectType));
  result.set("alignment", toVal(value.alignment));
  return result;
}

inline auto toVal(const cxx::ir::FunctionInfo& value) -> val {
  auto result = val::object();
  result.set("name", toVal(value.name));
  result.set("type", toVal(value.type));
  result.set("linkage", toVal(value.linkage));
  result.set("visibility", toVal(value.visibility));
  result.set("inlineKind", toVal(value.inlineKind));
  result.set("aliasee", toVal(value.aliasee));
  result.set("importModule", toVal(value.importModule));
  result.set("importName", toVal(value.importName));
  result.set("exportName", toVal(value.exportName));
  result.set("isUsed", toVal(value.isUsed));
  result.set("parameters",
             arrayVal(value.parameters, [](const cxx::ir::ParameterAbi& item) {
               return toVal(item);
             }));
  return result;
}

inline auto toVal(const cxx::ir::GlobalInfo& value) -> val {
  auto result = val::object();
  result.set("name", toVal(value.name));
  result.set("type", toVal(value.type));
  result.set("linkage", toVal(value.linkage));
  result.set("isConstant", toVal(value.isConstant));
  result.set("alignment", toVal(value.alignment));
  result.set("initializer", toVal(value.initializer));
  result.set("unknownLocation", toVal(value.unknownLocation));
  result.set("isUsed", toVal(value.isUsed));
  return result;
}

class JsEmitter final : public ir::Emitter {
 public:
  explicit JsEmitter(val delegate) : delegate_(std::move(delegate)) {}

  auto debug() -> cxx::ir::DebugEmitter* override { return nullptr; }

  auto saveInsertionPoint() -> cxx::ir::InsertionPointRef override {
    return toHandle<cxx::ir::InsertionPointTag>(
        delegate_.call<val>("saveInsertionPoint"));
  }

  void restoreInsertionPoint(cxx::ir::InsertionPointRef point) override {
    delegate_.call<val>("restoreInsertionPoint", toVal(point));
  }

  void setInsertionPoint(cxx::ir::InsertionPoint point) override {
    delegate_.call<val>("setInsertionPoint", toVal(point));
  }

  void beginGlobalInitializer(cxx::ir::GlobalRef global) override {
    delegate_.call<val>("beginGlobalInitializer", toVal(global));
  }

  void globalConstructor(cxx::SourceLocation loc,
                         cxx::ir::FunctionRef function) override {
    delegate_.call<val>("globalConstructor", toVal(loc), toVal(function));
  }

  auto constant(cxx::SourceLocation loc, cxx::ir::TypeRef type,
                const cxx::ir::Initializer& value)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(
        delegate_.call<val>("constant", toVal(loc), toVal(type), toVal(value)));
  }

  auto isZeroConstant(cxx::ir::ValueRef value) -> bool override {
    return toBool(delegate_.call<val>("isZeroConstant", toVal(value)));
  }

  auto symbolExists(std::string_view name) -> bool override {
    return toBool(delegate_.call<val>("symbolExists", toVal(name)));
  }

  auto todo(cxx::SourceLocation loc, cxx::ir::TodoKind kind,
            std::string_view message) -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(
        delegate_.call<val>("todo", toVal(loc), toVal(kind), toVal(message)));
  }

  auto unaryOp(cxx::SourceLocation loc, cxx::ir::UnaryOp op,
               cxx::ir::TypeRef type, cxx::ir::ValueRef value)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(delegate_.call<val>(
        "unaryOp", toVal(loc), toVal(op), toVal(type), toVal(value)));
  }

  void defineVTable(cxx::SourceLocation loc,
                    const cxx::ir::VTableInfo& info) override {
    delegate_.call<val>("defineVTable", toVal(loc), toVal(info));
  }

  auto beginModule(const cxx::ir::ModuleInfo& info)
      -> cxx::ir::ModuleRef override {
    return toHandle<cxx::ir::ModuleTag>(
        delegate_.call<val>("beginModule", toVal(info)));
  }

  void endModule() override { delegate_.call<val>("endModule"); }

  void beginFunctionBody(cxx::ir::FunctionRef function) override {
    delegate_.call<val>("beginFunctionBody", toVal(function));
  }

  void endFunctionBody(cxx::ir::FunctionRef function) override {
    delegate_.call<val>("endFunctionBody", toVal(function));
  }

  auto beginCleanupRegion() -> cxx::ir::CleanupRegionRef override {
    return toHandle<cxx::ir::CleanupRegionTag>(
        delegate_.call<val>("beginCleanupRegion"));
  }

  void endCleanupRegion(cxx::ir::CleanupRegionRef region) override {
    delegate_.call<val>("endCleanupRegion", toVal(region));
  }

  auto activateConditionalCleanup(cxx::ir::ValueRef address,
                                  cxx::ir::BlockRef entry,
                                  cxx::ir::CleanupRegionRef region)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(
        delegate_.call<val>("activateConditionalCleanup", toVal(address),
                            toVal(entry), toVal(region)));
  }

  void switchBranch(
      cxx::SourceLocation loc, cxx::ir::ValueRef flag,
      cxx::ir::BlockRef defaultDest, std::span<const long long> caseValues,
      std::span<const cxx::ir::BlockRef> caseDestinations) override {
    delegate_.call<val>(
        "switchBranch", toVal(loc), toVal(flag), toVal(defaultDest),
        arrayVal(caseValues, [](const long long& item) { return toVal(item); }),
        arrayVal(caseDestinations,
                 [](const cxx::ir::BlockRef& item) { return toVal(item); }));
  }

  void defineLabel(cxx::SourceLocation loc, std::string_view name,
                   long long cleanupDepth) override {
    delegate_.call<val>("defineLabel", toVal(loc), toVal(name),
                        toVal(cleanupDepth));
  }

  void branchWithCleanups(
      cxx::SourceLocation loc, cxx::ir::CleanupTarget target,
      std::span<const cxx::ir::CleanupAction> cleanups) override {
    delegate_.call<val>(
        "branchWithCleanups", toVal(loc), toVal(target),
        arrayVal(cleanups, [](const cxx::ir::CleanupAction& item) {
          return toVal(item);
        }));
  }

  void indirectGoto(cxx::SourceLocation loc,
                    cxx::ir::ValueRef target) override {
    delegate_.call<val>("indirectGoto", toVal(loc), toVal(target));
  }

  auto labelAddress(cxx::SourceLocation loc, cxx::ir::TypeRef type,
                    std::string_view name, cxx::ir::FunctionRef function)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(delegate_.call<val>(
        "labelAddress", toVal(loc), toVal(type), toVal(name), toVal(function)));
  }

  void resolveFunctionControlFlow(cxx::ir::FunctionRef function) override {
    delegate_.call<val>("resolveFunctionControlFlow", toVal(function));
  }

  auto functionParameterTypes(cxx::ir::FunctionRef function)
      -> std::vector<cxx::ir::TypeRef> override {
    return toHandleVector<cxx::ir::TypeTag>(
        delegate_.call<val>("functionParameterTypes", toVal(function)));
  }

  auto functionResultTypes(cxx::ir::FunctionRef function)
      -> std::vector<cxx::ir::TypeRef> override {
    return toHandleVector<cxx::ir::TypeTag>(
        delegate_.call<val>("functionResultTypes", toVal(function)));
  }

  auto addBlockParameter(cxx::ir::BlockRef block, cxx::ir::TypeRef type,
                         cxx::SourceLocation loc)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(delegate_.call<val>(
        "addBlockParameter", toVal(block), toVal(type), toVal(loc)));
  }

  auto blockParameter(cxx::ir::BlockRef block, unsigned int index)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(
        delegate_.call<val>("blockParameter", toVal(block), toVal(index)));
  }

  auto blockParameterCount(cxx::ir::BlockRef block) -> unsigned int override {
    return toNumber<unsigned int>(
        delegate_.call<val>("blockParameterCount", toVal(block)));
  }

  auto createBlock(cxx::ir::FunctionRef function)
      -> cxx::ir::BlockRef override {
    return toHandle<cxx::ir::BlockTag>(
        delegate_.call<val>("createBlock", toVal(function)));
  }

  auto insertionBlock() -> cxx::ir::BlockRef override {
    return toHandle<cxx::ir::BlockTag>(delegate_.call<val>("insertionBlock"));
  }

  void eraseBlock(cxx::ir::BlockRef block) override {
    delegate_.call<val>("eraseBlock", toVal(block));
  }

  auto hasTerminator(cxx::ir::BlockRef block) -> bool override {
    return toBool(delegate_.call<val>("hasTerminator", toVal(block)));
  }

  void branch(cxx::SourceLocation loc, cxx::ir::BlockRef target,
              std::span<const cxx::ir::ValueRef> operands) override {
    delegate_.call<val>("branch", toVal(loc), toVal(target),
                        arrayVal(operands, [](const cxx::ir::ValueRef& item) {
                          return toVal(item);
                        }));
  }

  auto globalLinkage(cxx::ir::GlobalRef global) -> cxx::ir::Linkage override {
    return toEnum<cxx::ir::Linkage>(
        delegate_.call<val>("globalLinkage", toVal(global)));
  }

  void condBranch(cxx::SourceLocation loc, cxx::ir::ValueRef condition,
                  cxx::ir::BlockRef trueDest,
                  cxx::ir::BlockRef falseDest) override {
    delegate_.call<val>("condBranch", toVal(loc), toVal(condition),
                        toVal(trueDest), toVal(falseDest));
  }

  auto binaryOp(cxx::SourceLocation loc, cxx::ir::BinaryOp op,
                cxx::ir::ValueRef lhs, cxx::ir::ValueRef rhs)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(delegate_.call<val>(
        "binaryOp", toVal(loc), toVal(op), toVal(lhs), toVal(rhs)));
  }

  auto compareInt(cxx::SourceLocation loc, cxx::ir::IntPredicate predicate,
                  cxx::ir::ValueRef lhs, cxx::ir::ValueRef rhs)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(delegate_.call<val>(
        "compareInt", toVal(loc), toVal(predicate), toVal(lhs), toVal(rhs)));
  }

  auto compareFloat(cxx::SourceLocation loc, cxx::ir::FloatPredicate predicate,
                    cxx::ir::ValueRef lhs, cxx::ir::ValueRef rhs)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(delegate_.call<val>(
        "compareFloat", toVal(loc), toVal(predicate), toVal(lhs), toVal(rhs)));
  }

  auto select(cxx::SourceLocation loc, cxx::ir::ValueRef condition,
              cxx::ir::ValueRef ifTrue, cxx::ir::ValueRef ifFalse)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(delegate_.call<val>(
        "select", toVal(loc), toVal(condition), toVal(ifTrue), toVal(ifFalse)));
  }

  auto voidType() -> cxx::ir::TypeRef override {
    return toHandle<cxx::ir::TypeTag>(delegate_.call<val>("voidType"));
  }

  auto unresolvedType() -> cxx::ir::TypeRef override {
    return toHandle<cxx::ir::TypeTag>(delegate_.call<val>("unresolvedType"));
  }

  auto integerType(unsigned int bits) -> cxx::ir::TypeRef override {
    return toHandle<cxx::ir::TypeTag>(
        delegate_.call<val>("integerType", toVal(bits)));
  }

  auto floatingType(cxx::ir::FloatKind kind) -> cxx::ir::TypeRef override {
    return toHandle<cxx::ir::TypeTag>(
        delegate_.call<val>("floatingType", toVal(kind)));
  }

  auto pointerType(cxx::ir::TypeRef elementType) -> cxx::ir::TypeRef override {
    return toHandle<cxx::ir::TypeTag>(
        delegate_.call<val>("pointerType", toVal(elementType)));
  }

  auto arrayType(cxx::ir::TypeRef elementType, unsigned long long size)
      -> cxx::ir::TypeRef override {
    return toHandle<cxx::ir::TypeTag>(
        delegate_.call<val>("arrayType", toVal(elementType), toVal(size)));
  }

  auto vectorType(cxx::ir::TypeRef elementType, unsigned long long elementCount)
      -> cxx::ir::TypeRef override {
    return toHandle<cxx::ir::TypeTag>(delegate_.call<val>(
        "vectorType", toVal(elementType), toVal(elementCount)));
  }

  auto vectorSplat(cxx::SourceLocation loc, cxx::ir::TypeRef vectorType,
                   cxx::ir::ValueRef scalar) -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(delegate_.call<val>(
        "vectorSplat", toVal(loc), toVal(vectorType), toVal(scalar)));
  }

  auto functionType(std::span<const cxx::ir::TypeRef> parameters,
                    std::span<const cxx::ir::TypeRef> results, bool isVariadic)
      -> cxx::ir::TypeRef override {
    return toHandle<cxx::ir::TypeTag>(delegate_.call<val>(
        "functionType",
        arrayVal(parameters,
                 [](const cxx::ir::TypeRef& item) { return toVal(item); }),
        arrayVal(results,
                 [](const cxx::ir::TypeRef& item) { return toVal(item); }),
        toVal(isVariadic)));
  }

  auto declareClassType(std::string_view name) -> cxx::ir::TypeRef override {
    return toHandle<cxx::ir::TypeTag>(
        delegate_.call<val>("declareClassType", toVal(name)));
  }

  void defineClassType(cxx::ir::TypeRef classType,
                       std::span<const cxx::ir::TypeRef> members,
                       bool isPacked) override {
    delegate_.call<val>(
        "defineClassType", toVal(classType),
        arrayVal(members,
                 [](const cxx::ir::TypeRef& item) { return toVal(item); }),
        toVal(isPacked));
  }

  auto convert(cxx::SourceLocation loc, cxx::ir::CastKind kind,
               cxx::ir::ValueRef value, cxx::ir::TypeRef type)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(delegate_.call<val>(
        "convert", toVal(loc), toVal(kind), toVal(value), toVal(type)));
  }

  auto typeKind(cxx::ir::TypeRef type) -> cxx::ir::TypeKind override {
    return toEnum<cxx::ir::TypeKind>(
        delegate_.call<val>("typeKind", toVal(type)));
  }

  auto scalarWidth(cxx::ir::TypeRef type) -> unsigned int override {
    return toNumber<unsigned int>(
        delegate_.call<val>("scalarWidth", toVal(type)));
  }

  auto elementType(cxx::ir::TypeRef type) -> cxx::ir::TypeRef override {
    return toHandle<cxx::ir::TypeTag>(
        delegate_.call<val>("elementType", toVal(type)));
  }

  auto typeOf(cxx::ir::ValueRef value) -> cxx::ir::TypeRef override {
    return toHandle<cxx::ir::TypeTag>(
        delegate_.call<val>("typeOf", toVal(value)));
  }

  auto allocate(cxx::SourceLocation loc, cxx::ir::TypeRef pointerType,
                cxx::ir::ValueRef size, unsigned long long alignment)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(
        delegate_.call<val>("allocate", toVal(loc), toVal(pointerType),
                            toVal(size), toVal(alignment)));
  }

  auto load(cxx::SourceLocation loc, cxx::ir::TypeRef valueType,
            cxx::ir::ValueRef address, const cxx::ir::Access& access)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(delegate_.call<val>(
        "load", toVal(loc), toVal(valueType), toVal(address), toVal(access)));
  }

  auto pointerAdd(cxx::SourceLocation loc, cxx::ir::TypeRef pointerType,
                  cxx::ir::ValueRef base, cxx::ir::ValueRef offset)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(
        delegate_.call<val>("pointerAdd", toVal(loc), toVal(pointerType),
                            toVal(base), toVal(offset)));
  }

  auto pointerDiff(cxx::SourceLocation loc, cxx::ir::TypeRef resultType,
                   cxx::ir::ValueRef lhs, cxx::ir::ValueRef rhs)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(delegate_.call<val>(
        "pointerDiff", toVal(loc), toVal(resultType), toVal(lhs), toVal(rhs)));
  }

  auto subscript(cxx::SourceLocation loc, cxx::ir::TypeRef pointerType,
                 cxx::ir::ValueRef base, cxx::ir::ValueRef index)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(
        delegate_.call<val>("subscript", toVal(loc), toVal(pointerType),
                            toVal(base), toVal(index)));
  }

  auto memberAddress(cxx::SourceLocation loc, cxx::ir::TypeRef pointerType,
                     cxx::ir::ValueRef base, unsigned int index)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(
        delegate_.call<val>("memberAddress", toVal(loc), toVal(pointerType),
                            toVal(base), toVal(index)));
  }

  auto extractValue(cxx::SourceLocation loc, cxx::ir::TypeRef resultType,
                    cxx::ir::ValueRef container, long long position)
      -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(
        delegate_.call<val>("extractValue", toVal(loc), toVal(resultType),
                            toVal(container), toVal(position)));
  }

  auto insertValue(cxx::SourceLocation loc, cxx::ir::TypeRef resultType,
                   cxx::ir::ValueRef container, cxx::ir::ValueRef value,
                   long long position) -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(
        delegate_.call<val>("insertValue", toVal(loc), toVal(resultType),
                            toVal(container), toVal(value), toVal(position)));
  }

  auto addressOfSymbol(cxx::SourceLocation loc, cxx::ir::TypeRef resultType,
                       std::string_view symbol) -> cxx::ir::ValueRef override {
    return toHandle<cxx::ir::ValueTag>(delegate_.call<val>(
        "addressOfSymbol", toVal(loc), toVal(resultType), toVal(symbol)));
  }

  void store(cxx::SourceLocation loc, cxx::ir::ValueRef value,
             cxx::ir::ValueRef address,
             const cxx::ir::Access& access) override {
    delegate_.call<val>("store", toVal(loc), toVal(value), toVal(address),
                        toVal(access));
  }

  void memsetZero(cxx::SourceLocation loc, cxx::ir::ValueRef address,
                  unsigned long long size) override {
    delegate_.call<val>("memsetZero", toVal(loc), toVal(address), toVal(size));
  }

  void memcpy(cxx::SourceLocation loc, cxx::ir::ValueRef destination,
              cxx::ir::ValueRef source, unsigned long long size) override {
    delegate_.call<val>("memcpy", toVal(loc), toVal(destination), toVal(source),
                        toVal(size));
  }

  void unreachable(cxx::SourceLocation loc) override {
    delegate_.call<val>("unreachable", toVal(loc));
  }

  auto call(cxx::SourceLocation loc, const cxx::ir::CallInfo& info)
      -> std::vector<cxx::ir::ValueRef> override {
    return toHandleVector<cxx::ir::ValueTag>(
        delegate_.call<val>("call", toVal(loc), toVal(info)));
  }

  void ret(cxx::SourceLocation loc,
           std::span<const cxx::ir::ValueRef> values) override {
    delegate_.call<val>("ret", toVal(loc),
                        arrayVal(values, [](const cxx::ir::ValueRef& item) {
                          return toVal(item);
                        }));
  }

  auto findFunction(std::string_view name) -> cxx::ir::FunctionRef override {
    return toHandle<cxx::ir::FunctionTag>(
        delegate_.call<val>("findFunction", toVal(name)));
  }

  auto declareFunction(cxx::SourceLocation loc,
                       const cxx::ir::FunctionInfo& info)
      -> cxx::ir::FunctionRef override {
    return toHandle<cxx::ir::FunctionTag>(
        delegate_.call<val>("declareFunction", toVal(loc), toVal(info)));
  }

  auto functionHasBody(cxx::ir::FunctionRef function) -> bool override {
    return toBool(delegate_.call<val>("functionHasBody", toVal(function)));
  }

  void setFunctionAliasee(cxx::ir::FunctionRef function,
                          std::string_view aliasee) override {
    delegate_.call<val>("setFunctionAliasee", toVal(function), toVal(aliasee));
  }

  auto findGlobal(std::string_view name) -> cxx::ir::GlobalRef override {
    return toHandle<cxx::ir::GlobalTag>(
        delegate_.call<val>("findGlobal", toVal(name)));
  }

  auto declareGlobal(cxx::SourceLocation loc, const cxx::ir::GlobalInfo& info)
      -> cxx::ir::GlobalRef override {
    return toHandle<cxx::ir::GlobalTag>(
        delegate_.call<val>("declareGlobal", toVal(loc), toVal(info)));
  }

 private:
  val delegate_;
};

}  // namespace cxx::js
