FROM ghcr.io/webassembly/wasi-sdk:wasi-sdk-27

RUN apt-get update && apt-get install -y \
    g++ \
    git \
    binaryen \
    wget \
    unzip \
    ninja-build

RUN wget https://github.com/google/flatbuffers/releases/download/v25.1.24/Linux.flatc.binary.clang++-18.zip && \
    unzip Linux.flatc.binary.clang++-18.zip && \
    mv flatc /usr/bin/flatc && \
    rm Linux.flatc.binary.clang++-18.zip
