FROM emscripten/emsdk:4.0.21 as em

RUN apt-get update && apt-get install -y \
    ninja-build \
    wget \
    unzip

RUN wget https://github.com/google/flatbuffers/releases/download/v25.1.24/Linux.flatc.binary.clang++-18.zip && \
    unzip Linux.flatc.binary.clang++-18.zip && \
    mv flatc /usr/bin/flatc && \
    rm Linux.flatc.binary.clang++-18.zip
