FROM emscripten/emsdk:3.1.71 as em

RUN apt-get update && apt-get install -y \
    ninja-build \
    wget \
    unzip

COPY tools/kwgen/kwgen.cc /tmp/kwgen.cc

RUN g++ -std=c++20 /tmp/kwgen.cc -o /usr/bin/kwgen

RUN wget https://github.com/google/flatbuffers/releases/download/v24.3.25/Linux.flatc.binary.clang++-15.zip && \
    unzip Linux.flatc.binary.clang++-15.zip && \
    mv flatc /usr/bin/flatc && \
    rm Linux.flatc.binary.clang++-15.zip
