[project]
name = "cplusplus"
version = "1.1.27"
description = "A compiler frontend for C++23"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "filecheck>=1.0.2",
    "lit>=18.1.8",
]
