// Generated by gen_builtins_interp_h.ts
// Copyright (c) 2026 Roberto Raggi <roberto.raggi@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#include <cmath>
#include <cstdlib>
#include <cstring>

auto cxx::ASTInterpreter::evaluateBuiltinCall(cxx::BuiltinFunctionKind kind,
                                              std::vector<ConstValue> args)
    -> std::optional<ConstValue> {
  switch (kind) {
    case BuiltinFunctionKind::T___BUILTIN_IS_CONSTANT_EVALUATED:
      return ConstValue{std::intmax_t(1)};

    case BuiltinFunctionKind::T___BUILTIN_EXPECT:
      if (args.size() >= 1) return args[0];
      return std::nullopt;

    case BuiltinFunctionKind::T___BUILTIN_BSWAP32: {
      if (auto a = toInt(args[0])) {
        auto v = static_cast<uint32_t>(*a);
        v = ((v & 0xFF000000u) >> 24) | ((v & 0x00FF0000u) >> 8) |
            ((v & 0x0000FF00u) << 8) | ((v & 0x000000FFu) << 24);
        return ConstValue{static_cast<std::intmax_t>(v)};
      }
      return std::nullopt;
    }

    case BuiltinFunctionKind::T___BUILTIN_BSWAP64: {
      if (auto a = toInt(args[0])) {
        auto v = static_cast<uint64_t>(*a);
        v = ((v & 0xFF00000000000000ull) >> 56) |
            ((v & 0x00FF000000000000ull) >> 40) |
            ((v & 0x0000FF0000000000ull) >> 24) |
            ((v & 0x000000FF00000000ull) >> 8) |
            ((v & 0x00000000FF000000ull) << 8) |
            ((v & 0x0000000000FF0000ull) << 24) |
            ((v & 0x000000000000FF00ull) << 40) |
            ((v & 0x00000000000000FFull) << 56);
        return ConstValue{static_cast<std::intmax_t>(v)};
      }
      return std::nullopt;
    }

    case BuiltinFunctionKind::T___BUILTIN_STRLEN: {
      if (auto* lit = std::get_if<const StringLiteral*>(&args[0])) {
        if (*lit) {
          return ConstValue{
              static_cast<std::intmax_t>((*lit)->stringValue().size())};
        }
      }
      return std::nullopt;
    }

    case BuiltinFunctionKind::T___BUILTIN_STRCMP: {
      auto* a = std::get_if<const StringLiteral*>(&args[0]);
      auto* b = std::get_if<const StringLiteral*>(&args[1]);
      if (a && b && *a && *b) {
        auto sa = (*a)->stringValue();
        auto sb = (*b)->stringValue();
        int r = sa.compare(sb);
        return ConstValue{static_cast<std::intmax_t>(r > 0   ? 1
                                                     : r < 0 ? -1
                                                             : 0)};
      }
      return std::nullopt;
    }

    case BuiltinFunctionKind::T___BUILTIN_STRNCMP: {
      auto* a = std::get_if<const StringLiteral*>(&args[0]);
      auto* b = std::get_if<const StringLiteral*>(&args[1]);
      auto n = toInt(args[2]);
      if (a && b && *a && *b && n) {
        auto sa = (*a)->stringValue();
        auto sb = (*b)->stringValue();
        int r = sa.compare(0, static_cast<size_t>(*n), sb, 0,
                           static_cast<size_t>(*n));
        return ConstValue{static_cast<std::intmax_t>(r > 0   ? 1
                                                     : r < 0 ? -1
                                                             : 0)};
      }
      return std::nullopt;
    }

    case BuiltinFunctionKind::T___BUILTIN_MEMCMP: {
      auto* a = std::get_if<const StringLiteral*>(&args[0]);
      auto* b = std::get_if<const StringLiteral*>(&args[1]);
      auto n = toInt(args[2]);
      if (a && b && *a && *b && n) {
        auto sa = (*a)->stringValue();
        auto sb = (*b)->stringValue();
        auto len = static_cast<size_t>(*n);
        if (sa.size() >= len && sb.size() >= len) {
          int r = std::memcmp(sa.data(), sb.data(), len);
          return ConstValue{static_cast<std::intmax_t>(r > 0   ? 1
                                                       : r < 0 ? -1
                                                               : 0)};
        }
      }
      return std::nullopt;
    }

    case BuiltinFunctionKind::T___BUILTIN_BCMP: {
      auto* a = std::get_if<const StringLiteral*>(&args[0]);
      auto* b = std::get_if<const StringLiteral*>(&args[1]);
      auto n = toInt(args[2]);
      if (a && b && *a && *b && n) {
        auto sa = (*a)->stringValue();
        auto sb = (*b)->stringValue();
        auto len = static_cast<size_t>(*n);
        if (sa.size() >= len && sb.size() >= len) {
          int r = std::memcmp(sa.data(), sb.data(), len);
          return ConstValue{static_cast<std::intmax_t>(r != 0 ? 1 : 0)};
        }
      }
      return std::nullopt;
    }

#ifndef _MSC_VER
    case BuiltinFunctionKind::T___BUILTIN_STRCASECMP: {
      auto* a = std::get_if<const StringLiteral*>(&args[0]);
      auto* b = std::get_if<const StringLiteral*>(&args[1]);
      if (a && b && *a && *b) {
        int r = strcasecmp(std::string((*a)->stringValue()).c_str(),
                           std::string((*b)->stringValue()).c_str());
        return ConstValue{static_cast<std::intmax_t>(r > 0   ? 1
                                                     : r < 0 ? -1
                                                             : 0)};
      }
      return std::nullopt;
    }
#endif

#ifndef _MSC_VER
    case BuiltinFunctionKind::T___BUILTIN_STRNCASECMP: {
      auto* a = std::get_if<const StringLiteral*>(&args[0]);
      auto* b = std::get_if<const StringLiteral*>(&args[1]);
      auto n = toInt(args[2]);
      if (a && b && *a && *b && n) {
        int r = strncasecmp(std::string((*a)->stringValue()).c_str(),
                            std::string((*b)->stringValue()).c_str(),
                            static_cast<size_t>(*n));
        return ConstValue{static_cast<std::intmax_t>(r > 0   ? 1
                                                     : r < 0 ? -1
                                                             : 0)};
      }
      return std::nullopt;
    }
#endif

    case BuiltinFunctionKind::T___BUILTIN_STRSPN: {
      auto* a = std::get_if<const StringLiteral*>(&args[0]);
      auto* b = std::get_if<const StringLiteral*>(&args[1]);
      if (a && b && *a && *b) {
        auto sa = std::string((*a)->stringValue());
        auto sb = std::string((*b)->stringValue());
        return ConstValue{
            static_cast<std::intmax_t>(strspn(sa.c_str(), sb.c_str()))};
      }
      return std::nullopt;
    }

    case BuiltinFunctionKind::T___BUILTIN_STRCSPN: {
      auto* a = std::get_if<const StringLiteral*>(&args[0]);
      auto* b = std::get_if<const StringLiteral*>(&args[1]);
      if (a && b && *a && *b) {
        auto sa = std::string((*a)->stringValue());
        auto sb = std::string((*b)->stringValue());
        return ConstValue{
            static_cast<std::intmax_t>(strcspn(sa.c_str(), sb.c_str()))};
      }
      return std::nullopt;
    }

    case BuiltinFunctionKind::T___BUILTIN_ABS: {
      if (auto a = toInt(args[0]))
        return ConstValue{
            static_cast<std::intmax_t>(std::abs(static_cast<int>(*a)))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LABS: {
      if (auto a = toInt(args[0]))
        return ConstValue{
            static_cast<std::intmax_t>(std::abs(static_cast<long>(*a)))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LLABS: {
      if (auto a = toInt(args[0]))
        return ConstValue{
            static_cast<std::intmax_t>(std::abs(static_cast<long long>(*a)))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ACOSF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::acos(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ACOS: {
      if (auto a = toDouble(args[0])) return ConstValue{std::acos(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ACOSL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::acos(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ACOSHF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::acosh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ACOSH: {
      if (auto a = toDouble(args[0])) return ConstValue{std::acosh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ACOSHL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::acosh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ASINF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::asin(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ASIN: {
      if (auto a = toDouble(args[0])) return ConstValue{std::asin(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ASINL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::asin(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ASINHF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::asinh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ASINH: {
      if (auto a = toDouble(args[0])) return ConstValue{std::asinh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ASINHL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::asinh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ATANF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::atan(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ATAN: {
      if (auto a = toDouble(args[0])) return ConstValue{std::atan(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ATANL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::atan(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ATAN2F: {
      auto a = toFloat(args[0]);
      auto b = toFloat(args[1]);
      if (a && b) return ConstValue{std::atan2(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ATAN2: {
      auto a = toDouble(args[0]);
      auto b = toDouble(args[1]);
      if (a && b) return ConstValue{std::atan2(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ATAN2L: {
      auto a = toLongDouble(args[0]);
      auto b = toLongDouble(args[1]);
      if (a && b) return ConstValue{std::atan2(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ATANHF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::atanh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ATANH: {
      if (auto a = toDouble(args[0])) return ConstValue{std::atanh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ATANHL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::atanh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_CBRTF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::cbrt(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_CBRT: {
      if (auto a = toDouble(args[0])) return ConstValue{std::cbrt(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_CBRTL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::cbrt(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_CEILF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::ceil(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_CEIL: {
      if (auto a = toDouble(args[0])) return ConstValue{std::ceil(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_CEILL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::ceil(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_COPYSIGNF: {
      auto a = toFloat(args[0]);
      auto b = toFloat(args[1]);
      if (a && b) return ConstValue{std::copysign(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_COPYSIGN: {
      auto a = toDouble(args[0]);
      auto b = toDouble(args[1]);
      if (a && b) return ConstValue{std::copysign(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_COPYSIGNL: {
      auto a = toLongDouble(args[0]);
      auto b = toLongDouble(args[1]);
      if (a && b) return ConstValue{std::copysign(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_COSF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::cos(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_COS: {
      if (auto a = toDouble(args[0])) return ConstValue{std::cos(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_COSL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::cos(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_COSHF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::cosh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_COSH: {
      if (auto a = toDouble(args[0])) return ConstValue{std::cosh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_COSHL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::cosh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ERFF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::erf(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ERF: {
      if (auto a = toDouble(args[0])) return ConstValue{std::erf(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ERFL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::erf(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ERFCF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::erfc(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ERFC: {
      if (auto a = toDouble(args[0])) return ConstValue{std::erfc(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ERFCL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::erfc(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_EXPF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::exp(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_EXP: {
      if (auto a = toDouble(args[0])) return ConstValue{std::exp(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_EXPL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::exp(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_EXP2F: {
      if (auto a = toFloat(args[0])) return ConstValue{std::exp2(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_EXP2: {
      if (auto a = toDouble(args[0])) return ConstValue{std::exp2(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_EXP2L: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::exp2(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_EXPM1F: {
      if (auto a = toFloat(args[0])) return ConstValue{std::expm1(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_EXPM1: {
      if (auto a = toDouble(args[0])) return ConstValue{std::expm1(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_EXPM1L: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::expm1(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FABSF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::fabs(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FABS: {
      if (auto a = toDouble(args[0])) return ConstValue{std::fabs(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FABSL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::fabs(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FDIMF: {
      auto a = toFloat(args[0]);
      auto b = toFloat(args[1]);
      if (a && b) return ConstValue{std::fdim(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FDIM: {
      auto a = toDouble(args[0]);
      auto b = toDouble(args[1]);
      if (a && b) return ConstValue{std::fdim(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FDIML: {
      auto a = toLongDouble(args[0]);
      auto b = toLongDouble(args[1]);
      if (a && b) return ConstValue{std::fdim(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FINITEF: {
      if (auto a = toFloat(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::isfinite(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FINITE: {
      if (auto a = toDouble(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::isfinite(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FINITEL: {
      if (auto a = toLongDouble(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::isfinite(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FLOORF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::floor(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FLOOR: {
      if (auto a = toDouble(args[0])) return ConstValue{std::floor(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FLOORL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::floor(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FMAF: {
      auto a = toFloat(args[0]);
      auto b = toFloat(args[1]);
      auto c = toFloat(args[2]);
      if (a && b && c) return ConstValue{std::fma(*a, *b, *c)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FMA: {
      auto a = toDouble(args[0]);
      auto b = toDouble(args[1]);
      auto c = toDouble(args[2]);
      if (a && b && c) return ConstValue{std::fma(*a, *b, *c)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FMAL: {
      auto a = toLongDouble(args[0]);
      auto b = toLongDouble(args[1]);
      auto c = toLongDouble(args[2]);
      if (a && b && c) return ConstValue{std::fma(*a, *b, *c)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FMAXF: {
      auto a = toFloat(args[0]);
      auto b = toFloat(args[1]);
      if (a && b) return ConstValue{std::fmax(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FMAX: {
      auto a = toDouble(args[0]);
      auto b = toDouble(args[1]);
      if (a && b) return ConstValue{std::fmax(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FMAXL: {
      auto a = toLongDouble(args[0]);
      auto b = toLongDouble(args[1]);
      if (a && b) return ConstValue{std::fmax(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FMINF: {
      auto a = toFloat(args[0]);
      auto b = toFloat(args[1]);
      if (a && b) return ConstValue{std::fmin(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FMIN: {
      auto a = toDouble(args[0]);
      auto b = toDouble(args[1]);
      if (a && b) return ConstValue{std::fmin(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FMINL: {
      auto a = toLongDouble(args[0]);
      auto b = toLongDouble(args[1]);
      if (a && b) return ConstValue{std::fmin(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FMODF: {
      auto a = toFloat(args[0]);
      auto b = toFloat(args[1]);
      if (a && b) return ConstValue{std::fmod(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FMOD: {
      auto a = toDouble(args[0]);
      auto b = toDouble(args[1]);
      if (a && b) return ConstValue{std::fmod(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_FMODL: {
      auto a = toLongDouble(args[0]);
      auto b = toLongDouble(args[1]);
      if (a && b) return ConstValue{std::fmod(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_HYPOTF: {
      auto a = toFloat(args[0]);
      auto b = toFloat(args[1]);
      if (a && b) return ConstValue{std::hypot(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_HYPOT: {
      auto a = toDouble(args[0]);
      auto b = toDouble(args[1]);
      if (a && b) return ConstValue{std::hypot(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_HYPOTL: {
      auto a = toLongDouble(args[0]);
      auto b = toLongDouble(args[1]);
      if (a && b) return ConstValue{std::hypot(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ILOGBF: {
      if (auto a = toFloat(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::ilogb(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ILOGB: {
      if (auto a = toDouble(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::ilogb(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ILOGBL: {
      if (auto a = toLongDouble(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::ilogb(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LDEXPF: {
      auto a = toFloat(args[0]);
      auto b = toInt(args[1]);
      if (a && b) return ConstValue{std::ldexp(*a, static_cast<int>(*b))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LDEXP: {
      auto a = toDouble(args[0]);
      auto b = toInt(args[1]);
      if (a && b) return ConstValue{std::ldexp(*a, static_cast<int>(*b))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LDEXPL: {
      auto a = toLongDouble(args[0]);
      auto b = toInt(args[1]);
      if (a && b) return ConstValue{std::ldexp(*a, static_cast<int>(*b))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LGAMMAF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::lgamma(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LGAMMA: {
      if (auto a = toDouble(args[0])) return ConstValue{std::lgamma(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LGAMMAL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::lgamma(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LLRINTF: {
      if (auto a = toFloat(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::llrint(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LLRINT: {
      if (auto a = toDouble(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::llrint(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LLRINTL: {
      if (auto a = toLongDouble(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::llrint(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LLROUNDF: {
      if (auto a = toFloat(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::llround(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LLROUND: {
      if (auto a = toDouble(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::llround(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LLROUNDL: {
      if (auto a = toLongDouble(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::llround(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LOGF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::log(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LOG: {
      if (auto a = toDouble(args[0])) return ConstValue{std::log(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LOGL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::log(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LOG1PF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::log1p(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LOG1P: {
      if (auto a = toDouble(args[0])) return ConstValue{std::log1p(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LOG1PL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::log1p(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LOG2F: {
      if (auto a = toFloat(args[0])) return ConstValue{std::log2(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LOG2: {
      if (auto a = toDouble(args[0])) return ConstValue{std::log2(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LOG2L: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::log2(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LOG10F: {
      if (auto a = toFloat(args[0])) return ConstValue{std::log10(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LOG10: {
      if (auto a = toDouble(args[0])) return ConstValue{std::log10(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LOG10L: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::log10(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LOGBF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::logb(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LOGB: {
      if (auto a = toDouble(args[0])) return ConstValue{std::logb(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LOGBL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::logb(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LRINTF: {
      if (auto a = toFloat(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::lrint(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LRINT: {
      if (auto a = toDouble(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::lrint(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LRINTL: {
      if (auto a = toLongDouble(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::lrint(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LROUNDF: {
      if (auto a = toFloat(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::lround(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LROUND: {
      if (auto a = toDouble(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::lround(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_LROUNDL: {
      if (auto a = toLongDouble(args[0]))
        return ConstValue{static_cast<std::intmax_t>(std::lround(*a))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_NEARBYINTF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::nearbyint(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_NEARBYINT: {
      if (auto a = toDouble(args[0])) return ConstValue{std::nearbyint(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_NEARBYINTL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::nearbyint(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_NEXTAFTERF: {
      auto a = toFloat(args[0]);
      auto b = toFloat(args[1]);
      if (a && b) return ConstValue{std::nextafter(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_NEXTAFTER: {
      auto a = toDouble(args[0]);
      auto b = toDouble(args[1]);
      if (a && b) return ConstValue{std::nextafter(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_NEXTAFTERL: {
      auto a = toLongDouble(args[0]);
      auto b = toLongDouble(args[1]);
      if (a && b) return ConstValue{std::nextafter(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_NEXTTOWARDF: {
      auto a = toFloat(args[0]);
      auto b = toLongDouble(args[1]);
      if (a && b) return ConstValue{std::nexttoward(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_NEXTTOWARD: {
      auto a = toDouble(args[0]);
      auto b = toLongDouble(args[1]);
      if (a && b) return ConstValue{std::nexttoward(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_NEXTTOWARDL: {
      auto a = toLongDouble(args[0]);
      auto b = toLongDouble(args[1]);
      if (a && b) return ConstValue{std::nexttoward(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_POWF: {
      auto a = toFloat(args[0]);
      auto b = toFloat(args[1]);
      if (a && b) return ConstValue{std::pow(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_POW: {
      auto a = toDouble(args[0]);
      auto b = toDouble(args[1]);
      if (a && b) return ConstValue{std::pow(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_POWL: {
      auto a = toLongDouble(args[0]);
      auto b = toLongDouble(args[1]);
      if (a && b) return ConstValue{std::pow(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_REMAINDERF: {
      auto a = toFloat(args[0]);
      auto b = toFloat(args[1]);
      if (a && b) return ConstValue{std::remainder(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_REMAINDER: {
      auto a = toDouble(args[0]);
      auto b = toDouble(args[1]);
      if (a && b) return ConstValue{std::remainder(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_REMAINDERL: {
      auto a = toLongDouble(args[0]);
      auto b = toLongDouble(args[1]);
      if (a && b) return ConstValue{std::remainder(*a, *b)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_RINTF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::rint(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_RINT: {
      if (auto a = toDouble(args[0])) return ConstValue{std::rint(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_RINTL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::rint(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ROUNDF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::round(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ROUND: {
      if (auto a = toDouble(args[0])) return ConstValue{std::round(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_ROUNDL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::round(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_SCALBLNF: {
      auto a = toFloat(args[0]);
      auto b = toInt(args[1]);
      if (a && b) return ConstValue{std::scalbln(*a, static_cast<long>(*b))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_SCALBLN: {
      auto a = toDouble(args[0]);
      auto b = toInt(args[1]);
      if (a && b) return ConstValue{std::scalbln(*a, static_cast<long>(*b))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_SCALBLNL: {
      auto a = toLongDouble(args[0]);
      auto b = toInt(args[1]);
      if (a && b) return ConstValue{std::scalbln(*a, static_cast<long>(*b))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_SCALBNF: {
      auto a = toFloat(args[0]);
      auto b = toInt(args[1]);
      if (a && b) return ConstValue{std::scalbn(*a, static_cast<int>(*b))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_SCALBN: {
      auto a = toDouble(args[0]);
      auto b = toInt(args[1]);
      if (a && b) return ConstValue{std::scalbn(*a, static_cast<int>(*b))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_SCALBNL: {
      auto a = toLongDouble(args[0]);
      auto b = toInt(args[1]);
      if (a && b) return ConstValue{std::scalbn(*a, static_cast<int>(*b))};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_SINF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::sin(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_SIN: {
      if (auto a = toDouble(args[0])) return ConstValue{std::sin(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_SINL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::sin(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_SINHF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::sinh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_SINH: {
      if (auto a = toDouble(args[0])) return ConstValue{std::sinh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_SINHL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::sinh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_SQRTF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::sqrt(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_SQRT: {
      if (auto a = toDouble(args[0])) return ConstValue{std::sqrt(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_SQRTL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::sqrt(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_TANF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::tan(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_TAN: {
      if (auto a = toDouble(args[0])) return ConstValue{std::tan(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_TANL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::tan(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_TANHF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::tanh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_TANH: {
      if (auto a = toDouble(args[0])) return ConstValue{std::tanh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_TANHL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::tanh(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_TGAMMAF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::tgamma(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_TGAMMA: {
      if (auto a = toDouble(args[0])) return ConstValue{std::tgamma(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_TGAMMAL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::tgamma(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_TRUNCF: {
      if (auto a = toFloat(args[0])) return ConstValue{std::trunc(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_TRUNC: {
      if (auto a = toDouble(args[0])) return ConstValue{std::trunc(*a)};
      return std::nullopt;
    }
    case BuiltinFunctionKind::T___BUILTIN_TRUNCL: {
      if (auto a = toLongDouble(args[0])) return ConstValue{std::trunc(*a)};
      return std::nullopt;
    }

    default:
      return std::nullopt;
  }
}
