// Generated by gen_builtins_signatures_h.ts
// Copyright (c) 2026 Roberto Raggi <roberto.raggi@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

#include <cxx/builtin_signature.h>
#include <cxx/control.h>

namespace cxx {

enum class BuiltinTypeOp : std::uint8_t {
  kEnd,
  kVariadic,
  kPointer,
  kLvalueReference,
  kRvalueReference,
  kConst,
  kVolatile,
  kComplex,
  kVoid,
  kBool,
  kChar,
  kSignedChar,
  kUnsignedChar,
  kShortInt,
  kUnsignedShortInt,
  kInt,
  kUnsignedInt,
  kLongInt,
  kUnsignedLongInt,
  kLongLongInt,
  kUnsignedLongLongInt,
  kInt128,
  kUnsignedInt128,
  kFloat,
  kDouble,
  kLongDouble,
  kFloat16,
  kWideChar,
  kChar8,
  kChar16,
  kChar32,
  kNullptr,
  kSizeType,
  kBuiltinVaList,
};

[[nodiscard]] inline auto decodeBuiltinLeafType(Control* control,
                                                BuiltinTypeOp op)
    -> const Type* {
  switch (op) {
    case BuiltinTypeOp::kVoid:
      return control->getVoidType();
    case BuiltinTypeOp::kBool:
      return control->getBoolType();
    case BuiltinTypeOp::kChar:
      return control->getCharType();
    case BuiltinTypeOp::kSignedChar:
      return control->getSignedCharType();
    case BuiltinTypeOp::kUnsignedChar:
      return control->getUnsignedCharType();
    case BuiltinTypeOp::kShortInt:
      return control->getShortIntType();
    case BuiltinTypeOp::kUnsignedShortInt:
      return control->getUnsignedShortIntType();
    case BuiltinTypeOp::kInt:
      return control->getIntType();
    case BuiltinTypeOp::kUnsignedInt:
      return control->getUnsignedIntType();
    case BuiltinTypeOp::kLongInt:
      return control->getLongIntType();
    case BuiltinTypeOp::kUnsignedLongInt:
      return control->getUnsignedLongIntType();
    case BuiltinTypeOp::kLongLongInt:
      return control->getLongLongIntType();
    case BuiltinTypeOp::kUnsignedLongLongInt:
      return control->getUnsignedLongLongIntType();
    case BuiltinTypeOp::kInt128:
      return control->getInt128Type();
    case BuiltinTypeOp::kUnsignedInt128:
      return control->getUnsignedInt128Type();
    case BuiltinTypeOp::kFloat:
      return control->getFloatType();
    case BuiltinTypeOp::kDouble:
      return control->getDoubleType();
    case BuiltinTypeOp::kLongDouble:
      return control->getLongDoubleType();
    case BuiltinTypeOp::kFloat16:
      return control->getFloat16Type();
    case BuiltinTypeOp::kWideChar:
      return control->getWideCharType();
    case BuiltinTypeOp::kChar8:
      return control->getChar8Type();
    case BuiltinTypeOp::kChar16:
      return control->getChar16Type();
    case BuiltinTypeOp::kChar32:
      return control->getChar32Type();
    case BuiltinTypeOp::kNullptr:
      return control->getNullptrType();
    case BuiltinTypeOp::kSizeType:
      return control->getSizeType();
    case BuiltinTypeOp::kBuiltinVaList:
      return control->getBuiltinVaListType();
    default:
      return nullptr;
  }
}

inline constexpr std::uint8_t kBuiltinSignatureOps[] = {
    19, 2,  6,  8,  19, 15, 0,  9,  32, 2,  5,  6,  8,  0,  19, 2,  6,  8,  19,
    15, 0,  8,  2,  6,  8,  15, 0,  9,  2,  6,  8,  2,  8,  2,  8,  9,  15, 15,
    0,  9,  2,  6,  8,  2,  8,  19, 9,  15, 15, 0,  8,  2,  6,  8,  2,  8,  2,
    8,  15, 0,  19, 2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,  19, 2,
    6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,
    19, 2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,  9,  32, 2,  5,  6,
    8,  0,  8,  2,  5,  6,  8,  2,  8,  15, 0,  19, 2,  5,  6,  8,  15, 0,  19,
    2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,  8,  15, 0,  8,  2,  6,
    8,  2,  8,  15, 0,  8,  2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,
    9,  2,  6,  8,  15, 0,  8,  15, 0,  19, 2,  6,  8,  19, 15, 0,  16, 0,  2,
    5,  10, 0,  2,  5,  10, 0,  16, 0,  8,  15, 0,  24, 24, 0,  23, 23, 0,  24,
    24, 0,  23, 23, 0,  15, 24, 0,  15, 23, 0,  15, 25, 0,  24, 24, 0,  23, 23,
    0,  24, 24, 0,  23, 23, 0,  8,  0,  15, 15, 0,  24, 24, 0,  23, 23, 0,  24,
    24, 0,  23, 23, 0,  25, 25, 0,  25, 25, 0,  9,  1,  0,  2,  8,  1,  0,  2,
    8,  32, 32, 0,  2,  8,  32, 0,  24, 24, 0,  23, 23, 0,  24, 24, 0,  23, 23,
    0,  25, 25, 0,  25, 25, 0,  2,  8,  2,  5,  8,  32, 1,  0,  24, 24, 0,  24,
    24, 24, 0,  23, 23, 23, 0,  25, 25, 25, 0,  23, 23, 0,  24, 24, 0,  23, 23,
    0,  25, 25, 0,  25, 25, 0,  15, 2,  5,  8,  2,  5,  8,  32, 0,  8,  2,  5,
    8,  2,  8,  32, 0,  14, 14, 0,  16, 16, 0,  20, 20, 0,  8,  2,  8,  32, 0,
    8,  3,  33, 1,  0,  24, 7,  24, 0,  23, 7,  23, 0,  25, 7,  25, 0,  7,  24,
    7,  24, 0,  7,  23, 7,  23, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23, 0,  7,
    25, 7,  25, 0,  7,  25, 7,  25, 0,  24, 7,  24, 0,  23, 7,  23, 0,  25, 7,
    25, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23, 0,  7,  24, 7,  24, 0,  7,  23,
    7,  23, 0,  7,  25, 7,  25, 0,  7,  25, 7,  25, 0,  7,  24, 7,  24, 0,  7,
    23, 7,  23, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23, 0,  7,  25, 7,  25, 0,
    7,  25, 7,  25, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  7,  24, 7,  24, 0,
    7,  23, 7,  23, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23, 0,  7,  25, 7,  25,
    0,  7,  25, 7,  25, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  7,  24, 7,  24,
    0,  7,  23, 7,  23, 0,  7,  25, 7,  25, 0,  24, 7,  24, 0,  23, 7,  23, 0,
    25, 7,  25, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23, 0,  7,  25, 7,  25, 0,
    15, 15, 0,  15, 17, 0,  15, 19, 0,  15, 16, 0,  15, 18, 0,  15, 20, 0,  15,
    14, 0,  7,  23, 23, 23, 0,  7,  24, 24, 24, 0,  7,  25, 25, 25, 0,  7,  24,
    7,  24, 0,  7,  23, 7,  23, 0,  7,  25, 7,  25, 0,  15, 1,  0,  24, 24, 24,
    0,  23, 23, 23, 0,  25, 25, 25, 0,  8,  2,  8,  0,  9,  2,  8,  0,  2,  8,
    2,  8,  15, 9,  0,  8,  2,  8,  0,  24, 24, 0,  23, 23, 0,  24, 24, 0,  23,
    23, 0,  25, 25, 0,  25, 25, 0,  7,  24, 7,  24, 7,  24, 0,  7,  23, 7,  23,
    7,  23, 0,  7,  25, 7,  25, 7,  25, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23,
    0,  7,  25, 7,  25, 0,  24, 7,  24, 0,  23, 7,  23, 0,  25, 7,  25, 0,  7,
    24, 7,  24, 0,  7,  23, 7,  23, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23, 0,
    7,  25, 7,  25, 0,  7,  25, 7,  25, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23,
    0,  7,  25, 7,  25, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23, 0,  7,  24, 7,
    24, 0,  7,  23, 7,  23, 0,  7,  25, 7,  25, 0,  7,  25, 7,  25, 0,  15, 16,
    0,  15, 18, 0,  15, 20, 0,  15, 14, 0,  24, 24, 0,  24, 24, 0,  23, 23, 0,
    25, 25, 0,  23, 23, 0,  25, 25, 0,  8,  15, 0,  24, 24, 0,  24, 24, 0,  23,
    23, 0,  25, 25, 0,  17, 17, 17, 0,  23, 23, 0,  25, 25, 0,  24, 24, 0,  23,
    23, 0,  25, 25, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  24, 24, 24, 0,  23,
    23, 23, 0,  25, 25, 25, 0,  15, 15, 0,  15, 17, 0,  15, 19, 0,  15, 24, 0,
    15, 23, 0,  15, 25, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  24, 24, 24, 24,
    0,  23, 23, 23, 23, 0,  25, 25, 25, 25, 0,  24, 24, 24, 0,  23, 23, 23, 0,
    24, 24, 24, 0,  23, 23, 23, 0,  25, 25, 25, 0,  25, 25, 25, 0,  24, 24, 24,
    0,  23, 23, 23, 0,  24, 24, 24, 0,  23, 23, 23, 0,  25, 25, 25, 0,  25, 25,
    25, 0,  24, 24, 24, 0,  23, 23, 23, 0,  25, 25, 25, 0,  15, 15, 15, 15, 15,
    15, 1,  0,  24, 24, 2,  15, 0,  23, 23, 2,  15, 0,  25, 25, 2,  15, 0,  24,
    0,  23, 0,  25, 0,  24, 24, 24, 0,  23, 23, 23, 0,  25, 25, 25, 0,  15, 24,
    0,  15, 23, 0,  15, 25, 0,  2,  10, 2,  5,  10, 15, 0,  24, 0,  23, 0,  25,
    0,  2,  8,  1,  0,  9,  0,  15, 15, 0,  15, 15, 0,  15, 15, 0,  15, 15, 0,
    15, 15, 0,  9,  23, 0,  9,  24, 0,  9,  25, 0,  15, 15, 0,  9,  1,  0,  9,
    1,  0,  9,  23, 0,  9,  24, 0,  9,  25, 0,  9,  1,  0,  9,  1,  0,  9,  1,
    0,  15, 15, 0,  9,  23, 0,  9,  24, 0,  9,  25, 0,  9,  23, 0,  9,  24, 0,
    9,  25, 0,  15, 15, 0,  15, 15, 0,  15, 15, 0,  9,  1,  0,  15, 15, 0,  15,
    15, 0,  17, 17, 0,  24, 24, 15, 0,  23, 23, 15, 0,  25, 25, 15, 0,  24, 24,
    0,  23, 23, 0,  25, 25, 0,  19, 19, 0,  19, 24, 0,  19, 23, 0,  19, 25, 0,
    19, 24, 0,  19, 23, 0,  19, 25, 0,  24, 24, 0,  24, 24, 0,  23, 23, 0,  25,
    25, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  24, 24, 0,  23, 23, 0,  25, 25,
    0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  23, 23, 0,  25, 25, 0,  17, 24, 0,
    17, 23, 0,  17, 25, 0,  17, 24, 0,  17, 23, 0,  17, 25, 0,  2,  8,  2,  8,
    2,  5,  8,  15, 32, 0,  2,  8,  2,  5,  8,  15, 32, 0,  15, 2,  5,  8,  2,
    5,  8,  32, 0,  2,  8,  2,  8,  2,  5,  8,  32, 0,  2,  8,  2,  8,  2,  5,
    8,  32, 0,  2,  8,  2,  8,  2,  5,  8,  32, 0,  2,  8,  2,  8,  15, 32, 0,
    24, 24, 2,  24, 0,  23, 23, 2,  23, 0,  25, 25, 2,  25, 0,  9,  1,  0,  24,
    2,  5,  10, 0,  23, 2,  5,  10, 0,  25, 2,  5,  10, 0,  24, 2,  5,  10, 0,
    23, 2,  5,  10, 0,  25, 2,  5,  10, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,
    24, 24, 24, 0,  23, 23, 23, 0,  25, 25, 25, 0,  24, 24, 25, 0,  23, 23, 25,
    0,  25, 25, 25, 0,  8,  2,  8,  1,  0,  2,  8,  32, 1,  0,  15, 16, 0,  15,
    18, 0,  15, 20, 0,  15, 16, 0,  15, 18, 0,  15, 20, 0,  24, 24, 24, 0,  23,
    23, 23, 0,  25, 25, 25, 0,  24, 24, 24, 0,  23, 23, 23, 0,  25, 25, 25, 0,
    24, 24, 24, 2,  15, 0,  23, 23, 23, 2,  15, 0,  25, 25, 25, 2,  15, 0,  2,
    10, 2,  5,  10, 15, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  24, 24, 0,  24,
    24, 0,  23, 23, 0,  25, 25, 0,  23, 23, 0,  25, 25, 0,  24, 24, 17, 0,  23,
    23, 17, 0,  25, 25, 17, 0,  24, 24, 15, 0,  23, 23, 15, 0,  25, 25, 15, 0,
    9,  23, 0,  9,  24, 0,  9,  25, 0,  24, 24, 0,  8,  24, 2,  24, 2,  24, 0,
    8,  23, 2,  23, 2,  23, 0,  8,  25, 2,  25, 2,  25, 0,  23, 23, 0,  24, 24,
    0,  23, 23, 0,  25, 25, 0,  25, 25, 0,  2,  5,  8,  0,  24, 24, 0,  23, 23,
    0,  25, 25, 0,  2,  10, 2,  10, 2,  5,  10, 0,  2,  10, 2,  10, 2,  5,  10,
    32, 0,  15, 2,  5,  10, 2,  5,  10, 0,  2,  10, 2,  10, 2,  5,  10, 0,  2,
    10, 2,  5,  10, 15, 0,  15, 2,  5,  10, 2,  5,  10, 0,  2,  10, 2,  10, 2,
    5,  10, 0,  32, 2,  5,  10, 2,  5,  10, 0,  2,  10, 2,  5,  10, 0,  2,  10,
    15, 0,  32, 2,  10, 2,  5,  10, 32, 0,  32, 2,  10, 2,  5,  10, 32, 0,  32,
    2,  5,  10, 0,  15, 2,  5,  10, 2,  5,  10, 32, 0,  2,  10, 2,  10, 2,  5,
    10, 32, 0,  15, 2,  5,  10, 2,  5,  10, 32, 0,  2,  10, 2,  10, 2,  5,  10,
    32, 0,  2,  10, 2,  5,  10, 32, 0,  2,  10, 2,  5,  10, 2,  5,  10, 0,  2,
    10, 2,  5,  10, 15, 0,  32, 2,  5,  10, 2,  5,  10, 0,  2,  10, 2,  5,  10,
    2,  5,  10, 0,  24, 2,  5,  10, 2,  2,  10, 0,  23, 2,  5,  10, 2,  2,  10,
    0,  2,  10, 2,  10, 2,  5,  10, 0,  17, 2,  5,  10, 2,  2,  10, 15, 0,  25,
    2,  5,  10, 2,  2,  10, 0,  19, 2,  5,  10, 2,  2,  10, 15, 0,  18, 2,  5,
    10, 2,  2,  10, 15, 0,  20, 2,  5,  10, 2,  2,  10, 15, 0,  32, 2,  10, 2,
    5,  10, 32, 0,  9,  1,  0,  24, 24, 0,  23, 23, 0,  24, 24, 0,  23, 23, 0,
    25, 25, 0,  25, 25, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  15, 15, 0,  15,
    15, 0,  8,  0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  8,  0,  8,  3,  33, 3,
    33, 0,  8,  3,  33, 0,  8,  3,  33, 1,  0,  15, 2,  10, 32, 2,  5,  10, 3,
    33, 0,  2,  27, 2,  5,  27, 27, 0,  15, 2,  5,  27, 2,  5,  27, 0,  32, 2,
    5,  27, 0,  15, 2,  5,  27, 2,  5,  27, 32, 0,  2,  27, 2,  5,  27, 27, 32,
    0,  15, 2,  5,  27, 2,  5,  27, 32, 0,  2,  27, 2,  27, 2,  5,  27, 32, 0,
    2,  27, 2,  27, 2,  5,  27, 32, 0,  15, 2,  6,  8,  2,  8,  19, 15, 15, 0,
    15, 2,  6,  8,  2,  8,  19, 15, 15, 0,  19, 2,  6,  8,  19, 15, 0,  19, 2,
    6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,
    19, 2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19,
    15, 0,  8,  2,  6,  8,  19, 0,  9,  32, 0,  19, 2,  6,  8,  15, 0,  8,  15,
    0,  8,  2,  6,  8,  19, 15, 0,  8,  15, 0,
};

inline constexpr BuiltinSignature kBuiltinSignatures[] = {
    {},
    {0, 1, BuiltinFlags::kNone},  // __atomic_add_fetch
    {7, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},     // __atomic_always_lock_free
    {14, 1, BuiltinFlags::kNone},      // __atomic_and_fetch
    {21, 1, BuiltinFlags::kNoexcept},  // __atomic_clear
    {27, 1, BuiltinFlags::kNone},      // __atomic_compare_exchange
    {39, 1, BuiltinFlags::kNone},      // __atomic_compare_exchange_n
    {50, 1, BuiltinFlags::kNone},      // __atomic_exchange
    {60, 1, BuiltinFlags::kNone},      // __atomic_exchange_n
    {67, 1, BuiltinFlags::kNone},      // __atomic_fetch_add
    {74, 1, BuiltinFlags::kNone},      // __atomic_fetch_and
    {81, 1, BuiltinFlags::kNone},      // __atomic_fetch_nand
    {88, 1, BuiltinFlags::kNone},      // __atomic_fetch_or
    {95, 1, BuiltinFlags::kNone},      // __atomic_fetch_sub
    {102, 1, BuiltinFlags::kNone},     // __atomic_fetch_xor
    {109, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},      // __atomic_is_lock_free
    {116, 1, BuiltinFlags::kNone},      // __atomic_load
    {125, 1, BuiltinFlags::kNone},      // __atomic_load_n
    {132, 1, BuiltinFlags::kNone},      // __atomic_nand_fetch
    {139, 1, BuiltinFlags::kNone},      // __atomic_or_fetch
    {146, 1, BuiltinFlags::kNoexcept},  // __atomic_signal_fence
    {149, 1, BuiltinFlags::kNone},      // __atomic_store
    {157, 1, BuiltinFlags::kNone},      // __atomic_store_n
    {164, 1, BuiltinFlags::kNone},      // __atomic_sub_fetch
    {171, 1, BuiltinFlags::kNoexcept},  // __atomic_test_and_set
    {177, 1, BuiltinFlags::kNoexcept},  // __atomic_thread_fence
    {180, 1, BuiltinFlags::kNone},      // __atomic_xor_fetch
    {187, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kConsteval |
         BuiltinFlags::kNoexcept},  // __builtin_COLUMN
    {189, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kConsteval |
         BuiltinFlags::kNoexcept},  // __builtin_FILE
    {193, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kConsteval |
         BuiltinFlags::kNoexcept},  // __builtin_FUNCTION
    {197, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kConsteval |
         BuiltinFlags::kNoexcept},      // __builtin_LINE
    {199, 1, BuiltinFlags::kNoReturn},  // __builtin__Exit
    {202, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___cospi
    {205, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___cospif
    {208, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___exp10
    {211, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___exp10f
    {214, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___finite
    {217, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin___finitef
    {220, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin___finitel
    {223, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___sinpi
    {226, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___sinpif
    {229, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___tanpi
    {232, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___tanpif
    {235, 1,
     BuiltinFlags::kNoexcept | BuiltinFlags::kNoReturn},  // __builtin_abort
    {237, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_abs
    {240, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_acos
    {243, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_acosf
    {246, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_acosh
    {249, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_acoshf
    {252, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_acoshl
    {255, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_acosl
    {258, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_add_overflow
    {261, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},      // __builtin_addressof
    {265, 1, BuiltinFlags::kNone},      // __builtin_aligned_alloc
    {270, 1, BuiltinFlags::kNoexcept},  // __builtin_alloca
    {274, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_asin
    {277, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_asinf
    {280, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_asinh
    {283, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_asinhf
    {286, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_asinhl
    {289, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_asinl
    {292, 1, BuiltinFlags::kNoexcept},  // __builtin_assume_aligned
    {300, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atan
    {303, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atan2
    {307, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atan2f
    {311, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atan2l
    {315, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atanf
    {318, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atanh
    {321, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atanhf
    {324, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atanhl
    {327, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atanl
    {330, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_bcmp
    {339, 1, BuiltinFlags::kNoexcept},                     // __builtin_bcopy
    {347, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_bswap16
    {350, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_bswap32
    {353, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_bswap64
    {356, 1, BuiltinFlags::kNoexcept},                     // __builtin_bzero
    {361, 1, BuiltinFlags::kNoexcept},  // __builtin_c23_va_start
    {366, 1, BuiltinFlags::kNoexcept},  // __builtin_cabs
    {370, 1, BuiltinFlags::kNoexcept},  // __builtin_cabsf
    {374, 1, BuiltinFlags::kNoexcept},  // __builtin_cabsl
    {378, 1, BuiltinFlags::kNoexcept},  // __builtin_cacos
    {383, 1, BuiltinFlags::kNoexcept},  // __builtin_cacosf
    {388, 1, BuiltinFlags::kNoexcept},  // __builtin_cacosh
    {393, 1, BuiltinFlags::kNoexcept},  // __builtin_cacoshf
    {398, 1, BuiltinFlags::kNoexcept},  // __builtin_cacoshl
    {403, 1, BuiltinFlags::kNoexcept},  // __builtin_cacosl
    {408, 1, BuiltinFlags::kNoexcept},  // __builtin_carg
    {412, 1, BuiltinFlags::kNoexcept},  // __builtin_cargf
    {416, 1, BuiltinFlags::kNoexcept},  // __builtin_cargl
    {420, 1, BuiltinFlags::kNoexcept},  // __builtin_casin
    {425, 1, BuiltinFlags::kNoexcept},  // __builtin_casinf
    {430, 1, BuiltinFlags::kNoexcept},  // __builtin_casinh
    {435, 1, BuiltinFlags::kNoexcept},  // __builtin_casinhf
    {440, 1, BuiltinFlags::kNoexcept},  // __builtin_casinhl
    {445, 1, BuiltinFlags::kNoexcept},  // __builtin_casinl
    {450, 1, BuiltinFlags::kNoexcept},  // __builtin_catan
    {455, 1, BuiltinFlags::kNoexcept},  // __builtin_catanf
    {460, 1, BuiltinFlags::kNoexcept},  // __builtin_catanh
    {465, 1, BuiltinFlags::kNoexcept},  // __builtin_catanhf
    {470, 1, BuiltinFlags::kNoexcept},  // __builtin_catanhl
    {475, 1, BuiltinFlags::kNoexcept},  // __builtin_catanl
    {480, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_cbrt
    {483, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_cbrtf
    {486, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_cbrtl
    {489, 1, BuiltinFlags::kNoexcept},                     // __builtin_ccos
    {494, 1, BuiltinFlags::kNoexcept},                     // __builtin_ccosf
    {499, 1, BuiltinFlags::kNoexcept},                     // __builtin_ccosh
    {504, 1, BuiltinFlags::kNoexcept},                     // __builtin_ccoshf
    {509, 1, BuiltinFlags::kNoexcept},                     // __builtin_ccoshl
    {514, 1, BuiltinFlags::kNoexcept},                     // __builtin_ccosl
    {519, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ceil
    {522, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ceilf
    {525, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ceill
    {528, 1, BuiltinFlags::kNoexcept},                     // __builtin_cexp
    {533, 1, BuiltinFlags::kNoexcept},                     // __builtin_cexpf
    {538, 1, BuiltinFlags::kNoexcept},                     // __builtin_cexpl
    {543, 1, BuiltinFlags::kNoexcept},                     // __builtin_cimag
    {547, 1, BuiltinFlags::kNoexcept},                     // __builtin_cimagf
    {551, 1, BuiltinFlags::kNoexcept},                     // __builtin_cimagl
    {555, 1, BuiltinFlags::kNoexcept},                     // __builtin_clog
    {560, 1, BuiltinFlags::kNoexcept},                     // __builtin_clogf
    {565, 1, BuiltinFlags::kNoexcept},                     // __builtin_clogl
    {570, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_clrsb
    {573, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_clrsbl
    {576, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_clrsbll
    {579, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_clz
    {582, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_clzl
    {585, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_clzll
    {588, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_clzs
    {591, 3,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_complex
    {606, 1, BuiltinFlags::kNoexcept},                     // __builtin_conj
    {611, 1, BuiltinFlags::kNoexcept},                     // __builtin_conjf
    {616, 1, BuiltinFlags::kNoexcept},                     // __builtin_conjl
    {621, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_constant_p
    {624, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_copysign
    {628, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_copysignf
    {632, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},      // __builtin_copysignl
    {636, 1, BuiltinFlags::kNone},      // __builtin_coro_destroy
    {640, 1, BuiltinFlags::kNoexcept},  // __builtin_coro_done
    {644, 1, BuiltinFlags::kNoexcept},  // __builtin_coro_promise
    {651, 1, BuiltinFlags::kNone},      // __builtin_coro_resume
    {655, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_cos
    {658, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_cosf
    {661, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_cosh
    {664, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_coshf
    {667, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_coshl
    {670, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_cosl
    {673, 1, BuiltinFlags::kNoexcept},                     // __builtin_cpow
    {680, 1, BuiltinFlags::kNoexcept},                     // __builtin_cpowf
    {687, 1, BuiltinFlags::kNoexcept},                     // __builtin_cpowl
    {694, 1, BuiltinFlags::kNoexcept},                     // __builtin_cproj
    {699, 1, BuiltinFlags::kNoexcept},                     // __builtin_cprojf
    {704, 1, BuiltinFlags::kNoexcept},                     // __builtin_cprojl
    {709, 1, BuiltinFlags::kNoexcept},                     // __builtin_creal
    {713, 1, BuiltinFlags::kNoexcept},                     // __builtin_crealf
    {717, 1, BuiltinFlags::kNoexcept},                     // __builtin_creall
    {721, 1, BuiltinFlags::kNoexcept},                     // __builtin_csin
    {726, 1, BuiltinFlags::kNoexcept},                     // __builtin_csinf
    {731, 1, BuiltinFlags::kNoexcept},                     // __builtin_csinh
    {736, 1, BuiltinFlags::kNoexcept},                     // __builtin_csinhf
    {741, 1, BuiltinFlags::kNoexcept},                     // __builtin_csinhl
    {746, 1, BuiltinFlags::kNoexcept},                     // __builtin_csinl
    {751, 1, BuiltinFlags::kNoexcept},                     // __builtin_csqrt
    {756, 1, BuiltinFlags::kNoexcept},                     // __builtin_csqrtf
    {761, 1, BuiltinFlags::kNoexcept},                     // __builtin_csqrtl
    {766, 1, BuiltinFlags::kNoexcept},                     // __builtin_ctan
    {771, 1, BuiltinFlags::kNoexcept},                     // __builtin_ctanf
    {776, 1, BuiltinFlags::kNoexcept},                     // __builtin_ctanh
    {781, 1, BuiltinFlags::kNoexcept},                     // __builtin_ctanhf
    {786, 1, BuiltinFlags::kNoexcept},                     // __builtin_ctanhl
    {791, 1, BuiltinFlags::kNoexcept},                     // __builtin_ctanl
    {796, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ctz
    {799, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ctzl
    {802, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ctzll
    {805, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ctzs
    {808, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_erf
    {811, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_erfc
    {814, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_erfcf
    {817, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_erfcl
    {820, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_erff
    {823, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_erfl
    {826, 1, BuiltinFlags::kNoReturn},                     // __builtin_exit
    {829, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_exp
    {832, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_exp2
    {835, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_exp2f
    {838, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_exp2l
    {841, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_expect
    {845, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_expf
    {848, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_expl
    {851, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_expm1
    {854, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_expm1f
    {857, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_expm1l
    {860, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fabs
    {863, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fabsf
    {866, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fabsl
    {869, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fdim
    {873, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fdimf
    {877, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fdiml
    {881, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ffs
    {884, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ffsl
    {887, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ffsll
    {890, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_finite
    {893, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_finitef
    {896, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_finitel
    {899, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_floor
    {902, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_floorf
    {905, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_floorl
    {908, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fma
    {913, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmaf
    {918, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmal
    {923, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmax
    {927, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmaxf
    {931, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_fmaximum_num
    {935, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_fmaximum_numf
    {939, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_fmaximum_numl
    {943, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmaxl
    {947, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmin
    {951, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fminf
    {955, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_fminimum_num
    {959, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_fminimum_numf
    {963, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_fminimum_numl
    {967, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fminl
    {971, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmod
    {975, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmodf
    {979, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmodl
    {983, 1, BuiltinFlags::kNoexcept},   // __builtin_fpclassify
    {991, 1, BuiltinFlags::kNoexcept},   // __builtin_frexp
    {996, 1, BuiltinFlags::kNoexcept},   // __builtin_frexpf
    {1001, 1, BuiltinFlags::kNoexcept},  // __builtin_frexpl
    {1006, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_huge_val
    {1008, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_huge_valf
    {1010, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_huge_vall
    {1012, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_hypot
    {1016, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_hypotf
    {1020, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_hypotl
    {1024, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ilogb
    {1027, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ilogbf
    {1030, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ilogbl
    {1033, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_index
    {1040, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_inf
    {1042, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_inff
    {1044, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_infl
    {1046, 1, BuiltinFlags::kNone},                        // __builtin_invoke
    {1050, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},       // __builtin_is_constant_evaluated
    {1052, 1, BuiltinFlags::kNoexcept},  // __builtin_isalnum
    {1055, 1, BuiltinFlags::kNoexcept},  // __builtin_isalpha
    {1058, 1, BuiltinFlags::kNoexcept},  // __builtin_isblank
    {1061, 1, BuiltinFlags::kNoexcept},  // __builtin_iscntrl
    {1064, 1, BuiltinFlags::kNoexcept},  // __builtin_isdigit
    {1067, 3,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_isfinite
    {1076, 1, BuiltinFlags::kNoexcept},                    // __builtin_isgraph
    {1079, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_isgreater
    {1082, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_isgreaterequal
    {1085, 3,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_isinf
    {1094, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_isless
    {1097, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_islessequal
    {1100, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},       // __builtin_islessgreater
    {1103, 1, BuiltinFlags::kNoexcept},  // __builtin_islower
    {1106, 3,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_isnan
    {1115, 3, BuiltinFlags::kNoexcept},                    // __builtin_isnormal
    {1124, 1, BuiltinFlags::kNoexcept},                    // __builtin_isprint
    {1127, 1, BuiltinFlags::kNoexcept},                    // __builtin_ispunct
    {1130, 1, BuiltinFlags::kNoexcept},                    // __builtin_isspace
    {1133, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},       // __builtin_isunordered
    {1136, 1, BuiltinFlags::kNoexcept},  // __builtin_isupper
    {1139, 1, BuiltinFlags::kNoexcept},  // __builtin_isxdigit
    {1142, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_labs
    {1145, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ldexp
    {1149, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ldexpf
    {1153, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ldexpl
    {1157, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lgamma
    {1160, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lgammaf
    {1163, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lgammal
    {1166, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_llabs
    {1169, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_llrint
    {1172, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_llrintf
    {1175, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_llrintl
    {1178, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_llround
    {1181, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_llroundf
    {1184, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_llroundl
    {1187, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log
    {1190, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log10
    {1193, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log10f
    {1196, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log10l
    {1199, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log1p
    {1202, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log1pf
    {1205, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log1pl
    {1208, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log2
    {1211, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log2f
    {1214, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log2l
    {1217, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_logb
    {1220, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_logbf
    {1223, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_logbl
    {1226, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_logf
    {1229, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_logl
    {1232, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lrint
    {1235, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lrintf
    {1238, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lrintl
    {1241, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lround
    {1244, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lroundf
    {1247, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lroundl
    {1250, 1, BuiltinFlags::kNone},                        // __builtin_memccpy
    {1260, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_memchr
    {1268, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_memcmp
    {1277, 1, BuiltinFlags::kNoexcept},                    // __builtin_memcpy
    {1286, 1, BuiltinFlags::kNoexcept},                    // __builtin_memmove
    {1295, 1, BuiltinFlags::kNoexcept},                    // __builtin_mempcpy
    {1304, 1, BuiltinFlags::kNoexcept},                    // __builtin_memset
    {1311, 1, BuiltinFlags::kNoexcept},                    // __builtin_modf
    {1316, 1, BuiltinFlags::kNoexcept},                    // __builtin_modff
    {1321, 1, BuiltinFlags::kNoexcept},                    // __builtin_modfl
    {1326, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_mul_overflow
    {1329, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_nan
    {1334, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_nanf
    {1339, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_nanl
    {1344, 1, BuiltinFlags::kNoexcept},                    // __builtin_nans
    {1349, 1, BuiltinFlags::kNoexcept},                    // __builtin_nansf
    {1354, 1, BuiltinFlags::kNoexcept},                    // __builtin_nansl
    {1359, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nearbyint
    {1362, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nearbyintf
    {1365, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nearbyintl
    {1368, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nextafter
    {1372, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nextafterf
    {1376, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nextafterl
    {1380, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nexttoward
    {1384, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nexttowardf
    {1388, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},       // __builtin_nexttowardl
    {1392, 1, BuiltinFlags::kNoexcept},  // __builtin_operator_delete
    {1397, 1, BuiltinFlags::kNone},      // __builtin_operator_new
    {1402, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_parity
    {1405, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_parityl
    {1408, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_parityll
    {1411, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_popcount
    {1414, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_popcountl
    {1417, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_popcountll
    {1420, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_pow
    {1424, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_powf
    {1428, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_powl
    {1432, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_remainder
    {1436, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_remainderf
    {1440, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},       // __builtin_remainderl
    {1444, 1, BuiltinFlags::kNoexcept},  // __builtin_remquo
    {1450, 1, BuiltinFlags::kNoexcept},  // __builtin_remquof
    {1456, 1, BuiltinFlags::kNoexcept},  // __builtin_remquol
    {1462, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_rindex
    {1469, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_rint
    {1472, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_rintf
    {1475, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_rintl
    {1478, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_round
    {1481, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_roundeven
    {1484, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_roundevenf
    {1487, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_roundevenl
    {1490, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_roundf
    {1493, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_roundl
    {1496, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_scalbln
    {1500, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_scalblnf
    {1504, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_scalblnl
    {1508, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_scalbn
    {1512, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_scalbnf
    {1516, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_scalbnl
    {1520, 3,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_signbit
    {1529, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sin
    {1532, 1, BuiltinFlags::kNoexcept},                    // __builtin_sincos
    {1539, 1, BuiltinFlags::kNoexcept},                    // __builtin_sincosf
    {1546, 1, BuiltinFlags::kNoexcept},                    // __builtin_sincosl
    {1553, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sinf
    {1556, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sinh
    {1559, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sinhf
    {1562, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sinhl
    {1565, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sinl
    {1568, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kConsteval |
         BuiltinFlags::kNoexcept},  // __builtin_source_location
    {1572, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sqrt
    {1575, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sqrtf
    {1578, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sqrtl
    {1581, 1, BuiltinFlags::kNoexcept},                    // __builtin_stpcpy
    {1589, 1, BuiltinFlags::kNoexcept},                    // __builtin_stpncpy
    {1598, 1, BuiltinFlags::kConstexpr},  // __builtin_strcasecmp
    {1606, 1, BuiltinFlags::kNoexcept},   // __builtin_strcat
    {1614, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strchr
    {1621, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strcmp
    {1629, 1, BuiltinFlags::kNoexcept},                    // __builtin_strcpy
    {1637, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strcspn
    {1645, 1, BuiltinFlags::kNoexcept},                    // __builtin_strdup
    {1651, 1, BuiltinFlags::kNone},                        // __builtin_strerror
    {1655, 1, BuiltinFlags::kNone},                        // __builtin_strlcat
    {1663, 1, BuiltinFlags::kNone},                        // __builtin_strlcpy
    {1671, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strlen
    {1676, 1, BuiltinFlags::kConstexpr},  // __builtin_strncasecmp
    {1685, 1, BuiltinFlags::kNoexcept},   // __builtin_strncat
    {1694, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strncmp
    {1703, 1, BuiltinFlags::kNoexcept},                    // __builtin_strncpy
    {1712, 1, BuiltinFlags::kNoexcept},                    // __builtin_strndup
    {1719, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strpbrk
    {1728, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strrchr
    {1735, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strspn
    {1743, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strstr
    {1752, 1, BuiltinFlags::kNone},                        // __builtin_strtod
    {1760, 1, BuiltinFlags::kNone},                        // __builtin_strtof
    {1768, 1, BuiltinFlags::kNone},                        // __builtin_strtok
    {1776, 1, BuiltinFlags::kNone},                        // __builtin_strtol
    {1785, 1, BuiltinFlags::kNone},                        // __builtin_strtold
    {1793, 1, BuiltinFlags::kNone},                        // __builtin_strtoll
    {1802, 1, BuiltinFlags::kNone},                        // __builtin_strtoul
    {1811, 1, BuiltinFlags::kNone},                        // __builtin_strtoull
    {1820, 1, BuiltinFlags::kNone},                        // __builtin_strxfrm
    {1828, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_sub_overflow
    {1831, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tan
    {1834, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tanf
    {1837, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tanh
    {1840, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tanhf
    {1843, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tanhl
    {1846, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tanl
    {1849, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tgamma
    {1852, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tgammaf
    {1855, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tgammal
    {1858, 1, BuiltinFlags::kNoexcept},                    // __builtin_tolower
    {1861, 1, BuiltinFlags::kNoexcept},                    // __builtin_toupper
    {1864, 1,
     BuiltinFlags::kNoexcept | BuiltinFlags::kNoReturn},  // __builtin_trap
    {1866, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_trunc
    {1869, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_truncf
    {1872, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_truncl
    {1875, 1,
     BuiltinFlags::kNoexcept |
         BuiltinFlags::kNoReturn},       // __builtin_unreachable
    {1877, 1, BuiltinFlags::kNoexcept},  // __builtin_va_copy
    {1883, 1, BuiltinFlags::kNoexcept},  // __builtin_va_end
    {1887, 1, BuiltinFlags::kNoexcept},  // __builtin_va_start
    {1892, 1, BuiltinFlags::kNoexcept},  // __builtin_vsnprintf
    {1902, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wcschr
    {1909, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wcscmp
    {1917, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wcslen
    {1922, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wcsncmp
    {1931, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wmemchr
    {1939, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wmemcmp
    {1948, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wmemcpy
    {1957, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wmemmove
    {1966, 1, BuiltinFlags::kNone},  // __c11_atomic_compare_exchange_strong
    {1976, 1, BuiltinFlags::kNone},  // __c11_atomic_compare_exchange_weak
    {1986, 1, BuiltinFlags::kNone},  // __c11_atomic_exchange
    {1993, 1, BuiltinFlags::kNone},  // __c11_atomic_fetch_add
    {2000, 1, BuiltinFlags::kNone},  // __c11_atomic_fetch_and
    {2007, 1, BuiltinFlags::kNone},  // __c11_atomic_fetch_nand
    {2014, 1, BuiltinFlags::kNone},  // __c11_atomic_fetch_or
    {2021, 1, BuiltinFlags::kNone},  // __c11_atomic_fetch_sub
    {2028, 1, BuiltinFlags::kNone},  // __c11_atomic_fetch_xor
    {2035, 1, BuiltinFlags::kNone},  // __c11_atomic_init
    {2041, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},       // __c11_atomic_is_lock_free
    {2044, 1, BuiltinFlags::kNone},      // __c11_atomic_load
    {2050, 1, BuiltinFlags::kNoexcept},  // __c11_atomic_signal_fence
    {2053, 1, BuiltinFlags::kNone},      // __c11_atomic_store
    {2060, 1, BuiltinFlags::kNoexcept},  // __c11_atomic_thread_fence
};

static_assert(
    std::size(kBuiltinSignatures) ==
    static_cast<std::size_t>(BuiltinFunctionKind::T___C11_ATOMIC_THREAD_FENCE) +
        1);

}  // namespace cxx
