// Generated by gen_builtins_h.ts
// Copyright (c) 2026 Roberto Raggi <roberto.raggi@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

// clang-format off
static constexpr const char* builtinsSource = R"(

#define __cxx_builtin_arity(_1, _2, selected, ...) selected
#define __cxx_builtin_overload(one, two, ...) __cxx_builtin_arity(__VA_ARGS__, two, one)

#define __cxx_clzg_dispatch(x) _Generic((x), \
    unsigned char: __builtin_clz((unsigned int)(x)) - 24, \
    unsigned short: __builtin_clzs(x), \
    unsigned int: __builtin_clz(x), \
    unsigned long: __builtin_clzl(x), \
    unsigned long long: __builtin_clzll(x), \
    unsigned __int128: ((unsigned long long)((x) >> 64) ? __builtin_clzll((unsigned long long)((x) >> 64)) : 64 + __builtin_clzll((unsigned long long)(x))))
#define __cxx_clzg_or(x, fallback) ((x) ? __cxx_clzg_dispatch(x) : _Generic((fallback), int: (fallback)))
#define __builtin_clzg(...) __cxx_builtin_overload(__cxx_clzg_dispatch, __cxx_clzg_or, __VA_ARGS__)(__VA_ARGS__)

#define __cxx_ctzg_dispatch(x) _Generic((x), \
    unsigned char: __builtin_ctz((unsigned int)(x)), \
    unsigned short: __builtin_ctzs(x), \
    unsigned int: __builtin_ctz(x), \
    unsigned long: __builtin_ctzl(x), \
    unsigned long long: __builtin_ctzll(x), \
    unsigned __int128: ((unsigned long long)(x) ? __builtin_ctzll((unsigned long long)(x)) : 64 + __builtin_ctzll((unsigned long long)((x) >> 64))))
#define __cxx_ctzg_or(x, fallback) ((x) ? __cxx_ctzg_dispatch(x) : _Generic((fallback), int: (fallback)))
#define __builtin_ctzg(...) __cxx_builtin_overload(__cxx_ctzg_dispatch, __cxx_ctzg_or, __VA_ARGS__)(__VA_ARGS__)

#define __cxx_popcountg_dispatch(x) _Generic((x), \
    unsigned char: __builtin_popcount((unsigned int)(x)), \
    unsigned short: __builtin_popcount((unsigned int)(x)), \
    unsigned int: __builtin_popcount(x), \
    unsigned long: __builtin_popcountl(x), \
    unsigned long long: __builtin_popcountll(x), \
    unsigned __int128: (__builtin_popcountll((unsigned long long)(x)) + __builtin_popcountll((unsigned long long)((x) >> 64))))
#define __builtin_popcountg(x) __cxx_popcountg_dispatch(x)

#ifdef __cplusplus

template <template <class IntSeqT, IntSeqT... Ints> class IntSeq, class T, T N>
using __make_integer_seq = void;

template <__SIZE_TYPE__ Index, class... Ts>
using __type_pack_element = void;

template <template <class... Args> class BaseTemplate,
          template <class TypeMember> class HasTypeMember,
          class HasNoTypeMember,
          class... Ts>
using __builtin_common_type = void;

void* operator new(__SIZE_TYPE__);
void* operator new[](__SIZE_TYPE__);
void operator delete(void*) noexcept;
void operator delete[](void*) noexcept;
void operator delete(void*, __SIZE_TYPE__) noexcept;
void operator delete[](void*, __SIZE_TYPE__) noexcept;

#endif
)";
// clang-format on
