// Generated by gen_builtins_typechecker_h.ts
// Copyright (c) 2026 Roberto Raggi <roberto.raggi@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// A libcall builtin (e.g. `__builtin_strlen`) that isn't constant-folded
// lowers to the C library function of the same name, sans the
// `__builtin_` prefix (Token::spell strips it at the call site).
auto cxx::isBuiltinLibcall(cxx::BuiltinFunctionKind kind) -> bool {
  switch (kind) {
    case BuiltinFunctionKind::T___BUILTIN_ABS:
    case BuiltinFunctionKind::T___BUILTIN_LABS:
    case BuiltinFunctionKind::T___BUILTIN_LLABS:
    case BuiltinFunctionKind::T___BUILTIN_ACOSF:
    case BuiltinFunctionKind::T___BUILTIN_ACOS:
    case BuiltinFunctionKind::T___BUILTIN_ACOSL:
    case BuiltinFunctionKind::T___BUILTIN_ACOSHF:
    case BuiltinFunctionKind::T___BUILTIN_ACOSH:
    case BuiltinFunctionKind::T___BUILTIN_ACOSHL:
    case BuiltinFunctionKind::T___BUILTIN_ASINF:
    case BuiltinFunctionKind::T___BUILTIN_ASIN:
    case BuiltinFunctionKind::T___BUILTIN_ASINL:
    case BuiltinFunctionKind::T___BUILTIN_ASINHF:
    case BuiltinFunctionKind::T___BUILTIN_ASINH:
    case BuiltinFunctionKind::T___BUILTIN_ASINHL:
    case BuiltinFunctionKind::T___BUILTIN_ATANF:
    case BuiltinFunctionKind::T___BUILTIN_ATAN:
    case BuiltinFunctionKind::T___BUILTIN_ATANL:
    case BuiltinFunctionKind::T___BUILTIN_ATAN2F:
    case BuiltinFunctionKind::T___BUILTIN_ATAN2:
    case BuiltinFunctionKind::T___BUILTIN_ATAN2L:
    case BuiltinFunctionKind::T___BUILTIN_ATANHF:
    case BuiltinFunctionKind::T___BUILTIN_ATANH:
    case BuiltinFunctionKind::T___BUILTIN_ATANHL:
    case BuiltinFunctionKind::T___BUILTIN_CBRTF:
    case BuiltinFunctionKind::T___BUILTIN_CBRT:
    case BuiltinFunctionKind::T___BUILTIN_CBRTL:
    case BuiltinFunctionKind::T___BUILTIN_CEILF:
    case BuiltinFunctionKind::T___BUILTIN_CEIL:
    case BuiltinFunctionKind::T___BUILTIN_CEILL:
    case BuiltinFunctionKind::T___BUILTIN_COPYSIGNF:
    case BuiltinFunctionKind::T___BUILTIN_COPYSIGN:
    case BuiltinFunctionKind::T___BUILTIN_COPYSIGNL:
    case BuiltinFunctionKind::T___BUILTIN_COSF:
    case BuiltinFunctionKind::T___BUILTIN_COS:
    case BuiltinFunctionKind::T___BUILTIN_COSL:
    case BuiltinFunctionKind::T___BUILTIN_COSHF:
    case BuiltinFunctionKind::T___BUILTIN_COSH:
    case BuiltinFunctionKind::T___BUILTIN_COSHL:
    case BuiltinFunctionKind::T___BUILTIN_ERFF:
    case BuiltinFunctionKind::T___BUILTIN_ERF:
    case BuiltinFunctionKind::T___BUILTIN_ERFL:
    case BuiltinFunctionKind::T___BUILTIN_ERFCF:
    case BuiltinFunctionKind::T___BUILTIN_ERFC:
    case BuiltinFunctionKind::T___BUILTIN_ERFCL:
    case BuiltinFunctionKind::T___BUILTIN_EXPF:
    case BuiltinFunctionKind::T___BUILTIN_EXP:
    case BuiltinFunctionKind::T___BUILTIN_EXPL:
    case BuiltinFunctionKind::T___BUILTIN_EXP2F:
    case BuiltinFunctionKind::T___BUILTIN_EXP2:
    case BuiltinFunctionKind::T___BUILTIN_EXP2L:
    case BuiltinFunctionKind::T___BUILTIN_EXPM1F:
    case BuiltinFunctionKind::T___BUILTIN_EXPM1:
    case BuiltinFunctionKind::T___BUILTIN_EXPM1L:
    case BuiltinFunctionKind::T___BUILTIN_FABSF:
    case BuiltinFunctionKind::T___BUILTIN_FABS:
    case BuiltinFunctionKind::T___BUILTIN_FABSL:
    case BuiltinFunctionKind::T___BUILTIN_FDIMF:
    case BuiltinFunctionKind::T___BUILTIN_FDIM:
    case BuiltinFunctionKind::T___BUILTIN_FDIML:
    case BuiltinFunctionKind::T___BUILTIN_FLOORF:
    case BuiltinFunctionKind::T___BUILTIN_FLOOR:
    case BuiltinFunctionKind::T___BUILTIN_FLOORL:
    case BuiltinFunctionKind::T___BUILTIN_FMAF:
    case BuiltinFunctionKind::T___BUILTIN_FMA:
    case BuiltinFunctionKind::T___BUILTIN_FMAL:
    case BuiltinFunctionKind::T___BUILTIN_FMAXF:
    case BuiltinFunctionKind::T___BUILTIN_FMAX:
    case BuiltinFunctionKind::T___BUILTIN_FMAXL:
    case BuiltinFunctionKind::T___BUILTIN_FMINF:
    case BuiltinFunctionKind::T___BUILTIN_FMIN:
    case BuiltinFunctionKind::T___BUILTIN_FMINL:
    case BuiltinFunctionKind::T___BUILTIN_FMODF:
    case BuiltinFunctionKind::T___BUILTIN_FMOD:
    case BuiltinFunctionKind::T___BUILTIN_FMODL:
    case BuiltinFunctionKind::T___BUILTIN_FREXPF:
    case BuiltinFunctionKind::T___BUILTIN_FREXP:
    case BuiltinFunctionKind::T___BUILTIN_FREXPL:
    case BuiltinFunctionKind::T___BUILTIN_HYPOTF:
    case BuiltinFunctionKind::T___BUILTIN_HYPOT:
    case BuiltinFunctionKind::T___BUILTIN_HYPOTL:
    case BuiltinFunctionKind::T___BUILTIN_ILOGBF:
    case BuiltinFunctionKind::T___BUILTIN_ILOGB:
    case BuiltinFunctionKind::T___BUILTIN_ILOGBL:
    case BuiltinFunctionKind::T___BUILTIN_LDEXPF:
    case BuiltinFunctionKind::T___BUILTIN_LDEXP:
    case BuiltinFunctionKind::T___BUILTIN_LDEXPL:
    case BuiltinFunctionKind::T___BUILTIN_LGAMMAF:
    case BuiltinFunctionKind::T___BUILTIN_LGAMMA:
    case BuiltinFunctionKind::T___BUILTIN_LGAMMAL:
    case BuiltinFunctionKind::T___BUILTIN_LLRINTF:
    case BuiltinFunctionKind::T___BUILTIN_LLRINT:
    case BuiltinFunctionKind::T___BUILTIN_LLRINTL:
    case BuiltinFunctionKind::T___BUILTIN_LLROUNDF:
    case BuiltinFunctionKind::T___BUILTIN_LLROUND:
    case BuiltinFunctionKind::T___BUILTIN_LLROUNDL:
    case BuiltinFunctionKind::T___BUILTIN_LOGF:
    case BuiltinFunctionKind::T___BUILTIN_LOG:
    case BuiltinFunctionKind::T___BUILTIN_LOGL:
    case BuiltinFunctionKind::T___BUILTIN_LOG1PF:
    case BuiltinFunctionKind::T___BUILTIN_LOG1P:
    case BuiltinFunctionKind::T___BUILTIN_LOG1PL:
    case BuiltinFunctionKind::T___BUILTIN_LOG2F:
    case BuiltinFunctionKind::T___BUILTIN_LOG2:
    case BuiltinFunctionKind::T___BUILTIN_LOG2L:
    case BuiltinFunctionKind::T___BUILTIN_LOG10F:
    case BuiltinFunctionKind::T___BUILTIN_LOG10:
    case BuiltinFunctionKind::T___BUILTIN_LOG10L:
    case BuiltinFunctionKind::T___BUILTIN_LOGBF:
    case BuiltinFunctionKind::T___BUILTIN_LOGB:
    case BuiltinFunctionKind::T___BUILTIN_LOGBL:
    case BuiltinFunctionKind::T___BUILTIN_LRINTF:
    case BuiltinFunctionKind::T___BUILTIN_LRINT:
    case BuiltinFunctionKind::T___BUILTIN_LRINTL:
    case BuiltinFunctionKind::T___BUILTIN_LROUNDF:
    case BuiltinFunctionKind::T___BUILTIN_LROUND:
    case BuiltinFunctionKind::T___BUILTIN_LROUNDL:
    case BuiltinFunctionKind::T___BUILTIN_MODFF:
    case BuiltinFunctionKind::T___BUILTIN_MODF:
    case BuiltinFunctionKind::T___BUILTIN_MODFL:
    case BuiltinFunctionKind::T___BUILTIN_NANF:
    case BuiltinFunctionKind::T___BUILTIN_NAN:
    case BuiltinFunctionKind::T___BUILTIN_NANL:
    case BuiltinFunctionKind::T___BUILTIN_NEARBYINTF:
    case BuiltinFunctionKind::T___BUILTIN_NEARBYINT:
    case BuiltinFunctionKind::T___BUILTIN_NEARBYINTL:
    case BuiltinFunctionKind::T___BUILTIN_NEXTAFTERF:
    case BuiltinFunctionKind::T___BUILTIN_NEXTAFTER:
    case BuiltinFunctionKind::T___BUILTIN_NEXTAFTERL:
    case BuiltinFunctionKind::T___BUILTIN_NEXTTOWARDF:
    case BuiltinFunctionKind::T___BUILTIN_NEXTTOWARD:
    case BuiltinFunctionKind::T___BUILTIN_NEXTTOWARDL:
    case BuiltinFunctionKind::T___BUILTIN_POWF:
    case BuiltinFunctionKind::T___BUILTIN_POW:
    case BuiltinFunctionKind::T___BUILTIN_POWL:
    case BuiltinFunctionKind::T___BUILTIN_REMAINDERF:
    case BuiltinFunctionKind::T___BUILTIN_REMAINDER:
    case BuiltinFunctionKind::T___BUILTIN_REMAINDERL:
    case BuiltinFunctionKind::T___BUILTIN_REMQUOF:
    case BuiltinFunctionKind::T___BUILTIN_REMQUO:
    case BuiltinFunctionKind::T___BUILTIN_REMQUOL:
    case BuiltinFunctionKind::T___BUILTIN_RINTF:
    case BuiltinFunctionKind::T___BUILTIN_RINT:
    case BuiltinFunctionKind::T___BUILTIN_RINTL:
    case BuiltinFunctionKind::T___BUILTIN_ROUNDF:
    case BuiltinFunctionKind::T___BUILTIN_ROUND:
    case BuiltinFunctionKind::T___BUILTIN_ROUNDL:
    case BuiltinFunctionKind::T___BUILTIN_ROUNDEVENF:
    case BuiltinFunctionKind::T___BUILTIN_ROUNDEVEN:
    case BuiltinFunctionKind::T___BUILTIN_ROUNDEVENL:
    case BuiltinFunctionKind::T___BUILTIN_SCALBLNF:
    case BuiltinFunctionKind::T___BUILTIN_SCALBLN:
    case BuiltinFunctionKind::T___BUILTIN_SCALBLNL:
    case BuiltinFunctionKind::T___BUILTIN_SCALBNF:
    case BuiltinFunctionKind::T___BUILTIN_SCALBN:
    case BuiltinFunctionKind::T___BUILTIN_SCALBNL:
    case BuiltinFunctionKind::T___BUILTIN_SINF:
    case BuiltinFunctionKind::T___BUILTIN_SIN:
    case BuiltinFunctionKind::T___BUILTIN_SINL:
    case BuiltinFunctionKind::T___BUILTIN_SINCOSF:
    case BuiltinFunctionKind::T___BUILTIN_SINCOS:
    case BuiltinFunctionKind::T___BUILTIN_SINCOSL:
    case BuiltinFunctionKind::T___BUILTIN_SINHF:
    case BuiltinFunctionKind::T___BUILTIN_SINH:
    case BuiltinFunctionKind::T___BUILTIN_SINHL:
    case BuiltinFunctionKind::T___BUILTIN_SQRTF:
    case BuiltinFunctionKind::T___BUILTIN_SQRT:
    case BuiltinFunctionKind::T___BUILTIN_SQRTL:
    case BuiltinFunctionKind::T___BUILTIN_TANF:
    case BuiltinFunctionKind::T___BUILTIN_TAN:
    case BuiltinFunctionKind::T___BUILTIN_TANL:
    case BuiltinFunctionKind::T___BUILTIN_TANHF:
    case BuiltinFunctionKind::T___BUILTIN_TANH:
    case BuiltinFunctionKind::T___BUILTIN_TANHL:
    case BuiltinFunctionKind::T___BUILTIN_TGAMMAF:
    case BuiltinFunctionKind::T___BUILTIN_TGAMMA:
    case BuiltinFunctionKind::T___BUILTIN_TGAMMAL:
    case BuiltinFunctionKind::T___BUILTIN_TRUNCF:
    case BuiltinFunctionKind::T___BUILTIN_TRUNC:
    case BuiltinFunctionKind::T___BUILTIN_TRUNCL:
    case BuiltinFunctionKind::T___BUILTIN_BCMP:
    case BuiltinFunctionKind::T___BUILTIN_BZERO:
    case BuiltinFunctionKind::T___BUILTIN_BCOPY:
    case BuiltinFunctionKind::T___BUILTIN_INDEX:
    case BuiltinFunctionKind::T___BUILTIN_MEMCHR:
    case BuiltinFunctionKind::T___BUILTIN_MEMCMP:
    case BuiltinFunctionKind::T___BUILTIN_MEMCCPY:
    case BuiltinFunctionKind::T___BUILTIN_MEMPCPY:
    case BuiltinFunctionKind::T___BUILTIN_RINDEX:
    case BuiltinFunctionKind::T___BUILTIN_STPCPY:
    case BuiltinFunctionKind::T___BUILTIN_STPNCPY:
    case BuiltinFunctionKind::T___BUILTIN_STRCASECMP:
    case BuiltinFunctionKind::T___BUILTIN_STRCAT:
    case BuiltinFunctionKind::T___BUILTIN_STRCHR:
    case BuiltinFunctionKind::T___BUILTIN_STRCMP:
    case BuiltinFunctionKind::T___BUILTIN_STRCPY:
    case BuiltinFunctionKind::T___BUILTIN_STRDUP:
    case BuiltinFunctionKind::T___BUILTIN_STRERROR:
    case BuiltinFunctionKind::T___BUILTIN_STRLEN:
    case BuiltinFunctionKind::T___BUILTIN_STRNCAT:
    case BuiltinFunctionKind::T___BUILTIN_STRNCMP:
    case BuiltinFunctionKind::T___BUILTIN_STRNCPY:
    case BuiltinFunctionKind::T___BUILTIN_STRSPN:
    case BuiltinFunctionKind::T___BUILTIN_STRSTR:
    case BuiltinFunctionKind::T___BUILTIN_STRTOK:
    case BuiltinFunctionKind::T___BUILTIN_STRCSPN:
    case BuiltinFunctionKind::T___BUILTIN_STRLCAT:
    case BuiltinFunctionKind::T___BUILTIN_STRLCPY:
    case BuiltinFunctionKind::T___BUILTIN_STRNCASECMP:
    case BuiltinFunctionKind::T___BUILTIN_STRNDUP:
    case BuiltinFunctionKind::T___BUILTIN_STRPBRK:
    case BuiltinFunctionKind::T___BUILTIN_STRRCHR:
    case BuiltinFunctionKind::T___BUILTIN_STRXFRM:
      return true;

    default:
      return false;
  }
}

auto cxx::TypeChecker::Visitor::typeCheckBuiltinDispatch(
    cxx::CallExpressionAST* ast, cxx::BuiltinFunctionKind kind) -> bool {
  switch (kind) {
    case BuiltinFunctionKind::T___BUILTIN_VA_START:
      return checkBuiltinVaListAccess(ast);

    case BuiltinFunctionKind::T___BUILTIN_VA_END:
      return checkBuiltinVaListAccess(ast);

    case BuiltinFunctionKind::T___BUILTIN_VA_COPY:
      return checkBuiltinVaListAccess(ast);

    case BuiltinFunctionKind::T___BUILTIN_C23_VA_START:
      return checkBuiltinVaListAccess(ast);

    case BuiltinFunctionKind::T___C11_ATOMIC_INIT:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___C11_ATOMIC_STORE:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___C11_ATOMIC_LOAD:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___C11_ATOMIC_EXCHANGE:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___C11_ATOMIC_COMPARE_EXCHANGE_STRONG:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___C11_ATOMIC_COMPARE_EXCHANGE_WEAK:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___C11_ATOMIC_FETCH_ADD:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___C11_ATOMIC_FETCH_SUB:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___C11_ATOMIC_FETCH_OR:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___C11_ATOMIC_FETCH_AND:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___C11_ATOMIC_FETCH_XOR:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___C11_ATOMIC_FETCH_NAND:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_LOAD_N:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_LOAD:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_STORE_N:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_STORE:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_EXCHANGE_N:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_EXCHANGE:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_COMPARE_EXCHANGE_N:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_COMPARE_EXCHANGE:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_ADD_FETCH:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_SUB_FETCH:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_AND_FETCH:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_XOR_FETCH:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_OR_FETCH:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_NAND_FETCH:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_FETCH_ADD:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_FETCH_SUB:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_FETCH_AND:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_FETCH_XOR:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_FETCH_OR:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___ATOMIC_FETCH_NAND:
      return checkBuiltinAtomic(ast);

    case BuiltinFunctionKind::T___BUILTIN_ASSUME_ALIGNED:
      return checkBuiltinAssumeAligned(ast);

    case BuiltinFunctionKind::T___BUILTIN_OPERATOR_NEW:
      return checkBuiltinOperatorNew(ast);

    case BuiltinFunctionKind::T___BUILTIN_OPERATOR_DELETE:
      return checkBuiltinOperatorDelete(ast);

    case BuiltinFunctionKind::T___BUILTIN_INVOKE:
      return checkBuiltinInvoke(ast);

    case BuiltinFunctionKind::T___BUILTIN_ADDRESSOF:
      return checkBuiltinAddressof(ast);

    case BuiltinFunctionKind::T___BUILTIN_CTZG:
      return checkBuiltinCountZerosGeneric(ast);

    case BuiltinFunctionKind::T___BUILTIN_CLZG:
      return checkBuiltinCountZerosGeneric(ast);

    default:
      return false;
  }
}
