// Generated by gen_builtins_signatures_h.ts
// Copyright (c) 2026 Roberto Raggi <roberto.raggi@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

#include <cxx/builtin_signature.h>
#include <cxx/control.h>

namespace cxx {

enum class BuiltinTypeOp : std::uint8_t {
  kEnd,
  kVariadic,
  kPointer,
  kLvalueReference,
  kRvalueReference,
  kConst,
  kVolatile,
  kComplex,
  kVoid,
  kBool,
  kChar,
  kSignedChar,
  kUnsignedChar,
  kShortInt,
  kUnsignedShortInt,
  kInt,
  kUnsignedInt,
  kLongInt,
  kUnsignedLongInt,
  kLongLongInt,
  kUnsignedLongLongInt,
  kInt128,
  kUnsignedInt128,
  kFloat,
  kDouble,
  kLongDouble,
  kFloat16,
  kWideChar,
  kChar8,
  kChar16,
  kChar32,
  kNullptr,
  kSizeType,
  kBuiltinVaList,
};

[[nodiscard]] inline auto decodeBuiltinLeafType(Control* control,
                                                BuiltinTypeOp op)
    -> const Type* {
  switch (op) {
    case BuiltinTypeOp::kVoid:
      return control->getVoidType();
    case BuiltinTypeOp::kBool:
      return control->getBoolType();
    case BuiltinTypeOp::kChar:
      return control->getCharType();
    case BuiltinTypeOp::kSignedChar:
      return control->getSignedCharType();
    case BuiltinTypeOp::kUnsignedChar:
      return control->getUnsignedCharType();
    case BuiltinTypeOp::kShortInt:
      return control->getShortIntType();
    case BuiltinTypeOp::kUnsignedShortInt:
      return control->getUnsignedShortIntType();
    case BuiltinTypeOp::kInt:
      return control->getIntType();
    case BuiltinTypeOp::kUnsignedInt:
      return control->getUnsignedIntType();
    case BuiltinTypeOp::kLongInt:
      return control->getLongIntType();
    case BuiltinTypeOp::kUnsignedLongInt:
      return control->getUnsignedLongIntType();
    case BuiltinTypeOp::kLongLongInt:
      return control->getLongLongIntType();
    case BuiltinTypeOp::kUnsignedLongLongInt:
      return control->getUnsignedLongLongIntType();
    case BuiltinTypeOp::kInt128:
      return control->getInt128Type();
    case BuiltinTypeOp::kUnsignedInt128:
      return control->getUnsignedInt128Type();
    case BuiltinTypeOp::kFloat:
      return control->getFloatType();
    case BuiltinTypeOp::kDouble:
      return control->getDoubleType();
    case BuiltinTypeOp::kLongDouble:
      return control->getLongDoubleType();
    case BuiltinTypeOp::kFloat16:
      return control->getFloat16Type();
    case BuiltinTypeOp::kWideChar:
      return control->getWideCharType();
    case BuiltinTypeOp::kChar8:
      return control->getChar8Type();
    case BuiltinTypeOp::kChar16:
      return control->getChar16Type();
    case BuiltinTypeOp::kChar32:
      return control->getChar32Type();
    case BuiltinTypeOp::kNullptr:
      return control->getNullptrType();
    case BuiltinTypeOp::kSizeType:
      return control->getSizeType();
    case BuiltinTypeOp::kBuiltinVaList:
      return control->getBuiltinVaListType();
    default:
      return nullptr;
  }
}

inline constexpr std::uint8_t kBuiltinSignatureOps[] = {
    19, 2,  6,  8,  19, 15, 0,  9,  32, 2,  5,  6,  8,  0,  19, 2,  6,  8,  19,
    15, 0,  8,  2,  6,  8,  15, 0,  9,  2,  6,  8,  2,  8,  2,  8,  9,  15, 15,
    0,  9,  2,  6,  8,  2,  8,  19, 9,  15, 15, 0,  8,  2,  6,  8,  2,  8,  2,
    8,  15, 0,  19, 2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,  19, 2,
    6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,
    19, 2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,  9,  32, 2,  5,  6,
    8,  0,  8,  2,  5,  6,  8,  2,  8,  15, 0,  19, 2,  5,  6,  8,  15, 0,  19,
    2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,  8,  15, 0,  8,  2,  6,
    8,  2,  8,  15, 0,  8,  2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,
    9,  2,  6,  8,  15, 0,  8,  15, 0,  19, 2,  6,  8,  19, 15, 0,  16, 0,  2,
    5,  10, 0,  2,  5,  10, 0,  16, 0,  8,  15, 0,  24, 24, 0,  23, 23, 0,  24,
    24, 0,  23, 23, 0,  15, 24, 0,  15, 23, 0,  15, 25, 0,  24, 24, 0,  23, 23,
    0,  24, 24, 0,  23, 23, 0,  8,  0,  15, 15, 0,  24, 24, 0,  23, 23, 0,  24,
    24, 0,  23, 23, 0,  25, 25, 0,  25, 25, 0,  9,  1,  0,  2,  8,  1,  0,  2,
    8,  32, 32, 0,  2,  8,  32, 0,  24, 24, 0,  23, 23, 0,  24, 24, 0,  23, 23,
    0,  25, 25, 0,  25, 25, 0,  2,  8,  2,  5,  8,  32, 1,  0,  24, 24, 0,  24,
    24, 24, 0,  23, 23, 23, 0,  25, 25, 25, 0,  23, 23, 0,  24, 24, 0,  23, 23,
    0,  25, 25, 0,  25, 25, 0,  15, 2,  5,  8,  2,  5,  8,  32, 0,  8,  2,  5,
    8,  2,  8,  32, 0,  14, 14, 0,  16, 16, 0,  20, 20, 0,  8,  2,  8,  32, 0,
    8,  3,  33, 1,  0,  24, 7,  24, 0,  23, 7,  23, 0,  25, 7,  25, 0,  7,  24,
    7,  24, 0,  7,  23, 7,  23, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23, 0,  7,
    25, 7,  25, 0,  7,  25, 7,  25, 0,  24, 7,  24, 0,  23, 7,  23, 0,  25, 7,
    25, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23, 0,  7,  24, 7,  24, 0,  7,  23,
    7,  23, 0,  7,  25, 7,  25, 0,  7,  25, 7,  25, 0,  7,  24, 7,  24, 0,  7,
    23, 7,  23, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23, 0,  7,  25, 7,  25, 0,
    7,  25, 7,  25, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  7,  24, 7,  24, 0,
    7,  23, 7,  23, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23, 0,  7,  25, 7,  25,
    0,  7,  25, 7,  25, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  7,  24, 7,  24,
    0,  7,  23, 7,  23, 0,  7,  25, 7,  25, 0,  24, 7,  24, 0,  23, 7,  23, 0,
    25, 7,  25, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23, 0,  7,  25, 7,  25, 0,
    15, 15, 0,  15, 17, 0,  15, 19, 0,  15, 16, 0,  15, 12, 0,  15, 14, 0,  15,
    16, 0,  15, 18, 0,  15, 20, 0,  15, 22, 0,  15, 12, 15, 0,  15, 14, 15, 0,
    15, 16, 15, 0,  15, 18, 15, 0,  15, 20, 15, 0,  15, 22, 15, 0,  15, 18, 0,
    15, 20, 0,  15, 14, 0,  7,  23, 23, 23, 0,  7,  24, 24, 24, 0,  7,  25, 25,
    25, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23, 0,  7,  25, 7,  25, 0,  15, 1,
    0,  24, 24, 24, 0,  23, 23, 23, 0,  25, 25, 25, 0,  8,  2,  8,  0,  9,  2,
    8,  0,  2,  8,  2,  8,  15, 9,  0,  8,  2,  8,  0,  24, 24, 0,  23, 23, 0,
    24, 24, 0,  23, 23, 0,  25, 25, 0,  25, 25, 0,  7,  24, 7,  24, 7,  24, 0,
    7,  23, 7,  23, 7,  23, 0,  7,  25, 7,  25, 7,  25, 0,  7,  24, 7,  24, 0,
    7,  23, 7,  23, 0,  7,  25, 7,  25, 0,  24, 7,  24, 0,  23, 7,  23, 0,  25,
    7,  25, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23, 0,  7,  24, 7,  24, 0,  7,
    23, 7,  23, 0,  7,  25, 7,  25, 0,  7,  25, 7,  25, 0,  7,  24, 7,  24, 0,
    7,  23, 7,  23, 0,  7,  25, 7,  25, 0,  7,  24, 7,  24, 0,  7,  23, 7,  23,
    0,  7,  24, 7,  24, 0,  7,  23, 7,  23, 0,  7,  25, 7,  25, 0,  7,  25, 7,
    25, 0,  15, 16, 0,  15, 12, 0,  15, 14, 0,  15, 16, 0,  15, 18, 0,  15, 20,
    0,  15, 22, 0,  15, 12, 15, 0,  15, 14, 15, 0,  15, 16, 15, 0,  15, 18, 15,
    0,  15, 20, 15, 0,  15, 22, 15, 0,  15, 18, 0,  15, 20, 0,  15, 14, 0,  24,
    24, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  23, 23, 0,  25, 25, 0,  8,  15,
    0,  24, 24, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  17, 17, 17, 0,  23, 23,
    0,  25, 25, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  24, 24, 0,  23, 23, 0,
    25, 25, 0,  24, 24, 24, 0,  23, 23, 23, 0,  25, 25, 25, 0,  15, 15, 0,  15,
    17, 0,  15, 19, 0,  15, 24, 0,  15, 23, 0,  15, 25, 0,  24, 24, 0,  23, 23,
    0,  25, 25, 0,  24, 24, 24, 24, 0,  23, 23, 23, 23, 0,  25, 25, 25, 25, 0,
    24, 24, 24, 0,  23, 23, 23, 0,  24, 24, 24, 0,  23, 23, 23, 0,  25, 25, 25,
    0,  25, 25, 25, 0,  24, 24, 24, 0,  23, 23, 23, 0,  24, 24, 24, 0,  23, 23,
    23, 0,  25, 25, 25, 0,  25, 25, 25, 0,  24, 24, 24, 0,  23, 23, 23, 0,  25,
    25, 25, 0,  15, 15, 15, 15, 15, 15, 1,  0,  24, 24, 2,  15, 0,  23, 23, 2,
    15, 0,  25, 25, 2,  15, 0,  24, 0,  23, 0,  25, 0,  24, 24, 24, 0,  23, 23,
    23, 0,  25, 25, 25, 0,  15, 24, 0,  15, 23, 0,  15, 25, 0,  2,  10, 2,  5,
    10, 15, 0,  24, 0,  23, 0,  25, 0,  2,  8,  1,  0,  9,  0,  15, 15, 0,  15,
    15, 0,  15, 15, 0,  15, 15, 0,  15, 15, 0,  9,  23, 0,  9,  24, 0,  9,  25,
    0,  15, 15, 0,  9,  1,  0,  9,  1,  0,  9,  23, 0,  9,  24, 0,  9,  25, 0,
    9,  1,  0,  9,  1,  0,  9,  1,  0,  15, 15, 0,  9,  23, 0,  9,  24, 0,  9,
    25, 0,  9,  23, 0,  9,  24, 0,  9,  25, 0,  15, 15, 0,  15, 15, 0,  15, 15,
    0,  9,  1,  0,  15, 15, 0,  15, 15, 0,  17, 17, 0,  24, 24, 15, 0,  23, 23,
    15, 0,  25, 25, 15, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  19, 19, 0,  19,
    24, 0,  19, 23, 0,  19, 25, 0,  19, 24, 0,  19, 23, 0,  19, 25, 0,  24, 24,
    0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,
    24, 24, 0,  23, 23, 0,  25, 25, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  23,
    23, 0,  25, 25, 0,  17, 24, 0,  17, 23, 0,  17, 25, 0,  17, 24, 0,  17, 23,
    0,  17, 25, 0,  2,  8,  2,  8,  2,  5,  8,  15, 32, 0,  2,  8,  2,  5,  8,
    15, 32, 0,  15, 2,  5,  8,  2,  5,  8,  32, 0,  2,  8,  2,  8,  2,  5,  8,
    32, 0,  2,  8,  2,  8,  2,  5,  8,  32, 0,  2,  8,  2,  8,  2,  5,  8,  32,
    0,  2,  8,  2,  8,  15, 32, 0,  24, 24, 2,  24, 0,  23, 23, 2,  23, 0,  25,
    25, 2,  25, 0,  9,  1,  0,  24, 2,  5,  10, 0,  23, 2,  5,  10, 0,  25, 2,
    5,  10, 0,  24, 2,  5,  10, 0,  23, 2,  5,  10, 0,  25, 2,  5,  10, 0,  24,
    24, 0,  23, 23, 0,  25, 25, 0,  24, 24, 24, 0,  23, 23, 23, 0,  25, 25, 25,
    0,  24, 24, 25, 0,  23, 23, 25, 0,  25, 25, 25, 0,  8,  2,  8,  1,  0,  2,
    8,  32, 1,  0,  15, 16, 0,  15, 18, 0,  15, 20, 0,  15, 16, 0,  15, 12, 0,
    15, 14, 0,  15, 16, 0,  15, 18, 0,  15, 20, 0,  15, 22, 0,  15, 18, 0,  15,
    20, 0,  24, 24, 24, 0,  23, 23, 23, 0,  25, 25, 25, 0,  24, 24, 24, 0,  23,
    23, 23, 0,  25, 25, 25, 0,  24, 24, 24, 2,  15, 0,  23, 23, 23, 2,  15, 0,
    25, 25, 25, 2,  15, 0,  2,  10, 2,  5,  10, 15, 0,  24, 24, 0,  23, 23, 0,
    25, 25, 0,  24, 24, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  23, 23, 0,  25,
    25, 0,  24, 24, 17, 0,  23, 23, 17, 0,  25, 25, 17, 0,  24, 24, 15, 0,  23,
    23, 15, 0,  25, 25, 15, 0,  9,  23, 0,  9,  24, 0,  9,  25, 0,  24, 24, 0,
    8,  24, 2,  24, 2,  24, 0,  8,  23, 2,  23, 2,  23, 0,  8,  25, 2,  25, 2,
    25, 0,  23, 23, 0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  25, 25, 0,  2,  5,
    8,  0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  2,  10, 2,  10, 2,  5,  10, 0,
    2,  10, 2,  10, 2,  5,  10, 32, 0,  15, 2,  5,  10, 2,  5,  10, 0,  2,  10,
    2,  10, 2,  5,  10, 0,  2,  10, 2,  5,  10, 15, 0,  15, 2,  5,  10, 2,  5,
    10, 0,  2,  10, 2,  10, 2,  5,  10, 0,  32, 2,  5,  10, 2,  5,  10, 0,  2,
    10, 2,  5,  10, 0,  2,  10, 15, 0,  32, 2,  10, 2,  5,  10, 32, 0,  32, 2,
    10, 2,  5,  10, 32, 0,  32, 2,  5,  10, 0,  15, 2,  5,  10, 2,  5,  10, 32,
    0,  2,  10, 2,  10, 2,  5,  10, 32, 0,  15, 2,  5,  10, 2,  5,  10, 32, 0,
    2,  10, 2,  10, 2,  5,  10, 32, 0,  2,  10, 2,  5,  10, 32, 0,  2,  10, 2,
    5,  10, 2,  5,  10, 0,  2,  10, 2,  5,  10, 15, 0,  32, 2,  5,  10, 2,  5,
    10, 0,  2,  10, 2,  5,  10, 2,  5,  10, 0,  24, 2,  5,  10, 2,  2,  10, 0,
    23, 2,  5,  10, 2,  2,  10, 0,  2,  10, 2,  10, 2,  5,  10, 0,  17, 2,  5,
    10, 2,  2,  10, 15, 0,  25, 2,  5,  10, 2,  2,  10, 0,  19, 2,  5,  10, 2,
    2,  10, 15, 0,  18, 2,  5,  10, 2,  2,  10, 15, 0,  20, 2,  5,  10, 2,  2,
    10, 15, 0,  32, 2,  10, 2,  5,  10, 32, 0,  9,  1,  0,  24, 24, 0,  23, 23,
    0,  24, 24, 0,  23, 23, 0,  25, 25, 0,  25, 25, 0,  24, 24, 0,  23, 23, 0,
    25, 25, 0,  15, 15, 0,  15, 15, 0,  8,  0,  24, 24, 0,  23, 23, 0,  25, 25,
    0,  8,  0,  8,  3,  33, 3,  33, 0,  8,  3,  33, 0,  8,  3,  33, 1,  0,  15,
    2,  10, 32, 2,  5,  10, 3,  33, 0,  2,  27, 2,  5,  27, 27, 0,  15, 2,  5,
    27, 2,  5,  27, 0,  32, 2,  5,  27, 0,  15, 2,  5,  27, 2,  5,  27, 32, 0,
    2,  27, 2,  5,  27, 27, 32, 0,  15, 2,  5,  27, 2,  5,  27, 32, 0,  2,  27,
    2,  27, 2,  5,  27, 32, 0,  2,  27, 2,  27, 2,  5,  27, 32, 0,  15, 2,  6,
    8,  2,  8,  19, 15, 15, 0,  15, 2,  6,  8,  2,  8,  19, 15, 15, 0,  19, 2,
    6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,
    19, 2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19, 15, 0,  19, 2,  6,  8,  19,
    15, 0,  19, 2,  6,  8,  19, 15, 0,  8,  2,  6,  8,  19, 0,  9,  32, 0,  19,
    2,  6,  8,  15, 0,  8,  15, 0,  8,  2,  6,  8,  19, 15, 0,  8,  15, 0,
};

inline constexpr BuiltinSignature kBuiltinSignatures[] = {
    {},
    {0, 1, BuiltinFlags::kNone},  // __atomic_add_fetch
    {7, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},     // __atomic_always_lock_free
    {14, 1, BuiltinFlags::kNone},      // __atomic_and_fetch
    {21, 1, BuiltinFlags::kNoexcept},  // __atomic_clear
    {27, 1, BuiltinFlags::kNone},      // __atomic_compare_exchange
    {39, 1, BuiltinFlags::kNone},      // __atomic_compare_exchange_n
    {50, 1, BuiltinFlags::kNone},      // __atomic_exchange
    {60, 1, BuiltinFlags::kNone},      // __atomic_exchange_n
    {67, 1, BuiltinFlags::kNone},      // __atomic_fetch_add
    {74, 1, BuiltinFlags::kNone},      // __atomic_fetch_and
    {81, 1, BuiltinFlags::kNone},      // __atomic_fetch_nand
    {88, 1, BuiltinFlags::kNone},      // __atomic_fetch_or
    {95, 1, BuiltinFlags::kNone},      // __atomic_fetch_sub
    {102, 1, BuiltinFlags::kNone},     // __atomic_fetch_xor
    {109, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},      // __atomic_is_lock_free
    {116, 1, BuiltinFlags::kNone},      // __atomic_load
    {125, 1, BuiltinFlags::kNone},      // __atomic_load_n
    {132, 1, BuiltinFlags::kNone},      // __atomic_nand_fetch
    {139, 1, BuiltinFlags::kNone},      // __atomic_or_fetch
    {146, 1, BuiltinFlags::kNoexcept},  // __atomic_signal_fence
    {149, 1, BuiltinFlags::kNone},      // __atomic_store
    {157, 1, BuiltinFlags::kNone},      // __atomic_store_n
    {164, 1, BuiltinFlags::kNone},      // __atomic_sub_fetch
    {171, 1, BuiltinFlags::kNoexcept},  // __atomic_test_and_set
    {177, 1, BuiltinFlags::kNoexcept},  // __atomic_thread_fence
    {180, 1, BuiltinFlags::kNone},      // __atomic_xor_fetch
    {187, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kConsteval |
         BuiltinFlags::kNoexcept},  // __builtin_COLUMN
    {189, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kConsteval |
         BuiltinFlags::kNoexcept},  // __builtin_FILE
    {193, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kConsteval |
         BuiltinFlags::kNoexcept},  // __builtin_FUNCTION
    {197, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kConsteval |
         BuiltinFlags::kNoexcept},      // __builtin_LINE
    {199, 1, BuiltinFlags::kNoReturn},  // __builtin__Exit
    {202, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___cospi
    {205, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___cospif
    {208, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___exp10
    {211, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___exp10f
    {214, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___finite
    {217, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin___finitef
    {220, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin___finitel
    {223, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___sinpi
    {226, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___sinpif
    {229, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___tanpi
    {232, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin___tanpif
    {235, 1,
     BuiltinFlags::kNoexcept | BuiltinFlags::kNoReturn},  // __builtin_abort
    {237, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_abs
    {240, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_acos
    {243, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_acosf
    {246, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_acosh
    {249, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_acoshf
    {252, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_acoshl
    {255, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_acosl
    {258, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_add_overflow
    {261, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},      // __builtin_addressof
    {265, 1, BuiltinFlags::kNone},      // __builtin_aligned_alloc
    {270, 1, BuiltinFlags::kNoexcept},  // __builtin_alloca
    {274, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_asin
    {277, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_asinf
    {280, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_asinh
    {283, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_asinhf
    {286, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_asinhl
    {289, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_asinl
    {292, 1, BuiltinFlags::kNoexcept},  // __builtin_assume_aligned
    {300, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atan
    {303, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atan2
    {307, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atan2f
    {311, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atan2l
    {315, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atanf
    {318, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atanh
    {321, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atanhf
    {324, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atanhl
    {327, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_atanl
    {330, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_bcmp
    {339, 1, BuiltinFlags::kNoexcept},                     // __builtin_bcopy
    {347, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_bswap16
    {350, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_bswap32
    {353, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_bswap64
    {356, 1, BuiltinFlags::kNoexcept},                     // __builtin_bzero
    {361, 1, BuiltinFlags::kNoexcept},  // __builtin_c23_va_start
    {366, 1, BuiltinFlags::kNoexcept},  // __builtin_cabs
    {370, 1, BuiltinFlags::kNoexcept},  // __builtin_cabsf
    {374, 1, BuiltinFlags::kNoexcept},  // __builtin_cabsl
    {378, 1, BuiltinFlags::kNoexcept},  // __builtin_cacos
    {383, 1, BuiltinFlags::kNoexcept},  // __builtin_cacosf
    {388, 1, BuiltinFlags::kNoexcept},  // __builtin_cacosh
    {393, 1, BuiltinFlags::kNoexcept},  // __builtin_cacoshf
    {398, 1, BuiltinFlags::kNoexcept},  // __builtin_cacoshl
    {403, 1, BuiltinFlags::kNoexcept},  // __builtin_cacosl
    {408, 1, BuiltinFlags::kNoexcept},  // __builtin_carg
    {412, 1, BuiltinFlags::kNoexcept},  // __builtin_cargf
    {416, 1, BuiltinFlags::kNoexcept},  // __builtin_cargl
    {420, 1, BuiltinFlags::kNoexcept},  // __builtin_casin
    {425, 1, BuiltinFlags::kNoexcept},  // __builtin_casinf
    {430, 1, BuiltinFlags::kNoexcept},  // __builtin_casinh
    {435, 1, BuiltinFlags::kNoexcept},  // __builtin_casinhf
    {440, 1, BuiltinFlags::kNoexcept},  // __builtin_casinhl
    {445, 1, BuiltinFlags::kNoexcept},  // __builtin_casinl
    {450, 1, BuiltinFlags::kNoexcept},  // __builtin_catan
    {455, 1, BuiltinFlags::kNoexcept},  // __builtin_catanf
    {460, 1, BuiltinFlags::kNoexcept},  // __builtin_catanh
    {465, 1, BuiltinFlags::kNoexcept},  // __builtin_catanhf
    {470, 1, BuiltinFlags::kNoexcept},  // __builtin_catanhl
    {475, 1, BuiltinFlags::kNoexcept},  // __builtin_catanl
    {480, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_cbrt
    {483, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_cbrtf
    {486, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_cbrtl
    {489, 1, BuiltinFlags::kNoexcept},                     // __builtin_ccos
    {494, 1, BuiltinFlags::kNoexcept},                     // __builtin_ccosf
    {499, 1, BuiltinFlags::kNoexcept},                     // __builtin_ccosh
    {504, 1, BuiltinFlags::kNoexcept},                     // __builtin_ccoshf
    {509, 1, BuiltinFlags::kNoexcept},                     // __builtin_ccoshl
    {514, 1, BuiltinFlags::kNoexcept},                     // __builtin_ccosl
    {519, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ceil
    {522, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ceilf
    {525, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ceill
    {528, 1, BuiltinFlags::kNoexcept},                     // __builtin_cexp
    {533, 1, BuiltinFlags::kNoexcept},                     // __builtin_cexpf
    {538, 1, BuiltinFlags::kNoexcept},                     // __builtin_cexpl
    {543, 1, BuiltinFlags::kNoexcept},                     // __builtin_cimag
    {547, 1, BuiltinFlags::kNoexcept},                     // __builtin_cimagf
    {551, 1, BuiltinFlags::kNoexcept},                     // __builtin_cimagl
    {555, 1, BuiltinFlags::kNoexcept},                     // __builtin_clog
    {560, 1, BuiltinFlags::kNoexcept},                     // __builtin_clogf
    {565, 1, BuiltinFlags::kNoexcept},                     // __builtin_clogl
    {570, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_clrsb
    {573, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_clrsbl
    {576, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_clrsbll
    {579, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_clz
    {582, 12,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_clzg
    {624, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_clzl
    {627, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_clzll
    {630, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_clzs
    {633, 3,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_complex
    {648, 1, BuiltinFlags::kNoexcept},                     // __builtin_conj
    {653, 1, BuiltinFlags::kNoexcept},                     // __builtin_conjf
    {658, 1, BuiltinFlags::kNoexcept},                     // __builtin_conjl
    {663, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_constant_p
    {666, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_copysign
    {670, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_copysignf
    {674, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},      // __builtin_copysignl
    {678, 1, BuiltinFlags::kNone},      // __builtin_coro_destroy
    {682, 1, BuiltinFlags::kNoexcept},  // __builtin_coro_done
    {686, 1, BuiltinFlags::kNoexcept},  // __builtin_coro_promise
    {693, 1, BuiltinFlags::kNone},      // __builtin_coro_resume
    {697, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_cos
    {700, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_cosf
    {703, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_cosh
    {706, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_coshf
    {709, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_coshl
    {712, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_cosl
    {715, 1, BuiltinFlags::kNoexcept},                     // __builtin_cpow
    {722, 1, BuiltinFlags::kNoexcept},                     // __builtin_cpowf
    {729, 1, BuiltinFlags::kNoexcept},                     // __builtin_cpowl
    {736, 1, BuiltinFlags::kNoexcept},                     // __builtin_cproj
    {741, 1, BuiltinFlags::kNoexcept},                     // __builtin_cprojf
    {746, 1, BuiltinFlags::kNoexcept},                     // __builtin_cprojl
    {751, 1, BuiltinFlags::kNoexcept},                     // __builtin_creal
    {755, 1, BuiltinFlags::kNoexcept},                     // __builtin_crealf
    {759, 1, BuiltinFlags::kNoexcept},                     // __builtin_creall
    {763, 1, BuiltinFlags::kNoexcept},                     // __builtin_csin
    {768, 1, BuiltinFlags::kNoexcept},                     // __builtin_csinf
    {773, 1, BuiltinFlags::kNoexcept},                     // __builtin_csinh
    {778, 1, BuiltinFlags::kNoexcept},                     // __builtin_csinhf
    {783, 1, BuiltinFlags::kNoexcept},                     // __builtin_csinhl
    {788, 1, BuiltinFlags::kNoexcept},                     // __builtin_csinl
    {793, 1, BuiltinFlags::kNoexcept},                     // __builtin_csqrt
    {798, 1, BuiltinFlags::kNoexcept},                     // __builtin_csqrtf
    {803, 1, BuiltinFlags::kNoexcept},                     // __builtin_csqrtl
    {808, 1, BuiltinFlags::kNoexcept},                     // __builtin_ctan
    {813, 1, BuiltinFlags::kNoexcept},                     // __builtin_ctanf
    {818, 1, BuiltinFlags::kNoexcept},                     // __builtin_ctanh
    {823, 1, BuiltinFlags::kNoexcept},                     // __builtin_ctanhf
    {828, 1, BuiltinFlags::kNoexcept},                     // __builtin_ctanhl
    {833, 1, BuiltinFlags::kNoexcept},                     // __builtin_ctanl
    {838, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ctz
    {841, 12,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ctzg
    {883, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ctzl
    {886, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ctzll
    {889, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ctzs
    {892, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_erf
    {895, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_erfc
    {898, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_erfcf
    {901, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_erfcl
    {904, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_erff
    {907, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_erfl
    {910, 1, BuiltinFlags::kNoReturn},                     // __builtin_exit
    {913, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_exp
    {916, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_exp2
    {919, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_exp2f
    {922, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_exp2l
    {925, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_expect
    {929, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_expf
    {932, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_expl
    {935, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_expm1
    {938, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_expm1f
    {941, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_expm1l
    {944, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fabs
    {947, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fabsf
    {950, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fabsl
    {953, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fdim
    {957, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fdimf
    {961, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fdiml
    {965, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ffs
    {968, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ffsl
    {971, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ffsll
    {974, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_finite
    {977, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_finitef
    {980, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_finitel
    {983, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_floor
    {986, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_floorf
    {989, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_floorl
    {992, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fma
    {997, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmaf
    {1002, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmal
    {1007, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmax
    {1011, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmaxf
    {1015, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_fmaximum_num
    {1019, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_fmaximum_numf
    {1023, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_fmaximum_numl
    {1027, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmaxl
    {1031, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmin
    {1035, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fminf
    {1039, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_fminimum_num
    {1043, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_fminimum_numf
    {1047, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_fminimum_numl
    {1051, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fminl
    {1055, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmod
    {1059, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmodf
    {1063, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_fmodl
    {1067, 1, BuiltinFlags::kNoexcept},  // __builtin_fpclassify
    {1075, 1, BuiltinFlags::kNoexcept},  // __builtin_frexp
    {1080, 1, BuiltinFlags::kNoexcept},  // __builtin_frexpf
    {1085, 1, BuiltinFlags::kNoexcept},  // __builtin_frexpl
    {1090, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_huge_val
    {1092, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_huge_valf
    {1094, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_huge_vall
    {1096, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_hypot
    {1100, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_hypotf
    {1104, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_hypotl
    {1108, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ilogb
    {1111, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ilogbf
    {1114, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ilogbl
    {1117, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_index
    {1124, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_inf
    {1126, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_inff
    {1128, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_infl
    {1130, 1, BuiltinFlags::kNone},                        // __builtin_invoke
    {1134, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},       // __builtin_is_constant_evaluated
    {1136, 1, BuiltinFlags::kNoexcept},  // __builtin_isalnum
    {1139, 1, BuiltinFlags::kNoexcept},  // __builtin_isalpha
    {1142, 1, BuiltinFlags::kNoexcept},  // __builtin_isblank
    {1145, 1, BuiltinFlags::kNoexcept},  // __builtin_iscntrl
    {1148, 1, BuiltinFlags::kNoexcept},  // __builtin_isdigit
    {1151, 3,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_isfinite
    {1160, 1, BuiltinFlags::kNoexcept},                    // __builtin_isgraph
    {1163, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_isgreater
    {1166, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_isgreaterequal
    {1169, 3,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_isinf
    {1178, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_isless
    {1181, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_islessequal
    {1184, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},       // __builtin_islessgreater
    {1187, 1, BuiltinFlags::kNoexcept},  // __builtin_islower
    {1190, 3,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_isnan
    {1199, 3, BuiltinFlags::kNoexcept},                    // __builtin_isnormal
    {1208, 1, BuiltinFlags::kNoexcept},                    // __builtin_isprint
    {1211, 1, BuiltinFlags::kNoexcept},                    // __builtin_ispunct
    {1214, 1, BuiltinFlags::kNoexcept},                    // __builtin_isspace
    {1217, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},       // __builtin_isunordered
    {1220, 1, BuiltinFlags::kNoexcept},  // __builtin_isupper
    {1223, 1, BuiltinFlags::kNoexcept},  // __builtin_isxdigit
    {1226, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_labs
    {1229, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ldexp
    {1233, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ldexpf
    {1237, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_ldexpl
    {1241, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lgamma
    {1244, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lgammaf
    {1247, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lgammal
    {1250, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_llabs
    {1253, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_llrint
    {1256, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_llrintf
    {1259, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_llrintl
    {1262, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_llround
    {1265, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_llroundf
    {1268, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_llroundl
    {1271, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log
    {1274, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log10
    {1277, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log10f
    {1280, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log10l
    {1283, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log1p
    {1286, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log1pf
    {1289, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log1pl
    {1292, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log2
    {1295, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log2f
    {1298, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_log2l
    {1301, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_logb
    {1304, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_logbf
    {1307, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_logbl
    {1310, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_logf
    {1313, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_logl
    {1316, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lrint
    {1319, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lrintf
    {1322, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lrintl
    {1325, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lround
    {1328, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lroundf
    {1331, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_lroundl
    {1334, 1, BuiltinFlags::kNone},                        // __builtin_memccpy
    {1344, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_memchr
    {1352, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_memcmp
    {1361, 1, BuiltinFlags::kNoexcept},                    // __builtin_memcpy
    {1370, 1, BuiltinFlags::kNoexcept},                    // __builtin_memmove
    {1379, 1, BuiltinFlags::kNoexcept},                    // __builtin_mempcpy
    {1388, 1, BuiltinFlags::kNoexcept},                    // __builtin_memset
    {1395, 1, BuiltinFlags::kNoexcept},                    // __builtin_modf
    {1400, 1, BuiltinFlags::kNoexcept},                    // __builtin_modff
    {1405, 1, BuiltinFlags::kNoexcept},                    // __builtin_modfl
    {1410, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_mul_overflow
    {1413, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_nan
    {1418, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_nanf
    {1423, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_nanl
    {1428, 1, BuiltinFlags::kNoexcept},                    // __builtin_nans
    {1433, 1, BuiltinFlags::kNoexcept},                    // __builtin_nansf
    {1438, 1, BuiltinFlags::kNoexcept},                    // __builtin_nansl
    {1443, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nearbyint
    {1446, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nearbyintf
    {1449, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nearbyintl
    {1452, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nextafter
    {1456, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nextafterf
    {1460, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nextafterl
    {1464, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nexttoward
    {1468, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_nexttowardf
    {1472, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},       // __builtin_nexttowardl
    {1476, 1, BuiltinFlags::kNoexcept},  // __builtin_operator_delete
    {1481, 1, BuiltinFlags::kNone},      // __builtin_operator_new
    {1486, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_parity
    {1489, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_parityl
    {1492, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_parityll
    {1495, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_popcount
    {1498, 6,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_popcountg
    {1516, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_popcountl
    {1519, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_popcountll
    {1522, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_pow
    {1526, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_powf
    {1530, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_powl
    {1534, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_remainder
    {1538, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_remainderf
    {1542, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},       // __builtin_remainderl
    {1546, 1, BuiltinFlags::kNoexcept},  // __builtin_remquo
    {1552, 1, BuiltinFlags::kNoexcept},  // __builtin_remquof
    {1558, 1, BuiltinFlags::kNoexcept},  // __builtin_remquol
    {1564, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_rindex
    {1571, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_rint
    {1574, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_rintf
    {1577, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_rintl
    {1580, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_round
    {1583, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_roundeven
    {1586, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_roundevenf
    {1589, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_roundevenl
    {1592, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_roundf
    {1595, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_roundl
    {1598, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_scalbln
    {1602, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_scalblnf
    {1606, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_scalblnl
    {1610, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_scalbn
    {1614, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_scalbnf
    {1618, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_scalbnl
    {1622, 3,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_signbit
    {1631, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sin
    {1634, 1, BuiltinFlags::kNoexcept},                    // __builtin_sincos
    {1641, 1, BuiltinFlags::kNoexcept},                    // __builtin_sincosf
    {1648, 1, BuiltinFlags::kNoexcept},                    // __builtin_sincosl
    {1655, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sinf
    {1658, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sinh
    {1661, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sinhf
    {1664, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sinhl
    {1667, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sinl
    {1670, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kConsteval |
         BuiltinFlags::kNoexcept},  // __builtin_source_location
    {1674, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sqrt
    {1677, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sqrtf
    {1680, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_sqrtl
    {1683, 1, BuiltinFlags::kNoexcept},                    // __builtin_stpcpy
    {1691, 1, BuiltinFlags::kNoexcept},                    // __builtin_stpncpy
    {1700, 1, BuiltinFlags::kConstexpr},  // __builtin_strcasecmp
    {1708, 1, BuiltinFlags::kNoexcept},   // __builtin_strcat
    {1716, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strchr
    {1723, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strcmp
    {1731, 1, BuiltinFlags::kNoexcept},                    // __builtin_strcpy
    {1739, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strcspn
    {1747, 1, BuiltinFlags::kNoexcept},                    // __builtin_strdup
    {1753, 1, BuiltinFlags::kNone},                        // __builtin_strerror
    {1757, 1, BuiltinFlags::kNone},                        // __builtin_strlcat
    {1765, 1, BuiltinFlags::kNone},                        // __builtin_strlcpy
    {1773, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strlen
    {1778, 1, BuiltinFlags::kConstexpr},  // __builtin_strncasecmp
    {1787, 1, BuiltinFlags::kNoexcept},   // __builtin_strncat
    {1796, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strncmp
    {1805, 1, BuiltinFlags::kNoexcept},                    // __builtin_strncpy
    {1814, 1, BuiltinFlags::kNoexcept},                    // __builtin_strndup
    {1821, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strpbrk
    {1830, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strrchr
    {1837, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strspn
    {1845, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_strstr
    {1854, 1, BuiltinFlags::kNone},                        // __builtin_strtod
    {1862, 1, BuiltinFlags::kNone},                        // __builtin_strtof
    {1870, 1, BuiltinFlags::kNone},                        // __builtin_strtok
    {1878, 1, BuiltinFlags::kNone},                        // __builtin_strtol
    {1887, 1, BuiltinFlags::kNone},                        // __builtin_strtold
    {1895, 1, BuiltinFlags::kNone},                        // __builtin_strtoll
    {1904, 1, BuiltinFlags::kNone},                        // __builtin_strtoul
    {1913, 1, BuiltinFlags::kNone},                        // __builtin_strtoull
    {1922, 1, BuiltinFlags::kNone},                        // __builtin_strxfrm
    {1930, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},  // __builtin_sub_overflow
    {1933, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tan
    {1936, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tanf
    {1939, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tanh
    {1942, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tanhf
    {1945, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tanhl
    {1948, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tanl
    {1951, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tgamma
    {1954, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tgammaf
    {1957, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_tgammal
    {1960, 1, BuiltinFlags::kNoexcept},                    // __builtin_tolower
    {1963, 1, BuiltinFlags::kNoexcept},                    // __builtin_toupper
    {1966, 1,
     BuiltinFlags::kNoexcept | BuiltinFlags::kNoReturn},  // __builtin_trap
    {1968, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_trunc
    {1971, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_truncf
    {1974, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_truncl
    {1977, 1,
     BuiltinFlags::kNoexcept |
         BuiltinFlags::kNoReturn},       // __builtin_unreachable
    {1979, 1, BuiltinFlags::kNoexcept},  // __builtin_va_copy
    {1985, 1, BuiltinFlags::kNoexcept},  // __builtin_va_end
    {1989, 1, BuiltinFlags::kNoexcept},  // __builtin_va_start
    {1994, 1, BuiltinFlags::kNoexcept},  // __builtin_vsnprintf
    {2004, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wcschr
    {2011, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wcscmp
    {2019, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wcslen
    {2024, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wcsncmp
    {2033, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wmemchr
    {2041, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wmemcmp
    {2050, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wmemcpy
    {2059, 1,
     BuiltinFlags::kConstexpr | BuiltinFlags::kNoexcept},  // __builtin_wmemmove
    {2068, 1, BuiltinFlags::kNone},  // __c11_atomic_compare_exchange_strong
    {2078, 1, BuiltinFlags::kNone},  // __c11_atomic_compare_exchange_weak
    {2088, 1, BuiltinFlags::kNone},  // __c11_atomic_exchange
    {2095, 1, BuiltinFlags::kNone},  // __c11_atomic_fetch_add
    {2102, 1, BuiltinFlags::kNone},  // __c11_atomic_fetch_and
    {2109, 1, BuiltinFlags::kNone},  // __c11_atomic_fetch_nand
    {2116, 1, BuiltinFlags::kNone},  // __c11_atomic_fetch_or
    {2123, 1, BuiltinFlags::kNone},  // __c11_atomic_fetch_sub
    {2130, 1, BuiltinFlags::kNone},  // __c11_atomic_fetch_xor
    {2137, 1, BuiltinFlags::kNone},  // __c11_atomic_init
    {2143, 1,
     BuiltinFlags::kConstexpr |
         BuiltinFlags::kNoexcept},       // __c11_atomic_is_lock_free
    {2146, 1, BuiltinFlags::kNone},      // __c11_atomic_load
    {2152, 1, BuiltinFlags::kNoexcept},  // __c11_atomic_signal_fence
    {2155, 1, BuiltinFlags::kNone},      // __c11_atomic_store
    {2162, 1, BuiltinFlags::kNoexcept},  // __c11_atomic_thread_fence
};

static_assert(
    std::size(kBuiltinSignatures) ==
    static_cast<std::size_t>(BuiltinFunctionKind::T___C11_ATOMIC_THREAD_FENCE) +
        1);

}  // namespace cxx
