import * as monaco from "monaco-editor"

export function registerLlvmLanguage() {
  if (monaco.languages.getLanguages().some((lang) => lang.id === "llvm")) {
    return
  }

  monaco.languages.register({ id: "llvm" })

  monaco.languages.setMonarchTokensProvider("llvm", {
    defaultToken: "",
    tokenPostfix: ".llvm",

    keywords: [
      "define",
      "declare",
      "ret",
      "br",
      "switch",
      "indirectbr",
      "invoke",
      "resume",
      "unreachable",
      "call",
      "phi",
      "select",
      "va_arg",
      "landingpad",
      "catchpad",
      "cleanuppad",
      "alloca",
      "load",
      "store",
      "fence",
      "cmpxchg",
      "atomicrmw",
      "getelementptr",
      "trunc",
      "zext",
      "sext",
      "fptrunc",
      "fpext",
      "fptoui",
      "fptosi",
      "uitofp",
      "sitofp",
      "ptrtoint",
      "inttoptr",
      "bitcast",
      "addrspacecast",
      "icmp",
      "fcmp",
      "extractelement",
      "insertelement",
      "shufflevector",
      "extractvalue",
      "insertvalue",
      "add",
      "fadd",
      "sub",
      "fsub",
      "mul",
      "fmul",
      "udiv",
      "sdiv",
      "fdiv",
      "urem",
      "srem",
      "frem",
      "shl",
      "lshr",
      "ashr",
      "and",
      "or",
      "xor",
      "target",
      "source_filename",
      "module",
      "asm",
      "global",
      "constant",
      "private",
      "internal",
      "external",
      "linkonce",
      "weak",
      "common",
      "appending",
      "extern_weak",
      "linkonce_odr",
      "weak_odr",
      "dso_local",
      "dso_preemptable",
      "thread_local",
      "dllimport",
      "dllexport",
      "attributes",
      "align",
      "noundef",
      "nonnull",
      "readonly",
      "nounwind",
      "uwtable",
      "section",
      "comdat",
      "type",
      "opaque",
      "distinct",
      "true",
      "false",
      "null",
      "undef",
      "zeroinitializer",
      "to",
      "nsw",
      "nuw",
      "exact",
      "volatile",
      "tail",
      "musttail",
      "unwind",
      "personality",
    ],

    typeKeywords: [
      "void",
      "half",
      "bfloat",
      "float",
      "double",
      "fp128",
      "x86_fp80",
      "ppc_fp128",
      "ptr",
      "label",
      "token",
      "metadata",
      "x86_mmx",
    ],

    tokenizer: {
      root: [
        [/;.*$/, "comment"],

        [/@[a-zA-Z0-9_.$"\\-]+/, "identifier"],

        [/%[a-zA-Z0-9_.$"\\-]+/, "variable"],

        [/![a-zA-Z0-9_.]+/, "metatag"],

        [/\bi[0-9]+\b/, "type"],

        [
          /[a-zA-Z_][a-zA-Z0-9_]*/,
          {
            cases: {
              "@keywords": "keyword",
              "@typeKeywords": "type",
              "@default": "identifier",
            },
          },
        ],

        [/"([^"\\]|\\.)*"/, "string"],

        [/-?\b0x[0-9a-fA-F]+\b/, "number"],
        [/-?\b\d+(\.\d+)?(e[+-]?\d+)?\b/, "number"],

        [/->/, "operator"],
        [/[{}()<>[\],:=*]/, "delimiter"],
      ],
    },
  })

  monaco.languages.setLanguageConfiguration("llvm", {
    comments: {
      lineComment: ";",
    },
    brackets: [
      ["{", "}"],
      ["[", "]"],
      ["(", ")"],
      ["<", ">"],
    ],
    autoClosingPairs: [
      { open: "{", close: "}" },
      { open: "[", close: "]" },
      { open: "(", close: ")" },
      { open: '"', close: '"' },
    ],
  })
}
