// Copyright (c) 2026 Roberto Raggi <roberto.raggi@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { cpy_header } from "./cpy_header.ts";
import { BUILTIN_FUNCTION_DEFS, type BuiltinDef } from "./builtins.ts";
import { BUILTIN_FUNCTIONS } from "./tokens.ts";
import {
  BUILTIN_LEAF_TYPES,
  BUILTIN_OPS,
  encodeSignature,
  opValue,
  prototypesOf,
} from "./builtinSignature.ts";
import * as fs from "node:fs";

function enumName(builtinName: string): string {
  return `BuiltinFunctionKind::T_${builtinName.toUpperCase()}`;
}

function flagsOf(builtin: BuiltinDef): string {
  const flags: string[] = [];
  if (builtin.constexpr) flags.push(`BuiltinFlags::kConstexpr`);
  if (builtin.consteval) flags.push(`BuiltinFlags::kConsteval`);
  if (builtin.noexcept) flags.push(`BuiltinFlags::kNoexcept`);
  if (builtin.noreturn) flags.push(`BuiltinFlags::kNoReturn`);
  if (!flags.length) return `BuiltinFlags::kNone`;
  return flags.join(` | `);
}

export function gen_builtins_signatures_h({ output }: { output: string }) {
  const lines: string[] = [];

  lines.push(`// Generated by gen_builtins_signatures_h.ts`);
  lines.push(cpy_header);
  lines.push(`#pragma once`);
  lines.push(``);
  lines.push(`#include <cxx/builtin_signature.h>`);
  lines.push(`#include <cxx/control.h>`);
  lines.push(``);
  lines.push(`namespace cxx {`);
  lines.push(``);

  lines.push(`enum class BuiltinTypeOp : std::uint8_t {`);
  for (const op of BUILTIN_OPS) lines.push(`  ${op},`);
  lines.push(`};`);
  lines.push(``);

  lines.push(
    `[[nodiscard]] inline auto decodeBuiltinLeafType(Control* control,`,
  );
  lines.push(
    `                                                BuiltinTypeOp op)`,
  );
  lines.push(`    -> const Type* {`);
  lines.push(`  switch (op) {`);
  for (const { op, expr } of BUILTIN_LEAF_TYPES) {
    lines.push(`    case BuiltinTypeOp::${op}:`);
    lines.push(`      return ${expr};`);
  }
  lines.push(`    default:`);
  lines.push(`      return nullptr;`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);

  const byName = new Map(BUILTIN_FUNCTION_DEFS.map((b) => [b.name, b]));

  const blob: number[] = [];
  const entries: {
    name: string;
    offset: number;
    count: number;
    flags: string;
  }[] = [];

  for (const name of BUILTIN_FUNCTIONS) {
    const builtin = byName.get(name);
    if (!builtin) throw new Error(`no definition for builtin '${name}'`);
    entries.push({
      name,
      offset: blob.length,
      count: prototypesOf(builtin).length,
      flags: flagsOf(builtin),
    });
    for (const op of encodeSignature(builtin)) blob.push(opValue(op));
  }

  lines.push(`inline constexpr std::uint8_t kBuiltinSignatureOps[] = {`);
  for (let i = 0; i < blob.length; i += 20) {
    lines.push(`    ${blob.slice(i, i + 20).join(", ")},`);
  }
  lines.push(`};`);
  lines.push(``);

  lines.push(`inline constexpr BuiltinSignature kBuiltinSignatures[] = {`);
  lines.push(`    {},`);
  for (const { name, offset, count, flags } of entries) {
    lines.push(`    {${offset}, ${count}, ${flags}},  // ${name}`);
  }
  lines.push(`};`);
  lines.push(``);

  const last = BUILTIN_FUNCTIONS.at(-1);
  if (!last) throw new Error(`no builtin functions`);
  lines.push(`static_assert(std::size(kBuiltinSignatures) ==`);
  lines.push(`              static_cast<std::size_t>(${enumName(last)}) + 1);`);
  lines.push(``);
  lines.push(`}  // namespace cxx`);
  lines.push(``);

  fs.writeFileSync(output, lines.join("\n"));
}
