// Copyright (c) 2026 Roberto Raggi <roberto.raggi@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import * as fs from "node:fs";
import { cpy_header } from "./cpy_header.ts";
import {
  cppType,
  emitterProtocol,
  type ProtocolMethod,
  type ProtocolStruct,
  type Wire,
} from "./emitterProtocol.ts";
import type { ModelIndex } from "./parseModel.ts";

function encode(wire: Wire, expr: string): string {
  switch (wire.kind) {
    case "void":
      throw new Error("void has no representation");
    case "span":
    case "vector":
      return `arrayVal(${expr}, [](const ${cppType(wire.element)}& item) { return ${encode(wire.element, "item")}; })`;
    case "optional":
      return `optionalVal(${expr}, [](const ${cppType(wire.element)}& item) { return ${encode(wire.element, "item")}; })`;
    default:
      return `toVal(${expr})`;
  }
}

function decode(wire: Wire, expr: string): string {
  switch (wire.kind) {
    case "bool":
      return `toBool(${expr})`;
    case "number":
      return `toNumber<${wire.cpp}>(${expr})`;
    case "location":
      return `cxx::SourceLocation(toNumber<unsigned>(${expr}))`;
    case "enum":
      return `toEnum<${wire.cpp}>(${expr})`;
    case "handle":
      return `toHandle<${wire.tag}>(${expr})`;
    case "vector":
      if (wire.element.kind !== "handle")
        throw new Error(
          `a delegate cannot return a vector of ${wire.element.kind}`,
        );
      return `toHandleVector<${wire.element.tag}>(${expr})`;
    default:
      throw new Error(`a delegate cannot return a ${wire.kind}`);
  }
}

function structConverter(struct: ProtocolStruct): string[] {
  const lines: string[] = [];
  lines.push(`inline auto toVal(const ${struct.cpp}& value) -> val {`);
  lines.push(`  auto result = val::object();`);
  for (const field of struct.fields)
    lines.push(
      `  result.set("${field.name}", ${encode(field.wire, `value.${field.name}`)});`,
    );
  lines.push(`  return result;`);
  lines.push(`}`);
  return lines;
}

function signature(method: ProtocolMethod): string {
  const parameters = method.parameters
    .map((parameter) => {
      const type = cppType(parameter.wire);
      return parameter.byConstRef
        ? `const ${type}& ${parameter.name}`
        : `${type} ${parameter.name}`;
    })
    .join(", ");
  if (method.result.kind === "void")
    return `void ${method.name}(${parameters}) override`;
  return `auto ${method.name}(${parameters}) -> ${cppType(method.result)} override`;
}

function body(method: ProtocolMethod): string {
  const args = method.parameters.map((parameter) =>
    encode(parameter.wire, parameter.name),
  );
  const call = `delegate_.call<val>("${method.name}"${args.map((a) => `, ${a}`).join("")})`;
  if (method.result.kind === "void") return `${call};`;
  return `return ${decode(method.result, call)};`;
}

export function gen_emitter_delegate_h({
  model,
  output,
}: {
  model: ModelIndex;
  output: string;
}) {
  const protocol = emitterProtocol(model);
  const lines: string[] = [];
  const emit = (line = "") => lines.push(line);

  emit(`// Generated by gen_emitter_delegate_h.ts`);
  emit(cpy_header);
  emit(`#pragma once`);
  emit();
  emit(`#include <cxx/codegen/emitter.h>`);
  emit();
  emit(`#include "emitter_marshal.h"`);
  emit();
  emit(`namespace cxx::js {`);
  emit();

  for (const entry of protocol.enums) {
    emit(`inline auto toVal(${entry.cpp} value) -> val {`);
    emit(`  switch (value) {`);
    for (const enumerator of entry.enumerators)
      emit(
        `    case ${entry.cpp}::${enumerator.name}:\n      return val("${enumerator.name}");`,
      );
    emit(`  }`);
    emit(`  return val::undefined();`);
    emit(`}`);
    emit();
    emit(`template <>`);
    emit(
      `inline auto toEnum<${entry.cpp}>(const val& value) -> ${entry.cpp} {`,
    );
    emit(`  const auto name = toString(value);`);
    for (const enumerator of entry.enumerators)
      emit(
        `  if (name == "${enumerator.name}") return ${entry.cpp}::${enumerator.name};`,
      );
    emit(`  return ${entry.cpp}{};`);
    emit(`}`);
    emit();
  }

  for (const struct of protocol.structs)
    emit(`auto toVal(const ${struct.cpp}& value) -> val;`);
  emit();

  for (const struct of protocol.structs) {
    for (const line of structConverter(struct)) emit(line);
    emit();
  }

  emit(`class JsEmitter final : public ir::Emitter {`);
  emit(` public:`);
  emit(
    `  explicit JsEmitter(val delegate) : delegate_(std::move(delegate)) {}`,
  );
  emit();

  for (const entry of protocol.undelegated) {
    emit(`  auto ${entry.name}() -> ${entry.cppResult} override {`);
    emit(`    ${entry.cppBody}`);
    emit(`  }`);
    emit();
  }

  for (const method of protocol.methods) {
    emit(`  ${signature(method)} {`);
    emit(`    ${body(method)}`);
    emit(`  }`);
    emit();
  }

  emit(` private:`);
  emit(`  val delegate_;`);
  emit(`};`);
  emit();
  emit(`}  // namespace cxx::js`);
  emit();

  fs.writeFileSync(output, lines.join("\n"));
}
