// Copyright (c) 2026 Roberto Raggi <roberto.raggi@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import * as fs from "node:fs";
import { cpy_header } from "./cpy_header.ts";
import { emitterProtocol, tsIdentifier, tsType } from "./emitterProtocol.ts";
import type { ModelIndex } from "./parseModel.ts";

export function gen_emitter_ts({
  model,
  output,
}: {
  model: ModelIndex;
  output: string;
}) {
  const protocol = emitterProtocol(model);
  const lines: string[] = [];
  const emit = (line = "") => lines.push(line);

  emit(`// Generated by gen_emitter_ts.ts`);
  emit(cpy_header);

  for (const tag of protocol.handles)
    emit(`export type ${tag.slice(0, -"Tag".length)}Ref = number;`);
  emit();

  emit(`export type TokenIndex = number;`);
  emit();

  for (const entry of protocol.enums) {
    emit(`export enum ${entry.name} {`);
    for (const enumerator of entry.enumerators)
      emit(`  ${enumerator.name} = ${enumerator.value},`);
    emit(`}`);
    emit();
  }

  for (const struct of protocol.structs) {
    emit(`export interface ${struct.name} {`);
    for (const field of struct.fields)
      emit(`  ${field.name}: ${tsType(field.wire, "in")};`);
    emit(`}`);
    emit();
  }

  emit(`export interface EmitterDelegate {`);
  for (const method of protocol.methods) {
    const parameters = method.parameters
      .map((parameter) => {
        const type =
          parameter.wire.kind === "location"
            ? "TokenIndex"
            : tsType(parameter.wire, "in");
        return `${tsIdentifier(parameter.name)}: ${type}`;
      })
      .join(", ");
    emit(`  ${method.name}(${parameters}): ${tsType(method.result, "out")};`);
  }
  emit(`}`);
  emit();

  fs.writeFileSync(output, lines.join("\n"));
}
