// Copyright (c) 2026 Roberto Raggi <roberto.raggi@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { cpy_header } from "./cpy_header.ts";
import { BUILTIN_MACRO_DEFS } from "./builtins.ts";
import * as fs from "node:fs";

export function gen_builtins_h({ output }: { output: string }) {
  const lines: string[] = [];

  lines.push(`// Generated by gen_builtins_h.ts`);
  lines.push(cpy_header);
  lines.push(`#pragma once`);
  lines.push(``);
  lines.push(`// clang-format off`);
  lines.push(`static constexpr const char* builtinsSource = R"(`);

  if (BUILTIN_MACRO_DEFS.length) {
    lines.push(``);
    lines.push(`#define __cxx_builtin_arity(_1, _2, selected, ...) selected`);
    lines.push(
      `#define __cxx_builtin_overload(one, two, ...) ` +
        `__cxx_builtin_arity(__VA_ARGS__, two, one)`,
    );
  }

  for (const b of BUILTIN_MACRO_DEFS) {
    const macro = b.genericMacro!;
    const { parameter, zeroFallbackParameter, zeroFallbackType, associations } =
      macro;
    const stem = b.name.replace(/^__builtin_/, "");
    const dispatch = `__cxx_${stem}_dispatch`;

    lines.push(``);
    lines.push(`#define ${dispatch}(${parameter}) _Generic((${parameter}), \\`);
    const continuation = ", \\";
    associations.forEach(({ type, expansion }, index) => {
      const last = index === associations.length - 1;
      const separator = last ? ")" : continuation;
      lines.push(`    ${type}: ${expansion}${separator}`);
    });

    if (!zeroFallbackParameter) {
      lines.push(`#define ${b.name}(${parameter}) ${dispatch}(${parameter})`);
      continue;
    }

    const withFallback = `__cxx_${stem}_or`;
    const fallbackValue = zeroFallbackType
      ? `_Generic((${zeroFallbackParameter}), ` +
        `${zeroFallbackType}: (${zeroFallbackParameter}))`
      : `(${zeroFallbackParameter})`;
    lines.push(
      `#define ${withFallback}(${parameter}, ${zeroFallbackParameter}) ` +
        `((${parameter}) ? ${dispatch}(${parameter}) : ${fallbackValue})`,
    );
    lines.push(
      `#define ${b.name}(...) ` +
        `__cxx_builtin_overload(${dispatch}, ${withFallback}, __VA_ARGS__)(__VA_ARGS__)`,
    );
  }

  lines.push(``);
  lines.push(`#ifdef __cplusplus`);
  lines.push(``);
  lines.push(
    `template <template <class IntSeqT, IntSeqT... Ints> class IntSeq, class T, T N>`,
  );
  lines.push(`using __make_integer_seq = void;`);
  lines.push(``);
  lines.push(`template <__SIZE_TYPE__ Index, class... Ts>`);
  lines.push(`using __type_pack_element = void;`);
  lines.push(``);
  lines.push(`template <template <class... Args> class BaseTemplate,`);
  lines.push(`          template <class TypeMember> class HasTypeMember,`);
  lines.push(`          class HasNoTypeMember,`);
  lines.push(`          class... Ts>`);
  lines.push(`using __builtin_common_type = void;`);
  lines.push(``);

  lines.push(`void* operator new(__SIZE_TYPE__);`);
  lines.push(`void* operator new[](__SIZE_TYPE__);`);
  lines.push(`void operator delete(void*) noexcept;`);
  lines.push(`void operator delete[](void*) noexcept;`);
  lines.push(`void operator delete(void*, __SIZE_TYPE__) noexcept;`);
  lines.push(`void operator delete[](void*, __SIZE_TYPE__) noexcept;`);
  lines.push(``);
  lines.push(`#endif`);

  lines.push(`)";`);
  lines.push(`// clang-format on`);
  lines.push(``);

  fs.writeFileSync(output, lines.join("\n"));
}
