if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
    set(cxx_native_target "${CMAKE_HOST_SYSTEM_PROCESSOR}-apple-macosx")
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(cxx_native_target "${CMAKE_HOST_SYSTEM_PROCESSOR}-linux-gnu")
else()
    message(FATAL_ERROR "The native self-host presets require macOS or Linux")
endif()

set(CMAKE_C_COMPILER_TARGET "${cxx_native_target}" CACHE STRING "C target triple")
set(CMAKE_CXX_COMPILER_TARGET "${cxx_native_target}" CACHE STRING "C++ target triple")
