// Generated by gen_builtins_codegen_h.ts
// Copyright (c) 2026 Roberto Raggi <roberto.raggi@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

auto cxx::Codegen::ExpressionVisitor::codegenBuiltinDispatch(
    cxx::CallExpressionAST* ast, cxx::BuiltinFunctionKind kind)
    -> std::optional<ExpressionResult> {
  switch (kind) {
    case BuiltinFunctionKind::T___BUILTIN_COMPLEX:
      return codegenBuiltinComplex(ast);

    case BuiltinFunctionKind::T___BUILTIN_BZERO:
      return codegenBuiltinBzero(ast);

    case BuiltinFunctionKind::T___BUILTIN_INF:
      return codegenBuiltinHugeVal(ast);

    case BuiltinFunctionKind::T___BUILTIN_INFF:
      return codegenBuiltinHugeValf(ast);

    case BuiltinFunctionKind::T___BUILTIN_INFL:
      return codegenBuiltinHugeVall(ast);

    case BuiltinFunctionKind::T___BUILTIN_ISFINITE:
      return codegenBuiltinIsFinite(ast);

    case BuiltinFunctionKind::T___BUILTIN_ISINF:
      return codegenBuiltinIsInf(ast);

    case BuiltinFunctionKind::T___BUILTIN_ISNAN:
      return codegenBuiltinIsNan(ast);

    case BuiltinFunctionKind::T___BUILTIN_HUGE_VAL:
      return codegenBuiltinHugeVal(ast);

    case BuiltinFunctionKind::T___BUILTIN_HUGE_VALF:
      return codegenBuiltinHugeValf(ast);

    case BuiltinFunctionKind::T___BUILTIN_HUGE_VALL:
      return codegenBuiltinHugeVall(ast);

    case BuiltinFunctionKind::T___BUILTIN_NANS:
      return codegenBuiltinNans(ast);

    case BuiltinFunctionKind::T___BUILTIN_NANSF:
      return codegenBuiltinNansf(ast);

    case BuiltinFunctionKind::T___BUILTIN_NANSL:
      return codegenBuiltinNansl(ast);

    case BuiltinFunctionKind::T___BUILTIN_ALLOCA:
      return codegenBuiltinAlloca(ast);

    case BuiltinFunctionKind::T___BUILTIN_ASSUME_ALIGNED:
      return codegenBuiltinAssumeAligned(ast);

    case BuiltinFunctionKind::T___BUILTIN_MUL_OVERFLOW:
      return codegenBuiltinArithmeticOverflow(ast);

    case BuiltinFunctionKind::T___BUILTIN_ADDRESSOF:
      return codegenBuiltinAddressof(ast);

    case BuiltinFunctionKind::T___BUILTIN_SIGNBIT:
      return codegenBuiltinSignbit(ast);

    case BuiltinFunctionKind::T___BUILTIN_CLZ:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_CLZL:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_CLZLL:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_CTZ:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_CTZL:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_CTZLL:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_POPCOUNT:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_POPCOUNTL:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_POPCOUNTLL:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_PARITY:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_PARITYL:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_PARITYLL:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_FFS:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_FFSL:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_FFSLL:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_CLRSB:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_CLRSBL:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_CLRSBLL:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_CLZS:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_CTZS:
      return codegenBuiltinBitCount(ast);

    case BuiltinFunctionKind::T___BUILTIN_ISGREATER:
      return codegenBuiltinFloatComparison(ast);

    case BuiltinFunctionKind::T___BUILTIN_ISGREATEREQUAL:
      return codegenBuiltinFloatComparison(ast);

    case BuiltinFunctionKind::T___BUILTIN_ISLESS:
      return codegenBuiltinFloatComparison(ast);

    case BuiltinFunctionKind::T___BUILTIN_ISLESSEQUAL:
      return codegenBuiltinFloatComparison(ast);

    case BuiltinFunctionKind::T___BUILTIN_ISLESSGREATER:
      return codegenBuiltinFloatComparison(ast);

    case BuiltinFunctionKind::T___BUILTIN_ISUNORDERED:
      return codegenBuiltinFloatComparison(ast);

    case BuiltinFunctionKind::T___BUILTIN_ADD_OVERFLOW:
      return codegenBuiltinArithmeticOverflow(ast);

    case BuiltinFunctionKind::T___BUILTIN_SUB_OVERFLOW:
      return codegenBuiltinArithmeticOverflow(ast);

    default:
      return std::nullopt;
  }
}
