name: Node.js Package

on:
  workflow_dispatch:

  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7

      - name: Install emsdk
        uses: ./.github/actions/setup-emsdk

      - uses: actions/setup-node@v6
        with:
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          npm ci

      - name: Download MLIR
        run: |
          npm run download-mlir
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true

      - name: Build
        run: |
          source "/opt/emsdk/emsdk_env.sh"
          export EMSCRIPTEN_ROOT="/opt/emsdk/upstream/emscripten"
          npm run build:cxx-frontend

      - name: Publish
        working-directory: packages/cxx-frontend
        run: npm publish
